uWindows: External/SDFat/SysCall.h File Reference
SysCall.h File Reference
SysCall class.
Classes
class SysCall
SysCall - Class to wrap system calls.
Macros
#define F(str) (str)
Functions
uint16_t curTimeMS ()
Detailed Description
SysCall class.
Definition in file SysCall.h.
Macro Definition Documentation
F
#define F (str) (str)
Define macro for strings stored in flash.
Definition at line 42 of file SysCall.h.
Referenced by SdFileSystem< SdSpiCardEX >::errorPrint(), and SdFileSystem< SdSpiCardEX >::initErrorPrint().
Function Documentation
curTimeMS()
uint16_t curTimeMS () inline
Returns
the time in milliseconds.
Definition at line 46 of file SysCall.h.
Referenced by SdSpiCard::begin(), SdSpiCard::isBusy(), SdSpiCard::readData(), and SdSpiCard::readStop().