uWindows: UIElements/FT8XX/UIPrimitives.cpp File Reference
UIPrimitives.cpp File Reference
#include "UIPrimitives.h"
Macros
#define PAINT_ALPHA() GD.BlendFunc(ONE, ONE_MINUS_SRC_ALPHA)
#define CLEAR_ALPHA() GD.BlendFunc(ZERO, ONE_MINUS_SRC_ALPHA)
Functions
void circle (int x, int y, int r0, int r1)
Macro Definition Documentation
CLEAR_ALPHA
#define CLEAR_ALPHA () GD.BlendFunc(ZERO, ONE_MINUS_SRC_ALPHA)
Definition at line 212 of file UIPrimitives.cpp.
Referenced by circle().
PAINT_ALPHA
#define PAINT_ALPHA () GD.BlendFunc(ONE, ONE_MINUS_SRC_ALPHA)
Definition at line 211 of file UIPrimitives.cpp.
Referenced by circle().
Function Documentation
circle()
void circle (int x, int y, int r0, int r1)
Definition at line 214 of file UIPrimitives.cpp.
References GDClass::Begin(), CLEAR_ALPHA, GD, PAINT_ALPHA, POINTS, GDClass::PointSize(), and GDClass::Vertex2f().
Referenced by UIPrimitives::CircleOutline().