uWindows: External/SDFat/FatLib/FmtNumber.h File Reference
FmtNumber.h File Reference
#include <math.h>
#include <stdint.h>
Functions
bool isDigit (char c)
bool isSpace (char c)
char * fmtDec (uint16_t n, char *p)
char * fmtDec (uint32_t n, char *p)
char * fmtFloat (float value, char *p, uint8_t prec)
char * fmtFloat (float value, char *ptr, uint8_t prec, char expChar)
char * fmtHex (uint32_t n, char *p)
float scale10 (float v, int8_t n)
float scanFloat (const char *str, char **ptr)
Function Documentation
fmtDec() [1/2]
char* fmtDec (uint16_t n, char * p)
Definition at line 186 of file FmtNumber.cpp.
Referenced by fmtFloat(), isSpace(), StdioStream::printDec(), and FatFile::printFileSize().
fmtDec() [2/2]
char* fmtDec (uint32_t n, char * p)
Definition at line 211 of file FmtNumber.cpp.
fmtFloat() [1/2]
char* fmtFloat (float value, char * p, uint8_t prec)
Definition at line 234 of file FmtNumber.cpp.
Referenced by StdioStream::printDec(), and FatFile::printField().
fmtFloat() [2/2]
char* fmtFloat (float value, char * ptr, uint8_t prec, char expChar)
Print a number followed by a field terminator.
Parameters
[in] value The number to be printed.
[in] ptr Pointer to last char in buffer.
[in] prec Number of digits after decimal point.
[in] expChar Use exp format if non zero.
Returns
Pointer to first character of result.
Definition at line 287 of file FmtNumber.cpp.
References fmtDec(), and scale10().
fmtHex()
char* fmtHex (uint32_t n, char * p)
Definition at line 365 of file FmtNumber.cpp.
Referenced by StdioStream::printHex().
isDigit()
bool isDigit (char c) inline
Definition at line 23 of file FmtNumber.h.
Referenced by scanFloat().
isSpace()
bool isSpace (char c) inline
Definition at line 26 of file FmtNumber.h.
References fmtDec().
Referenced by scanFloat().
scale10()
float scale10 (float v, int8_t n)
Definition at line 162 of file FmtNumber.cpp.
Referenced by fmtFloat(), and scanFloat().
scanFloat()
float scanFloat (const char * str, char ** ptr)
Definition at line 374 of file FmtNumber.cpp.
References EXP_LIMIT, isDigit(), isSpace(), and scale10().