uWindows: SdSpiAltDriver Class Reference
SdSpiAltDriver Class Reference
Optimized SPI class for access to SD and SDHC flash memory cards.
#include <SdSpiDriver.h>
Public Member Functions
void activate ()
void deactivate ()
void begin (uint8_t csPin)
uint8_t receive ()
uint8_t receive (uint8_t *buf, size_t n)
void send (uint8_t data)
void send (const uint8_t *buf, size_t n)
void select ()
void setSpiSettings (SPISettings spiSettings)
void unselect ()
Detailed Description
Optimized SPI class for access to SD and SDHC flash memory cards.
Definition at line 124 of file SdSpiDriver.h.
Member Function Documentation
activate()
void SdSpiAltDriver::activate ()
Activate SPI hardware.
begin()
void SdSpiAltDriver::begin (uint8_t csPin)
Initialize the SPI bus.
Parameters
[in] csPin SD card chip select pin.
deactivate()
void SdSpiAltDriver::deactivate ()
Deactivate SPI hardware.
receive() [1/2]
uint8_t SdSpiAltDriver::receive ()
Receive a byte.
Returns
The byte.
receive() [2/2]
uint8_t SdSpiAltDriver::receive (uint8_t * buf, size_t n)
Receive multiple bytes.
Parameters
[out] buf Buffer to receive the data.
[in] n Number of bytes to receive.
Returns
Zero for no error or nonzero error code.
select()
void SdSpiAltDriver::select () inline
Set CS low.
Definition at line 161 of file SdSpiDriver.h.
send() [1/2]
void SdSpiAltDriver::send (uint8_t data)
Send a byte.
Parameters
[in] data Byte to send
send() [2/2]
void SdSpiAltDriver::send (const uint8_t * buf, size_t n)
Send multiple bytes.
Parameters
[in] buf Buffer for data to be sent.
[in] n Number of bytes to send.
setSpiSettings()
void SdSpiAltDriver::setSpiSettings (SPISettings spiSettings) inline
Save SPISettings.
Parameters
[in] spiSettings SPI speed, mode, and byte order.
Definition at line 168 of file SdSpiDriver.h.
unselect()
void SdSpiAltDriver::unselect () inline
Set CS high.
Definition at line 172 of file SdSpiDriver.h.
References SdSpiLibDriver::activate(), SdSpiLibDriver::begin(), SdSpiLibDriver::deactivate(), SdSpiLibDriver::receive(), SdSpiLibDriver::select(), SdSpiLibDriver::send(), SdSpiLibDriver::setSpiSettings(), and SdSpiLibDriver::unselect().
The documentation for this class was generated from the following file:
External/SDFat/SpiDriver/SdSpiDriver.h