uWindows: sdcard Class Reference
sdcard Class Reference
#include <GD3.h>
Public Member Functions
void sel ()
void desel ()
void sd_delay (byte n)
void cmd (byte cmd, uint32_t lba=0, uint8_t crc=0x95)
byte response ()
byte R1 ()
byte sdR3 (uint32_t &ocr)
byte sdR7 ()
void appcmd (byte cc, uint32_t lba=0)
void begin (byte p)
void cmd17 (uint32_t off)
void rdn (byte *d, uint32_t off, uint16_t n)
uint32_t rd4 (uint32_t off)
uint16_t rd2 (uint32_t off)
byte rd (uint32_t off)
Public Attributes
byte pin
byte ccs
byte type
uint16_t sectors_per_cluster
uint16_t reserved_sectors
uint16_t max_root_dir_entries
uint16_t sectors_per_fat
uint16_t cluster_size
uint32_t root_dir_first_cluster
uint32_t o_partition
uint32_t o_fat
uint32_t o_root
uint32_t o_data
Detailed Description
Definition at line 157 of file GD3.h.
Member Function Documentation
appcmd()
void sdcard::appcmd (byte cc, uint32_t lba = 0) inline
Definition at line 231 of file GD3.h.
begin()
void sdcard::begin (byte p) inline
Definition at line 236 of file GD3.h.
References FAT16, FAT32, INFO, and REPORT.
cmd()
void sdcard::cmd (byte cmd, uint32_t lba = 0, uint8_t crc = 0x95) inline
Definition at line 173 of file GD3.h.
References DD.
cmd17()
void sdcard::cmd17 (uint32_t off) inline
Definition at line 362 of file GD3.h.
Referenced by Reader::nextcluster2(), and Reader::readsector().
desel()
void sdcard::desel () inline
Definition at line 163 of file GD3.h.
Referenced by Reader::fetch512().
R1()
byte sdcard::R1 () inline
Definition at line 204 of file GD3.h.
rd()
byte sdcard::rd (uint32_t off) inline
Definition at line 397 of file GD3.h.
rd2()
uint16_t sdcard::rd2 (uint32_t off) inline
Definition at line 391 of file GD3.h.
Referenced by Reader::nextcluster().
rd4()
uint32_t sdcard::rd4 (uint32_t off) inline
Definition at line 385 of file GD3.h.
Referenced by Reader::nextcluster().
rdn()
void sdcard::rdn (byte * d, uint32_t off, uint16_t n) inline
Definition at line 372 of file GD3.h.
Referenced by Reader::openfile(), and Reader::seek().
response()
byte sdcard::response () inline
Definition at line 193 of file GD3.h.
References DD.
sd_delay()
void sdcard::sd_delay (byte n) inline
Definition at line 167 of file GD3.h.
References DD.
sdR3()
byte sdcard::sdR3 (uint32_t & ocr) inline
Definition at line 211 of file GD3.h.
sdR7()
byte sdcard::sdR7 () inline
Definition at line 221 of file GD3.h.
sel()
void sdcard::sel () inline
Definition at line 159 of file GD3.h.
Member Data Documentation
ccs
byte sdcard::ccs
Definition at line 403 of file GD3.h.
cluster_size
uint16_t sdcard::cluster_size
Definition at line 410 of file GD3.h.
Referenced by Reader::readsector(), Reader::seek(), and Reader::skipcluster().
max_root_dir_entries
uint16_t sdcard::max_root_dir_entries
Definition at line 408 of file GD3.h.
o_data
uint32_t sdcard::o_data
Definition at line 417 of file GD3.h.
Referenced by Reader::readsector().
o_fat
uint32_t sdcard::o_fat
Definition at line 415 of file GD3.h.
Referenced by Reader::nextcluster(), Reader::nextcluster2(), and Reader::seek().
o_partition
uint32_t sdcard::o_partition
Definition at line 414 of file GD3.h.
o_root
uint32_t sdcard::o_root
Definition at line 416 of file GD3.h.
Referenced by Reader::openfile().
pin
byte sdcard::pin
Definition at line 402 of file GD3.h.
reserved_sectors
uint16_t sdcard::reserved_sectors
Definition at line 407 of file GD3.h.
root_dir_first_cluster
uint32_t sdcard::root_dir_first_cluster
Definition at line 411 of file GD3.h.
sectors_per_cluster
uint16_t sdcard::sectors_per_cluster
Definition at line 406 of file GD3.h.
Referenced by Reader::readsector(), Reader::seek(), and Reader::skipsector().
sectors_per_fat
uint16_t sdcard::sectors_per_fat
Definition at line 409 of file GD3.h.
type
byte sdcard::type
Definition at line 405 of file GD3.h.
Referenced by Reader::begin(), Reader::nextcluster(), and Reader::seek().
The documentation for this class was generated from the following file:
External/GD3/GD3.h