uWindows: FatFileSystem Class Reference
FatFileSystem Class Reference
Integration class for the FatLib library.
#include <FatFileSystem.h>
Public Member Functions
bool begin (BlockDriver *blockDev, uint8_t part=0)
bool chdir (bool set_cwd=false)
bool chdir (const char *path, bool set_cwd=false)
void chvol ()
bool exists (const char *path)
void ls (print_t *pr, uint8_t flags=0)
void ls (print_t *pr, const char *path, uint8_t flags)
bool mkdir (const char *path, bool pFlag=true)
bool remove (const char *path)
bool rename (const char *oldPath, const char *newPath)
bool rmdir (const char *path)
bool truncate (const char *path, uint32_t length)
FatVolume * vol ()
FatFile * vwd ()
bool wipe (print_t *pr=0)
Public Member Functions inherited from FatVolume
FatVolume ()
uint8_t blocksPerCluster () const
uint32_t blocksPerFat () const
cache_t * cacheClear ()
uint32_t clusterCount () const
uint8_t clusterSizeShift () const
uint32_t dataStartBlock () const
uint8_t fatCount ()
uint32_t fatStartBlock () const
uint8_t fatType () const
int32_t freeClusterCount ()
bool init ()
bool init (uint8_t part)
uint16_t rootDirEntryCount () const
uint32_t rootDirStart () const
uint32_t volumeBlockCount () const
bool wipe (print_t *pr=0)
int8_t dbgFat (uint32_t n, uint32_t *v)
Detailed Description
Integration class for the FatLib library.
Definition at line 35 of file FatFileSystem.h.
Member Function Documentation
begin()
bool FatFileSystem::begin (BlockDriver * blockDev, uint8_t part = 0) inline
Initialize an FatFileSystem object.
Parameters
[in] blockDev Device block driver.
[in] part partition to initialize.
Returns
The value true is returned for success and the value false is returned for failure.
Definition at line 44 of file FatFileSystem.h.
References FatFile::close(), FatVolume::init(), ls(), FatFile::openRoot(), part, FatFile::setCwd(), and vwd().
Referenced by SdFileSystem< SdSpiCardEX >::begin(), and SdFat::fsBegin().
chdir() [1/2]
bool FatFileSystem::chdir (bool set_cwd = false) inline
Change a volume's working directory to root
Changes the volume's working directory to the SD's root directory. Optionally set the current working directory to the volume's working directory.
Parameters
[in] set_cwd Set the current working directory to this volume's working directory if true.
Returns
The value true is returned for success and the value false is returned for failure.
Definition at line 112 of file FatFileSystem.h.
References FatFile::close(), FatFile::openRoot(), FatFile::setCwd(), and vwd().
Referenced by chdir().
chdir() [2/2]
bool FatFileSystem::chdir (const char * path, bool set_cwd = false) inline
Change a volume's working directory
Changes the volume working directory to the path subdirectory. Optionally set the current working directory to the volume's working directory.
Example: If the volume's working directory is "/DIR", chdir("SUB") will change the volume's working directory from "/DIR" to "/DIR/SUB".
If path is "/", the volume's working directory will be changed to the root directory
Parameters
[in] path The name of the subdirectory.
[in] set_cwd Set the current working directory to this volume's working directory if true.
Returns
The value true is returned for success and the value false is returned for failure.
Definition at line 137 of file FatFileSystem.h.
References chdir(), FatFile::isDir(), O_READ, FatFile::open(), FatFile::setCwd(), and vwd().
chvol()
void FatFileSystem::chvol () inline
Set the current working directory to a volume's working directory.
This is useful with multiple SD cards.
The current working directory is changed to this volume's working directory.
This is like the Windows/DOS <drive letter>: command.
Definition at line 167 of file FatFileSystem.h.
References FatFile::setCwd(), and vwd().
exists()
bool FatFileSystem::exists (const char * path) inline
Test for the existence of a file.
Parameters
[in] path Path of the file to be tested for.
Returns
true if the file exists else false.
Definition at line 178 of file FatFileSystem.h.
References FatFile::exists(), and vwd().
ls() [1/2]
void FatFileSystem::ls (print_t * pr, uint8_t flags = 0) inline
List the directory contents of the volume working directory.
Parameters
[in] pr Print stream for list.
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Definition at line 194 of file FatFileSystem.h.
References FatFile::ls(), and vwd().
Referenced by begin().
ls() [2/2]
void FatFileSystem::ls (print_t * pr, const char * path, uint8_t flags) inline
List the directory contents of a directory.
Parameters
[in] pr Print stream for list.
[in] path directory to list.
[in] flags The inclusive OR of
LS_DATE - Print file modification date
LS_SIZE - Print file size.
LS_R - Recursive list of subdirectories.
Definition at line 212 of file FatFileSystem.h.
References FatFile::ls(), O_READ, FatFile::open(), and vwd().
mkdir()
bool FatFileSystem::mkdir (const char * path, bool pFlag = true) inline
Make a subdirectory in the volume working directory.
Parameters
[in] path A path with a valid 8.3 DOS name for the subdirectory.
[in] pFlag Create missing parent directories if true.
Returns
The value true is returned for success and the value false is returned for failure.
Definition at line 227 of file FatFileSystem.h.
References FatFile::mkdir(), and vwd().
remove()
bool FatFileSystem::remove (const char * path) inline
Remove a file from the volume working directory.
Parameters
[in] path A path with a valid 8.3 DOS name for the file.
Returns
The value true is returned for success and the value false is returned for failure.
Definition at line 239 of file FatFileSystem.h.
References FatFile::remove(), and vwd().
rename()
bool FatFileSystem::rename (const char * oldPath, const char * newPath) inline
Rename a file or subdirectory.
Parameters
[in] oldPath Path name to the file or subdirectory to be renamed.
[in] newPath New path name of the file or subdirectory.
The newPath object must not exist before the rename call.
The file to be renamed must not be open. The directory entry may be moved and file system corruption could occur if the file is accessed by a file object that was opened before the rename() call.
Returns
The value true is returned for success and the value false is returned for failure.
Definition at line 258 of file FatFileSystem.h.
References O_READ, FatFile::open(), FatFile::rename(), and vwd().
rmdir()
bool FatFileSystem::rmdir (const char * path) inline
Remove a subdirectory from the volume's working directory.
Parameters
[in] path A path with a valid 8.3 DOS name for the subdirectory.
The subdirectory file will be removed only if it is empty.
Returns
The value true is returned for success and the value false is returned for failure.
Definition at line 275 of file FatFileSystem.h.
References O_READ, FatFile::open(), FatFile::rmdir(), and vwd().
truncate()
bool FatFileSystem::truncate (const char * path, uint32_t length) inline
Truncate a file to a specified length. The current file position will be maintained if it is less than or equal to length otherwise it will be set to end of file.
Parameters
[in] path A path with a valid 8.3 DOS name for the file.
[in] length The desired length for the file.
Returns
The value true is returned for success and the value false is returned for failure.
Definition at line 293 of file FatFileSystem.h.
References O_WRITE, FatFile::open(), FatFile::truncate(), and vwd().
vol()
FatVolume* FatFileSystem::vol () inline
Returns
a pointer to the FatVolume object.
Definition at line 301 of file FatFileSystem.h.
vwd()
FatFile* FatFileSystem::vwd () inline
Returns
a pointer to the volume working directory.
Definition at line 305 of file FatFileSystem.h.
Referenced by begin(), chdir(), chvol(), exists(), ls(), mkdir(), FatFile::open(), remove(), rename(), rmdir(), truncate(), and wipe().
wipe()
bool FatFileSystem::wipe (print_t * pr = 0) inline
Wipe all data from the volume. You must reinitialize the volume before accessing it again.
Parameters
[in] pr print stream for status dots.
Returns
true for success else false.
Definition at line 313 of file FatFileSystem.h.
References FatFile::close(), vwd(), and FatVolume::wipe().
The documentation for this class was generated from the following file:
External/SDFat/FatLib/FatFileSystem.h