uWindows: ConfigRam Class Reference
ConfigRam Class Reference
Public Member Functions
void read (byte *v)
Private Member Functions
void set_SDA (byte n)
void set_SCL (byte n)
int get_SDA (void)
void i2c_start (void)
void i2c_stop (void)
int i2c_rx1 ()
void i2c_tx1 (byte b)
int i2c_tx (byte x)
int i2c_rx (int nak)
Private Attributes
uint8_t gpio
uint8_t gpio_dir
uint8_t sda
Detailed Description
Definition at line 75 of file GD3.cpp.
Member Function Documentation
get_SDA()
int ConfigRam::get_SDA (void) inline private
Definition at line 91 of file GD3.cpp.
References GDTransport::__rd16(), and REG_GPIO.
Referenced by i2c_rx1().
i2c_rx()
int ConfigRam::i2c_rx (int nak) inline private
Definition at line 135 of file GD3.cpp.
References i2c_rx1(), and i2c_tx1().
Referenced by read().
i2c_rx1()
int ConfigRam::i2c_rx1 () inline private
Definition at line 112 of file GD3.cpp.
References get_SDA(), set_SCL(), and set_SDA().
Referenced by i2c_rx(), and i2c_tx().
i2c_start()
void ConfigRam::i2c_start (void) inline private
Definition at line 96 of file GD3.cpp.
References set_SCL(), and set_SDA().
Referenced by read().
i2c_stop()
void ConfigRam::i2c_stop (void) inline private
Definition at line 104 of file GD3.cpp.
References set_SCL(), and set_SDA().
Referenced by read().
i2c_tx()
int ConfigRam::i2c_tx (byte x) inline private
Definition at line 128 of file GD3.cpp.
References i2c_rx1(), and i2c_tx1().
Referenced by read().
i2c_tx1()
void ConfigRam::i2c_tx1 (byte b) inline private
Definition at line 121 of file GD3.cpp.
References set_SCL(), and set_SDA().
Referenced by i2c_rx(), and i2c_tx().
read()
void ConfigRam::read (byte * v) inline
Definition at line 145 of file GD3.cpp.
References GDTransport::__end(), GDTransport::__rd16(), i2c_rx(), i2c_start(), i2c_stop(), i2c_tx(), REG_GPIO, REG_GPIO_DIR, and GDTransport::resume().
Referenced by GDClass::begin().
set_SCL()
void ConfigRam::set_SCL (byte n) inline private
Definition at line 86 of file GD3.cpp.
References GDTransport::__wr16(), and REG_GPIO.
Referenced by i2c_rx1(), i2c_start(), i2c_stop(), and i2c_tx1().
set_SDA()
void ConfigRam::set_SDA (byte n) inline private
Definition at line 78 of file GD3.cpp.
References GDTransport::__wr16(), and REG_GPIO_DIR.
Referenced by i2c_rx1(), i2c_start(), i2c_stop(), and i2c_tx1().
Member Data Documentation
gpio
uint8_t ConfigRam::gpio private
Definition at line 77 of file GD3.cpp.
gpio_dir
uint8_t ConfigRam::gpio_dir private
Definition at line 77 of file GD3.cpp.
sda
uint8_t ConfigRam::sda private
Definition at line 77 of file GD3.cpp.
The documentation for this class was generated from the following file:
External/GD3/GD3.cpp