uWindows: HomeScreen Class Reference
HomeScreen Class Reference
The home screen for the PiMower A screen is an element that contains the window and all the elements as children
#include <HomeScreen.h>
Public Member Functions
HomeScreen (DriverBase &tft)
~HomeScreen ()
void Update () override
sTouchResponse ProcessTouch (Point pt) override
Public Member Functions inherited from UIElement
UIElement (DriverBase &tft, Rectangle location, std::string elementName, eElementType elementType)
UIElement (const UIElement &other)
eElementType GetElementType ()
bool UpdatePending ()
int getElementID ()
bool isEnabled ()
void setEnabled (bool val)
void Invalidate ()
Rectangle GetLocation ()
Rectangle SetLocation (Rectangle newLoc)
std::vector< UIElement * > GetChildElements ()
virtual void AddChildElement (UIElement *element)
If a child UI element overrides this, it must call this as well
void SetParent (UIElement *element)
std::string getElementName ()
void UpdateChildren ()
~UIElement ()
Private Member Functions
void addButtons ()
Private Attributes
UIWindow * pageWindow
SettingsButton * settingsButton
Additional Inherited Members
Protected Attributes inherited from UIElement
std::string elementName
Rectangle location
UIElement * parentElement
bool updatePending
bool enabled
uint32_t elementID
DriverBase & tft
eElementType elementType
std::vector< UIElement * > childElements
Detailed Description
The home screen for the PiMower A screen is an element that contains the window and all the elements as children
See also
UIElement
Definition at line 12 of file HomeScreen.h.
Constructor & Destructor Documentation
HomeScreen()
HomeScreen::HomeScreen (DriverBase & tft)
Definition at line 3 of file HomeScreen.cpp.
References addButtons(), UIElement::AddChildElement(), UIElement::location, None, and pageWindow.
~HomeScreen()
HomeScreen::~HomeScreen ()
Definition at line 12 of file HomeScreen.cpp.
References pageWindow.
Member Function Documentation
addButtons()
void HomeScreen::addButtons () private
Definition at line 17 of file HomeScreen.cpp.
References UIElement::AddChildElement(), settingsButton, and UIElement::tft.
Referenced by HomeScreen().
ProcessTouch()
sTouchResponse HomeScreen::ProcessTouch (Point pt) override virtual
Implements UIElement.
Definition at line 29 of file HomeScreen.cpp.
Update()
void HomeScreen::Update () override virtual
Implements UIElement.
Definition at line 23 of file HomeScreen.cpp.
References UIElement::UpdateChildren().
Member Data Documentation
pageWindow
UIWindow* HomeScreen::pageWindow private
Definition at line 24 of file HomeScreen.h.
Referenced by HomeScreen(), and ~HomeScreen().
settingsButton
SettingsButton* HomeScreen::settingsButton private
Definition at line 25 of file HomeScreen.h.
Referenced by addButtons().
The documentation for this class was generated from the following files:
UIElements/UIPages/HomeScreen.h
UIElements/UIPages/HomeScreen.cpp