uWindows: Button Class Reference
Button Class Reference
#include <Button.h>
Static Public Member Functions
static Rectangle Draw (DriverBase &tft, bool sunken, uint16_t x, uint16_t y, uint16_t width, uint16_t height, int32_t textColor, uint32_t buttonColor, eUITextFont font, std::string text, bool is3D=true, uint8_t cornerRadius=4, uint8_t alpha=255, eVertAlign vertAlign=eVertAlign::Middle)
Detailed Description
Definition at line 14 of file Button.h.
Member Function Documentation
Draw()
Rectangle Button::Draw (DriverBase & tft, bool sunken, uint16_t x, uint16_t y, uint16_t width, uint16_t height, int32_t textColor, uint32_t buttonColor, eUITextFont font, std::string text, bool is3D = true, uint8_t cornerRadius = 4, uint8_t alpha = 255, eVertAlign vertAlign = eVertAlign::Middle) static
Definition at line 5 of file Button.cpp.
References Bottom, UIPrimitives::Center, UIPrimitives::FlatPanel(), FontHelper::GetTextRect(), Rectangle::height, UIPrimitives::RaisedPanel(), UIPrimitives::SunkenPanel(), UIPrimitives::Text(), Top, Logger::Trace(), Rectangle::update(), Rectangle::x1, Rectangle::x2, Rectangle::y1, and Rectangle::y2.
Referenced by UIActiveButton::Update(), and UIButton::Update().
The documentation for this class was generated from the following files:
UIElements/ControlDisplay/Button.h
UIElements/ControlDisplay/Button.cpp