uWindows: Logger Class Reference
Logger Class Reference
#include <Logger.h>
Public Types
enum LogLevel { TRACE = 0, WARN = 1, CRITICAL =2, FATAL = 3 }
Static Public Member Functions
static void Trace (const char *fmt,...)
static void Warn (const char *fmt,...)
static void Crit (const char *fmt,...)
static void Fatal (const char *fmt,...)
static void initLogger (LogLevel minimumLevel)
static void initLogger (LogLevel minimumLevel, long baudRate)
static std::string BoolToStr (bool val)
Static Private Member Functions
static std::string buildString (LogLevel level, const char *fmt,...)
Static Private Attributes
static LogLevel minLevel
static HardwareSerial * serial
Detailed Description
Definition at line 12 of file Logger.h.
Member Enumeration Documentation
LogLevel
enum Logger::LogLevel
Enumerator
TRACE
WARN
CRITICAL
FATAL
Definition at line 15 of file Logger.h.
Member Function Documentation
BoolToStr()
static std::string Logger::BoolToStr (bool val) inline static
Definition at line 31 of file Logger.h.
Referenced by NumericEntry::Draw(), ProgressBar::Draw(), UICheckBox::UICheckBox(), UIRadioButton::UIRadioButton(), and UIWindow::UIWindow().
buildString()
static std::string Logger::buildString (LogLevel level, const char * fmt, ...) static private
Crit()
void Logger::Crit (const char * fmt, ...) static
Definition at line 55 of file Logger.cpp.
References minLevel, and serial.
Referenced by WindowManager::DeleteElement(), and WindowManager::updateOccluded().
Fatal()
void Logger::Fatal (const char * fmt, ...) static
Definition at line 74 of file Logger.cpp.
References serial.
initLogger() [1/2]
void Logger::initLogger (LogLevel minimumLevel) static
Definition at line 5 of file Logger.cpp.
References minLevel.
initLogger() [2/2]
void Logger::initLogger (LogLevel minimumLevel, long baudRate) static
Definition at line 10 of file Logger.cpp.
References minLevel, and serial.
Trace()
void Logger::Trace (const char * fmt, ...) static
Definition at line 17 of file Logger.cpp.
References minLevel, and serial.
Referenced by Compass::Draw(), ProgressBar::Draw(), IconButton::Draw(), NumericEntry::Draw(), Button::Draw(), Slider::Draw(), FT8XXDriver::FT8XXDriver(), Color::GetColor565(), UIWindow::ProcessTouch(), WindowManager::processTouch(), WindowManager::RegisterElement(), UIActiveButton::UIActiveButton(), UIButton::UIButton(), UICheckBox::UICheckBox(), UIRadioButton::UIRadioButton(), UIWindow::UIWindow(), UIRadioButton::Update(), UIActiveButton::Update(), UIWindow::Update(), UIButton::Update(), UICheckBox::Update(), UIElementGraph::Update(), and WindowManager::WindowManager().
Warn()
void Logger::Warn (const char * fmt, ...) static
Definition at line 36 of file Logger.cpp.
References minLevel, and serial.
Referenced by WindowManager::MoveControlToFront().
Member Data Documentation
minLevel
Logger::LogLevel Logger::minLevel static private
Definition at line 39 of file Logger.h.
Referenced by Crit(), initLogger(), Trace(), and Warn().
serial
HardwareSerial * Logger::serial static private
Definition at line 40 of file Logger.h.
Referenced by Crit(), Fatal(), initLogger(), Trace(), and Warn().
The documentation for this class was generated from the following files:
Utility/Logger.h
Utility/Logger.cpp