uWindows: Reader Class Reference
Reader Class Reference
#include <GD3.h>
Public Member Functions
int openfile (const char *filename)
void begin (dirent &de)
void rewind (void)
void nextcluster ()
void fetch512 (byte *dst)
void nextcluster2 (byte *dst)
void skipcluster ()
void skipsector ()
void seek (uint32_t o)
void readsector (byte *dst)
int eof (void)
Public Attributes
uint32_t cluster
uint32_t cluster0
uint32_t offset
uint32_t size
byte sector
byte nseq
Detailed Description
Definition at line 643 of file GD3.h.
Member Function Documentation
begin()
void Reader::begin (dirent & de) inline
Definition at line 663 of file GD3.h.
References dirent::cluster, dirent::cluster_hi, FAT32, GDClass::SD, dirent::size, and sdcard::type.
eof()
int Reader::eof (void) inline
Definition at line 792 of file GD3.h.
fetch512()
void Reader::fetch512 (byte * dst) inline
Definition at line 689 of file GD3.h.
References sdcard::desel(), and GDClass::SD.
nextcluster()
void Reader::nextcluster () inline
Definition at line 678 of file GD3.h.
References FAT16, sdcard::o_fat, sdcard::rd2(), sdcard::rd4(), GDClass::SD, and sdcard::type.
nextcluster2()
void Reader::nextcluster2 (byte * dst) inline
Definition at line 719 of file GD3.h.
References sdcard::cmd17(), sdcard::o_fat, and GDClass::SD.
openfile()
int Reader::openfile (const char * filename) inline
Definition at line 645 of file GD3.h.
References dos83(), dirent::name, sdcard::o_root, sdcard::rdn(), and GDClass::SD.
readsector()
void Reader::readsector (byte * dst) inline
Definition at line 780 of file GD3.h.
References sdcard::cluster_size, sdcard::cmd17(), sdcard::o_data, GDClass::SD, and sdcard::sectors_per_cluster.
rewind()
void Reader::rewind (void) inline
Definition at line 672 of file GD3.h.
seek()
void Reader::seek (uint32_t o) inline
Definition at line 752 of file GD3.h.
References sdcard::cluster_size, FAT16, sdcard::o_fat, sdcard::rdn(), GDClass::SD, sdcard::sectors_per_cluster, and sdcard::type.
skipcluster()
void Reader::skipcluster () inline
Definition at line 738 of file GD3.h.
References sdcard::cluster_size, and GDClass::SD.
skipsector()
void Reader::skipsector () inline
Definition at line 743 of file GD3.h.
References GDClass::SD, and sdcard::sectors_per_cluster.
Member Data Documentation
cluster
uint32_t Reader::cluster
Definition at line 796 of file GD3.h.
cluster0
uint32_t Reader::cluster0
Definition at line 796 of file GD3.h.
nseq
byte Reader::nseq
Definition at line 800 of file GD3.h.
offset
uint32_t Reader::offset
Definition at line 797 of file GD3.h.
sector
byte Reader::sector
Definition at line 799 of file GD3.h.
size
uint32_t Reader::size
Definition at line 798 of file GD3.h.
The documentation for this class was generated from the following file:
External/GD3/GD3.h