uWindows: UIRadioGroup Class Reference
UIRadioGroup Class Reference
UIRadioGroup is a container class, some differences from other UIElements
#include <UIRadioGroup.h>
Public Member Functions
UIRadioGroup (DriverBase &tft, std::string elementName)
void AddRadioButton (UIRadioButton *radioButton)
std::string GetSelectedButton ()
void SetSelectedButton (std::string buttonName)
void SetSelectedButton (uint8_t buttonIdx)
void Update () override
The standard update is fine for this, as the only displayable objects in this are children
sTouchResponse ProcessTouch (Point pt) override
Private Attributes
uint8_t selectedButton
uint8_t buttonCount
Private Attributes inherited from UIElement
std::string elementName
Rectangle location
UIElement * parentElement
bool updatePending
bool enabled
uint32_t elementID
DriverBase & tft
eElementType elementType
std::vector< UIElement * > childElements
Additional Inherited Members
Private Member Functions inherited from UIElement
UIElement (DriverBase &tft, Rectangle location, std::string elementName, eElementType elementType)
UIElement (const UIElement &other)
eElementType GetElementType ()
bool UpdatePending ()
int getElementID ()
bool isEnabled ()
void setEnabled (bool val)
void Invalidate ()
Rectangle GetLocation ()
Rectangle SetLocation (Rectangle newLoc)
std::vector< UIElement * > GetChildElements ()
virtual void AddChildElement (UIElement *element)
If a child UI element overrides this, it must call this as well
void SetParent (UIElement *element)
std::string getElementName ()
void UpdateChildren ()
~UIElement ()
Detailed Description
UIRadioGroup is a container class, some differences from other UIElements
Location is a total of the children (UIRadioButton)
The radio buttons value is retrieved from this element
See also
UIElement
Definition at line 18 of file UIRadioGroup.h.
Constructor & Destructor Documentation
UIRadioGroup()
UIRadioGroup::UIRadioGroup (DriverBase & tft, std::string elementName)
Definition at line 3 of file UIRadioGroup.cpp.
References buttonCount.
Member Function Documentation
AddRadioButton()
void UIRadioGroup::AddRadioButton (UIRadioButton * radioButton)
Definition at line 9 of file UIRadioGroup.cpp.
References Rectangle::add(), UIElement::AddChildElement(), buttonCount, UIElement::childElements, UIElement::GetElementType(), UIElement::GetLocation(), UIRadioButton::IsChecked(), UIElement::location, RadioButton, selectedButton, and UIRadioButton::SetChecked().
GetSelectedButton()
std::string UIRadioGroup::GetSelectedButton ()
Definition at line 35 of file UIRadioGroup.cpp.
References UIElement::childElements, UIElement::GetElementType(), and RadioButton.
ProcessTouch()
sTouchResponse UIRadioGroup::ProcessTouch (Point pt) override virtual
Implements UIElement.
Definition at line 110 of file UIRadioGroup.cpp.
References UIElement::childElements, Rectangle::contains(), ControlTouched, UIElement::getElementID(), UIElement::GetElementType(), UIElement::GetLocation(), RadioButton, and SetSelectedButton().
SetSelectedButton() [1/2]
void UIRadioGroup::SetSelectedButton (std::string buttonName)
Definition at line 49 of file UIRadioGroup.cpp.
References UIElement::childElements, UIElement::GetElementType(), and RadioButton.
Referenced by ProcessTouch().
SetSelectedButton() [2/2]
void UIRadioGroup::SetSelectedButton (uint8_t buttonIdx)
Definition at line 72 of file UIRadioGroup.cpp.
References UIElement::childElements, UIElement::GetElementType(), and RadioButton.
Update()
void UIRadioGroup::Update () override virtual
The standard update is fine for this, as the only displayable objects in this are children
Implements UIElement.
Definition at line 105 of file UIRadioGroup.cpp.
References UIElement::Update().
Member Data Documentation
buttonCount
uint8_t UIRadioGroup::buttonCount private
Definition at line 36 of file UIRadioGroup.h.
Referenced by AddRadioButton(), and UIRadioGroup().
selectedButton
uint8_t UIRadioGroup::selectedButton private
Definition at line 35 of file UIRadioGroup.h.
Referenced by AddRadioButton().
The documentation for this class was generated from the following files:
UIElements/UIRadioGroup.h
UIElements/UIRadioGroup.cpp