uWindows: SdSpiCard Class Reference
SdSpiCard Class Reference
Raw access to SD and SDHC flash memory cards via SPI protocol.
#include <SdSpiCard.h>
Public Member Functions
SdSpiCard ()
bool begin (SdSpiDriver *spi, uint8_t csPin, SPISettings spiSettings)
uint32_t cardSize ()
bool erase (uint32_t firstBlock, uint32_t lastBlock)
bool eraseSingleBlockEnable ()
void error (uint8_t code)
int errorCode () const
int errorData () const
bool isBusy ()
bool readBlock (uint32_t lba, uint8_t *dst)
bool readBlocks (uint32_t lba, uint8_t *dst, size_t nb)
bool readCID (cid_t *cid)
bool readCSD (csd_t *csd)
bool readData (uint8_t *dst)
bool readOCR (uint32_t *ocr)
bool readStart (uint32_t blockNumber)
bool readStatus (uint8_t *status)
bool readStop ()
bool syncBlocks ()
int type () const
bool writeBlock (uint32_t lba, const uint8_t *src)
bool writeBlocks (uint32_t lba, const uint8_t *src, size_t nb)
bool writeData (const uint8_t *src)
bool writeStart (uint32_t blockNumber)
bool writeStart (uint32_t blockNumber, uint32_t eraseCount)
bool writeStop ()
void spiStart ()
void spiStop ()
Detailed Description
Raw access to SD and SDHC flash memory cards via SPI protocol.
Definition at line 37 of file SdSpiCard.h.
Constructor & Destructor Documentation
SdSpiCard()
SdSpiCard::SdSpiCard () inline
Construct an instance of SdSpiCard.
Definition at line 43 of file SdSpiCard.h.
References begin(), cardSize(), erase(), and eraseSingleBlockEnable().
Member Function Documentation
begin()
bool SdSpiCard::begin (SdSpiDriver * spi, uint8_t csPin, SPISettings spiSettings)
Initialize the SD card.
Parameters
[in] spi SPI driver for card.
[in] csPin card chip select pin.
[in] spiSettings SPI speed, mode, and bit order.
Returns
true for success else false.
Definition at line 117 of file SdSpiCard.cpp.
References ACMD41, SdSpiLibDriver::begin(), CMD0, CMD12, CMD58, CMD59, CMD8, curTimeMS(), error(), R1_IDLE_STATE, R1_ILLEGAL_COMMAND, R1_READY_STATE, SD_CARD_ERROR_ACMD41, SD_CARD_ERROR_CMD0, SD_CARD_ERROR_CMD58, SD_CARD_ERROR_CMD59, SD_CARD_ERROR_CMD8, SD_CARD_ERROR_NONE, SD_CARD_TYPE_SD1, SD_CARD_TYPE_SD2, SD_CARD_TYPE_SDHC, SD_INIT_TIMEOUT, SD_SCK_HZ, SD_WRITE_TIMEOUT, SdSpiLibDriver::setSpiSettings(), spiStart(), spiStop(), and type().
Referenced by SdSpiCardEX::begin(), Sd2Card::begin(), and SdSpiCard().
cardSize()
uint32_t SdSpiCard::cardSize ()
Determine the size of an SD flash memory card.
Returns
The number of 512 byte data blocks in the card or zero if an error occurs.
Definition at line 247 of file SdSpiCard.cpp.
References readCSD(), and sdCardCapacity().
Referenced by SdSpiCard().
erase()
bool SdSpiCard::erase (uint32_t firstBlock, uint32_t lastBlock)
Erase a range of blocks.
Parameters
[in] firstBlock The address of the first block in the range.
[in] lastBlock The address of the last block in the range.
Note
This function requests the SD card to do a flash erase for a range of blocks. The data on the card after an erase operation is either 0 or 1, depends on the card vendor. The card must support single block erase.
Returns
The value true is returned for success and the value false is returned for failure.
Definition at line 252 of file SdSpiCard.cpp.
References readCSD(), and csd_t::v1.
Referenced by SdSpiCard().
eraseSingleBlockEnable()
bool SdSpiCard::eraseSingleBlockEnable ()
Determine if card supports single block erase.
Returns
true is returned if single block erase is supported. false is returned if single block erase is not supported.
Definition at line 289 of file SdSpiCard.cpp.
References readCSD(), and csd_t::v1.
Referenced by SdSpiCard().
error()
void SdSpiCard::error (uint8_t code) inline
Set SD error code.
Parameters
[in] code value for error code.
Definition at line 82 of file SdSpiCard.h.
Referenced by begin(), readBlock(), readData(), readStart(), readStatus(), readStop(), writeBlock(), writeData(), writeStart(), and writeStop().
errorCode()
int SdSpiCard::errorCode () const inline
Returns
code for the last error. See SdInfo.h for a list of error codes.
Definition at line 88 of file SdSpiCard.h.
errorData()
int SdSpiCard::errorData () const inline
Returns
error data for last error.
Definition at line 92 of file SdSpiCard.h.
References isBusy(), readBlock(), and readBlocks().
isBusy()
bool SdSpiCard::isBusy ()
Check for busy. MISO low indicates the card is busy.
Returns
true if busy else false.
Definition at line 294 of file SdSpiCard.cpp.
References curTimeMS(), spiStart(), spiStop(), WDT_YIELD_TIME_MICROS, and SysCall::yield().
Referenced by errorData().
readBlock()
bool SdSpiCard::readBlock (uint32_t lba, uint8_t * dst) virtual
Read a 512 byte block from an SD card.
Parameters
[in] lba Logical block to be read.
[out] dst Pointer to the location that will receive the data.
Returns
The value true is returned for success and the value false is returned for failure.
Implements BaseBlockDriver.
Reimplemented in SdSpiCardEX.
Definition at line 323 of file SdSpiCard.cpp.
References CMD17, error(), readData(), SD_CARD_ERROR_CMD17, SD_CARD_TYPE_SDHC, SD_TRACE, spiStop(), and type().
Referenced by SdSpiCardEX::begin(), and errorData().
readBlocks()
bool SdSpiCard::readBlocks (uint32_t lba, uint8_t * dst, size_t nb) virtual
Read multiple 512 byte blocks from an SD card.
Parameters
[in] lba Logical block to be read.
[in] nb Number of blocks to be read.
[out] dst Pointer to the location that will receive the data.
Returns
The value true is returned for success and the value false is returned for failure.
Implements BaseBlockDriver.
Reimplemented in SdSpiCardEX.
Definition at line 344 of file SdSpiCard.cpp.
References readData(), readStart(), and readStop().
Referenced by SdSpiCardEX::begin(), and errorData().
readCID()
bool SdSpiCard::readCID (cid_t * cid) inline
Read a card's CID register. The CID contains card identification information such as Manufacturer ID, Product name, Product serial number and Manufacturing date.
Parameters
[out] cid pointer to area for returned data.
Returns
true for success or false for failure.
Definition at line 129 of file SdSpiCard.h.
References CMD10.
readCSD()
bool SdSpiCard::readCSD (csd_t * csd) inline
Read a card's CSD register. The CSD contains Card-Specific Data that provides information regarding access to the card's contents.
Parameters
[out] csd pointer to area for returned data.
Returns
true for success or false for failure.
Definition at line 140 of file SdSpiCard.h.
References CMD9, readData(), readOCR(), readStart(), readStatus(), and readStop().
Referenced by cardSize(), erase(), and eraseSingleBlockEnable().
readData()
bool SdSpiCard::readData (uint8_t * dst)
Read one data block in a multiple block read sequence
Parameters
[out] dst Pointer to the location for the data to be read.
Returns
The value true is returned for success and the value false is returned for failure.
Definition at line 356 of file SdSpiCard.cpp.
References crc, curTimeMS(), DATA_START_BLOCK, error(), SD_CARD_ERROR_DMA, SD_CARD_ERROR_READ, SD_CARD_ERROR_READ_TIMEOUT, SD_READ_TIMEOUT, and spiStop().
Referenced by readBlock(), SdSpiCardEX::readBlock(), readBlocks(), readCSD(), readStatus(), and type().
readOCR()
bool SdSpiCard::readOCR (uint32_t * ocr)
Read OCR register.
Parameters
[out] ocr Value of OCR register.
Returns
true for success else false.
Definition at line 401 of file SdSpiCard.cpp.
Referenced by readCSD().
readStart()
bool SdSpiCard::readStart (uint32_t blockNumber)
Start a read multiple blocks sequence.
Parameters
[in] blockNumber Address of first block in sequence.
Note
This function is used with readData() and readStop() for optimized multiple block reads. SPI chipSelect must be low for the entire sequence.
Returns
The value true is returned for success and the value false is returned for failure.
Definition at line 437 of file SdSpiCard.cpp.
References CMD18, error(), SD_CARD_ERROR_CMD18, SD_CARD_TYPE_SDHC, SD_TRACE, spiStop(), and type().
Referenced by SdSpiCardEX::readBlock(), readBlocks(), and readCSD().
readStatus()
bool SdSpiCard::readStatus (uint8_t * status)
Return the 64 byte card status
Parameters
[out] status location for 64 status bytes.
Returns
The value true is returned for success and the value false is returned for failure.
Definition at line 454 of file SdSpiCard.cpp.
References ACMD13, error(), readData(), SD_CARD_ERROR_ACMD13, and spiStop().
Referenced by readCSD().
readStop()
bool SdSpiCard::readStop ()
End a read multiple blocks sequence.
Returns
The value true is returned for success and the value false is returned for failure.
Definition at line 488 of file SdSpiCard.cpp.
References CMD12, curTimeMS(), error(), SD_CARD_ERROR_CMD12, and spiStop().
Referenced by readBlocks(), readCSD(), and SdSpiCardEX::syncBlocks().
spiStart()
void SdSpiCard::spiStart ()
Set CS low and activate the card.
Definition at line 471 of file SdSpiCard.cpp.
Referenced by begin(), isBusy(), and type().
spiStop()
void SdSpiCard::spiStop ()
Set CS high and deactivate the card.
Definition at line 479 of file SdSpiCard.cpp.
Referenced by begin(), isBusy(), readBlock(), readData(), readStart(), readStatus(), readStop(), type(), writeBlock(), writeBlocks(), writeData(), writeStart(), and writeStop().
syncBlocks()
bool SdSpiCard::syncBlocks () inline virtual
Returns
success if sync successful. Not for user apps.
Implements BaseBlockDriver.
Reimplemented in SdSpiCardEX.
Definition at line 181 of file SdSpiCard.h.
Referenced by SdSpiCardEX::begin().
type()
int SdSpiCard::type () const inline
Return the card type: SD V1, SD V2 or SDHC
Returns
0 - SD V1, 1 - SD V2, or 3 - SDHC.
Definition at line 185 of file SdSpiCard.h.
References SdSpiLibDriver::activate(), CMD55, SdSpiLibDriver::deactivate(), readData(), SdSpiLibDriver::receive(), SdSpiLibDriver::select(), SdSpiLibDriver::send(), spiStart(), spiStop(), SdSpiLibDriver::unselect(), writeBlock(), writeBlocks(), writeData(), writeStart(), and writeStop().
Referenced by begin(), readBlock(), readStart(), writeBlock(), and writeStart().
writeBlock()
bool SdSpiCard::writeBlock (uint32_t lba, const uint8_t * src) virtual
Writes a 512 byte block to an SD card.
Parameters
[in] lba Logical block to be written.
[in] src Pointer to the location of the data to be written.
Returns
The value true is returned for success and the value false is returned for failure.
Implements BaseBlockDriver.
Reimplemented in SdSpiCardEX.
Definition at line 523 of file SdSpiCard.cpp.
References CMD13, CMD24, DATA_START_BLOCK, error(), SD_CARD_ERROR_CMD13, SD_CARD_ERROR_CMD24, SD_CARD_ERROR_WRITE_TIMEOUT, SD_CARD_TYPE_SDHC, SD_TRACE, SD_WRITE_TIMEOUT, spiStop(), type(), and writeData().
Referenced by SdSpiCardEX::begin(), and type().
writeBlocks()
bool SdSpiCard::writeBlocks (uint32_t lba, const uint8_t * src, size_t nb) virtual
Write multiple 512 byte blocks to an SD card.
Parameters
[in] lba Logical block to be written.
[in] nb Number of blocks to be written.
[in] src Pointer to the location of the data to be written.
Returns
The value true is returned for success and the value false is returned for failure.
Implements BaseBlockDriver.
Reimplemented in SdSpiCardEX.
Definition at line 559 of file SdSpiCard.cpp.
References spiStop(), writeData(), writeStart(), and writeStop().
Referenced by SdSpiCardEX::begin(), and type().
writeData()
bool SdSpiCard::writeData (const uint8_t * src)
Write one data block in a multiple block write sequence.
Parameters
[in] src Pointer to the location of the data to be written.
Returns
The value true is returned for success and the value false is returned for failure.
Definition at line 575 of file SdSpiCard.cpp.
References crc, DATA_RES_ACCEPTED, DATA_RES_MASK, error(), SD_CARD_ERROR_WRITE, SD_CARD_ERROR_WRITE_TIMEOUT, SD_WRITE_TIMEOUT, spiStop(), and WRITE_MULTIPLE_TOKEN.
Referenced by type(), writeBlock(), SdSpiCardEX::writeBlock(), and writeBlocks().
writeStart() [1/2]
bool SdSpiCard::writeStart (uint32_t blockNumber)
Start a write multiple blocks sequence.
Parameters
[in] blockNumber Address of first block in sequence.
Note
This function is used with writeData() and writeStop() for optimized multiple block writes.
Returns
The value true is returned for success and the value false is returned for failure.
Definition at line 615 of file SdSpiCard.cpp.
References CMD25, error(), SD_CARD_ERROR_CMD25, SD_CARD_TYPE_SDHC, spiStop(), and type().
Referenced by type(), SdSpiCardEX::writeBlock(), and writeBlocks().
writeStart() [2/2]
bool SdSpiCard::writeStart (uint32_t blockNumber, uint32_t eraseCount)
Start a write multiple blocks sequence with pre-erase.
Parameters
[in] blockNumber Address of first block in sequence.
[in] eraseCount The number of blocks to be pre-erased.
Note
This function is used with writeData() and writeStop() for optimized multiple block writes.
Returns
The value true is returned for success and the value false is returned for failure.
Definition at line 631 of file SdSpiCard.cpp.
References ACMD23, CMD25, error(), SD_CARD_ERROR_ACMD23, SD_CARD_ERROR_CMD25, SD_CARD_TYPE_SDHC, SD_TRACE, spiStop(), and type().
writeStop()
bool SdSpiCard::writeStop ()
End a write multiple blocks sequence.
Returns
The value true is returned for success and the value false is returned for failure.
Definition at line 653 of file SdSpiCard.cpp.
References error(), SD_CARD_ERROR_STOP_TRAN, SD_WRITE_TIMEOUT, spiStop(), and STOP_TRAN_TOKEN.
Referenced by SdSpiCardEX::syncBlocks(), type(), and writeBlocks().
The documentation for this class was generated from the following files:
External/SDFat/SdCard/SdSpiCard.h
External/SDFat/SdCard/SdSpiCard.cpp