uWindows: UIWindow Class Reference
UIWindow Class Reference
#include <UIWindow.h>
Public Member Functions
UIWindow (DriverBase &tft, Rectangle location, eUITextFont titleBarFont, std::string titleText="", bool hasTitleBar=false, bool hasCloseIcon=false, bool hasChrome=false, bool isModal=false, bool is3D=true, tColor titleBarColor=Color::GetColor(Color::Blue), tColor titleTextColor=Color::GetColor(Color::White), tColor chromeColor=Color::GetColor(Color::White), tColor windowColor=Color::GetColor(Color::Black), uint8_t cornerRadius=5, std::string elementName="")
void Update () override
void SetWindowTitle (std::string title)
void SetTitleBar (bool titleBar)
void SetCloseIcon (bool closeIcon)
void SetHasChrome (bool hasChrome)
void SetModal (bool isModal)
void SetCornerRadius (uint8_t cornerRadius)
void AddChildElement (UIElement *element) override
Adds a child element to a window. For Windows it is special (Hence override), as the location is relative to the window size
sTouchResponse ProcessTouch (Point touchPoint) override
Public Member Functions inherited from UIElement
UIElement (DriverBase &tft, Rectangle location, std::string elementName, eElementType elementType)
UIElement (const UIElement &other)
eElementType GetElementType ()
bool UpdatePending ()
int getElementID ()
bool isEnabled ()
void setEnabled (bool val)
void Invalidate ()
Rectangle GetLocation ()
Rectangle SetLocation (Rectangle newLoc)
std::vector< UIElement * > GetChildElements ()
void SetParent (UIElement *element)
std::string getElementName ()
void UpdateChildren ()
~UIElement ()
Additional Inherited Members
Protected Attributes inherited from UIElement
std::string elementName
Rectangle location
UIElement * parentElement
bool updatePending
bool enabled
uint32_t elementID
DriverBase & tft
eElementType elementType
std::vector< UIElement * > childElements
Detailed Description
Definition at line 11 of file UIWindow.h.
Constructor & Destructor Documentation
UIWindow()
UIWindow::UIWindow (DriverBase & tft, Rectangle location, eUITextFont titleBarFont, std::string titleText = "", bool hasTitleBar = false, bool hasCloseIcon = false, bool hasChrome = false, bool isModal = false, bool is3D = true, tColor titleBarColor = Color::GetColor(Color::Blue), tColor titleTextColor = Color::GetColor(Color::White), tColor chromeColor = Color::GetColor(Color::White), tColor windowColor = Color::GetColor(Color::Black), uint8_t cornerRadius = 5, std::string elementName = "")
Definition at line 5 of file UIWindow.cpp.
References Logger::BoolToStr(), UIElement::location, UIElement::tft, Logger::Trace(), UIElement::UIElement(), Rectangle::x1, Rectangle::x2, Rectangle::y1, and Rectangle::y2.
Member Function Documentation
AddChildElement()
void UIWindow::AddChildElement (UIElement * element) override virtual
Adds a child element to a window. For Windows it is special (Hence override), as the location is relative to the window size
Parameters
element The element to be added
Reimplemented from UIElement.
Definition at line 200 of file UIWindow.cpp.
References UIElement::childElements, GFXfont::first, UIElement::GetLocation(), GFXfont::glyph, GFXglyph::height, DriverBase::height(), GFXfont::last, pgm_read_byte, pgm_read_pointer, UIElement::SetLocation(), UIElement::SetParent(), Rectangle::update(), GFXglyph::width, DriverBase::width(), Rectangle::x1, Rectangle::x2, GFXglyph::xAdvance, GFXglyph::xOffset, Rectangle::y1, Rectangle::y2, GFXfont::yAdvance, and GFXglyph::yOffset.
Referenced by WindowManager::RegisterElement(), and SetCornerRadius().
ProcessTouch()
sTouchResponse UIWindow::ProcessTouch (Point touchPoint) override virtual
Implements UIElement.
Definition at line 264 of file UIWindow.cpp.
References BringToFront, CloseControl, Rectangle::contains(), UIElement::elementID, NoOp, NULL, Logger::Trace(), Point::x, and Point::y.
Referenced by SetCornerRadius().
SetCloseIcon()
void UIWindow::SetCloseIcon (bool closeIcon)
Definition at line 83 of file UIWindow.cpp.
References UIElement::Invalidate().
SetCornerRadius()
void UIWindow::SetCornerRadius (uint8_t cornerRadius) inline
Definition at line 28 of file UIWindow.h.
References AddChildElement(), NULL, and ProcessTouch().
SetHasChrome()
void UIWindow::SetHasChrome (bool hasChrome)
Definition at line 89 of file UIWindow.cpp.
References UIElement::Invalidate().
SetModal()
void UIWindow::SetModal (bool isModal)
Definition at line 95 of file UIWindow.cpp.
References DriverBase::drawLine(), DriverBase::drawRect(), DriverBase::drawRoundRect(), DriverBase::fillRect(), DriverBase::fillRoundRect(), Rectangle::height, UIElement::Invalidate(), NULL, DriverBase::textWrite(), Logger::Trace(), Rectangle::update(), UIElement::updatePending, Rectangle::width, Rectangle::x1, Rectangle::x2, Rectangle::y1, and Rectangle::y2.
SetTitleBar()
void UIWindow::SetTitleBar (bool titleBar)
Definition at line 71 of file UIWindow.cpp.
References UIElement::Invalidate().
SetWindowTitle()
void UIWindow::SetWindowTitle (std::string title)
Definition at line 63 of file UIWindow.cpp.
References UIElement::Invalidate().
Update()
void UIWindow::Update () override virtual
Implements UIElement.
Definition at line 172 of file UIWindow.cpp.
References UIElement::childElements, Logger::Trace(), and UIElement::updatePending.
The documentation for this class was generated from the following files:
UIElements/UIWindow.h
UIElements/FT8XX/UIWindow.cpp