uWindows: CircularMinMaxBuffer Class Reference
CircularMinMaxBuffer Class Reference
Class to contain a circular buffer of a certain size When the buffer is full, the first half of the items will be deleted So we can always have preceding data
#include <CircularMinMaxBuffer.h>
Public Member Functions
CircularMinMaxBuffer (uint16_t maxSize)
~CircularMinMaxBuffer ()
float GetAvg ()
float GetMin ()
float GetMax ()
uint16_t GetCount ()
void PushItem (float value)
std::vector< float > GetValues ()
uint16_t GetSize ()
uint16_t GetChecksum ()
Detailed Description
Class to contain a circular buffer of a certain size When the buffer is full, the first half of the items will be deleted So we can always have preceding data
Definition at line 12 of file CircularMinMaxBuffer.h.
Constructor & Destructor Documentation
CircularMinMaxBuffer()
CircularMinMaxBuffer::CircularMinMaxBuffer (uint16_t maxSize)
Definition at line 3 of file CircularMinMaxBuffer.cpp.
~CircularMinMaxBuffer()
CircularMinMaxBuffer::~CircularMinMaxBuffer ()
Definition at line 9 of file CircularMinMaxBuffer.cpp.
Member Function Documentation
GetAvg()
float CircularMinMaxBuffer::GetAvg () inline
Definition at line 17 of file CircularMinMaxBuffer.h.
GetChecksum()
uint16_t CircularMinMaxBuffer::GetChecksum () inline
Definition at line 44 of file CircularMinMaxBuffer.h.
Referenced by UIElementGraph::Update().
GetCount()
uint16_t CircularMinMaxBuffer::GetCount () inline
Definition at line 29 of file CircularMinMaxBuffer.h.
References PushItem().
GetMax()
float CircularMinMaxBuffer::GetMax () inline
Definition at line 25 of file CircularMinMaxBuffer.h.
Referenced by UIElementGraph::Update().
GetMin()
float CircularMinMaxBuffer::GetMin () inline
Definition at line 21 of file CircularMinMaxBuffer.h.
Referenced by UIElementGraph::Update().
GetSize()
uint16_t CircularMinMaxBuffer::GetSize () inline
Definition at line 39 of file CircularMinMaxBuffer.h.
Referenced by UIElementGraph::Update().
GetValues()
std::vector<float> CircularMinMaxBuffer::GetValues () inline
Definition at line 35 of file CircularMinMaxBuffer.h.
Referenced by UIElementGraph::Update().
PushItem()
void CircularMinMaxBuffer::PushItem (float value)
Definition at line 14 of file CircularMinMaxBuffer.cpp.
Referenced by UIElementGraph::AddValue(), and GetCount().
The documentation for this class was generated from the following files:
Utility/CircularMinMaxBuffer.h
Utility/CircularMinMaxBuffer.cpp