uWindows: Adafruit_GFX Class Reference
Adafruit_GFX Class Reference abstract
#include <Adafruit_GFX.h>
Public Member Functions
Adafruit_GFX (int16_t w, int16_t h)
GFXfont * getFont ()
uint16_t getTextSize ()
virtual void drawPixel (int16_t x, int16_t y, uint16_t color)=0
virtual void startWrite (void)
virtual void writePixel (int16_t x, int16_t y, uint16_t color)
virtual void writeFillRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
virtual void writeFastVLine (int16_t x, int16_t y, int16_t h, uint16_t color)
virtual void writeFastHLine (int16_t x, int16_t y, int16_t w, uint16_t color)
virtual void writeLine (int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint16_t color)
virtual void endWrite (void)
virtual void setRotation (uint8_t r)
virtual void invertDisplay (boolean i)
virtual void drawFastVLine (int16_t x, int16_t y, int16_t h, uint16_t color)
virtual void drawFastHLine (int16_t x, int16_t y, int16_t w, uint16_t color)
virtual void fillRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
virtual void fillScreen (uint16_t color)
virtual void drawLine (int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint16_t color)
virtual void drawRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
void drawCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
void drawCircleHelper (int16_t x0, int16_t y0, int16_t r, uint8_t cornername, uint16_t color)
void fillCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
void fillCircleHelper (int16_t x0, int16_t y0, int16_t r, uint8_t cornername, int16_t delta, uint16_t color)
void drawTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color)
void fillTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color)
void drawRoundRect (int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint16_t color)
void fillRoundRect (int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint16_t color)
void drawBitmap (int16_t x, int16_t y, const uint8_t *bitmap, int16_t w, int16_t h, uint16_t color)
void drawBitmap (int16_t x, int16_t y, const uint8_t *bitmap, int16_t w, int16_t h, uint16_t color, uint16_t bg)
void drawBitmap (int16_t x, int16_t y, uint8_t *bitmap, int16_t w, int16_t h, uint16_t color)
void drawBitmap (int16_t x, int16_t y, uint8_t *bitmap, int16_t w, int16_t h, uint16_t color, uint16_t bg)
void drawXBitmap (int16_t x, int16_t y, const uint8_t *bitmap, int16_t w, int16_t h, uint16_t color)
void drawChar (int16_t x, int16_t y, unsigned char c, uint16_t color, uint16_t bg, uint8_t size)
void setCursor (int16_t x, int16_t y)
void setTextColor (uint16_t c)
void setTextColor (uint16_t c, uint16_t bg)
void setTextSize (uint8_t s)
void setTextWrap (boolean w)
void cp437 (boolean x=true)
void setFont (const GFXfont *f=NULL)
void getTextBounds (char *string, int16_t x, int16_t y, int16_t *x1, int16_t *y1, uint16_t *w, uint16_t *h)
void getTextBounds (const __FlashStringHelper *s, int16_t x, int16_t y, int16_t *x1, int16_t *y1, uint16_t *w, uint16_t *h)
virtual void write (uint8_t)
int16_t height (void) const
int16_t width (void) const
uint8_t getRotation (void) const
int16_t getCursorX (void) const
int16_t getCursorY (void) const
Protected Attributes
const int16_t WIDTH
const int16_t HEIGHT
int16_t _width
int16_t _height
int16_t cursor_x
int16_t cursor_y
uint16_t textcolor
uint16_t textbgcolor
uint8_t textsize
uint8_t rotation
boolean wrap
boolean _cp437
GFXfont * gfxFont
Detailed Description
Definition at line 12 of file Adafruit_GFX.h.
Constructor & Destructor Documentation
Adafruit_GFX()
Adafruit_GFX::Adafruit_GFX (int16_t w, int16_t h)
Definition at line 69 of file Adafruit_GFX.cpp.
References _cp437, _height, _width, cursor_x, cursor_y, gfxFont, HEIGHT, rotation, textbgcolor, textcolor, textsize, WIDTH, and wrap.
Member Function Documentation
cp437()
void Adafruit_GFX::cp437 (boolean x = true)
Definition at line 772 of file Adafruit_GFX.cpp.
References _cp437.
Referenced by getTextSize().
drawBitmap() [1/4]
void Adafruit_GFX::drawBitmap (int16_t x, int16_t y, const uint8_t * bitmap, int16_t w, int16_t h, uint16_t color)
Definition at line 471 of file Adafruit_GFX.cpp.
References endWrite(), pgm_read_byte, startWrite(), and writePixel().
Referenced by getTextSize().
drawBitmap() [2/4]
void Adafruit_GFX::drawBitmap (int16_t x, int16_t y, const uint8_t * bitmap, int16_t w, int16_t h, uint16_t color, uint16_t bg)
Definition at line 491 of file Adafruit_GFX.cpp.
References endWrite(), pgm_read_byte, startWrite(), and writePixel().
drawBitmap() [3/4]
void Adafruit_GFX::drawBitmap (int16_t x, int16_t y, uint8_t * bitmap, int16_t w, int16_t h, uint16_t color)
Definition at line 510 of file Adafruit_GFX.cpp.
References endWrite(), startWrite(), and writePixel().
drawBitmap() [4/4]
void Adafruit_GFX::drawBitmap (int16_t x, int16_t y, uint8_t * bitmap, int16_t w, int16_t h, uint16_t color, uint16_t bg)
Definition at line 528 of file Adafruit_GFX.cpp.
References endWrite(), startWrite(), and writePixel().
drawChar()
void Adafruit_GFX::drawChar (int16_t x, int16_t y, unsigned char c, uint16_t color, uint16_t bg, uint8_t size)
Definition at line 567 of file Adafruit_GFX.cpp.
References _cp437, _height, _width, GFXfont::bitmap, GFXglyph::bitmapOffset, endWrite(), GFXfont::first, gfxFont, GFXfont::glyph, GFXglyph::height, pgm_read_byte, pgm_read_pointer, pgm_read_word, startWrite(), GFXglyph::width, write(), writeFillRect(), writePixel(), GFXglyph::xOffset, and GFXglyph::yOffset.
Referenced by getTextSize(), and write().
drawCircle()
void Adafruit_GFX::drawCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
Definition at line 227 of file Adafruit_GFX.cpp.
References endWrite(), startWrite(), and writePixel().
Referenced by getTextSize().
drawCircleHelper()
void Adafruit_GFX::drawCircleHelper (int16_t x0, int16_t y0, int16_t r, uint8_t cornername, uint16_t color)
Definition at line 263 of file Adafruit_GFX.cpp.
References writePixel().
Referenced by drawRoundRect(), and getTextSize().
drawFastHLine()
void Adafruit_GFX::drawFastHLine (int16_t x, int16_t y, int16_t w, uint16_t color)
Definition at line 186 of file Adafruit_GFX.cpp.
References endWrite(), startWrite(), and writeLine().
Referenced by drawLine(), getTextSize(), and writeFastHLine().
drawFastVLine()
void Adafruit_GFX::drawFastVLine (int16_t x, int16_t y, int16_t h, uint16_t color) virtual
Reimplemented in Adafruit_RA8875.
Definition at line 176 of file Adafruit_GFX.cpp.
References endWrite(), startWrite(), and writeLine().
Referenced by drawLine(), getTextSize(), and writeFastVLine().
drawLine()
void Adafruit_GFX::drawLine (int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint16_t color)
Definition at line 209 of file Adafruit_GFX.cpp.
References _swap_int16_t, drawFastHLine(), drawFastVLine(), endWrite(), startWrite(), and writeLine().
Referenced by drawTriangle(), and getTextSize().
drawPixel()
virtual void Adafruit_GFX::drawPixel (int16_t x, int16_t y, uint16_t color) pure virtual
Implemented in GFXcanvas16, GFXcanvas1, and Adafruit_RA8875.
Referenced by getTextSize(), and writePixel().
drawRect()
void Adafruit_GFX::drawRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
Definition at line 339 of file Adafruit_GFX.cpp.
References endWrite(), startWrite(), writeFastHLine(), and writeFastVLine().
Referenced by getTextSize().
drawRoundRect()
void Adafruit_GFX::drawRoundRect (int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint16_t color)
Definition at line 350 of file Adafruit_GFX.cpp.
References drawCircleHelper(), endWrite(), startWrite(), writeFastHLine(), and writeFastVLine().
Referenced by getTextSize().
drawTriangle()
void Adafruit_GFX::drawTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color)
Definition at line 380 of file Adafruit_GFX.cpp.
References drawLine().
Referenced by getTextSize().
drawXBitmap()
void Adafruit_GFX::drawXBitmap (int16_t x, int16_t y, const uint8_t * bitmap, int16_t w, int16_t h, uint16_t color)
Definition at line 549 of file Adafruit_GFX.cpp.
References endWrite(), pgm_read_byte, startWrite(), and writePixel().
Referenced by getTextSize().
endWrite()
void Adafruit_GFX::endWrite (void) virtual
Definition at line 170 of file Adafruit_GFX.cpp.
Referenced by drawBitmap(), drawChar(), drawCircle(), drawFastHLine(), drawFastVLine(), drawLine(), drawRect(), drawRoundRect(), drawXBitmap(), fillCircle(), fillRect(), fillRoundRect(), fillTriangle(), and getTextSize().
fillCircle()
void Adafruit_GFX::fillCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
Definition at line 299 of file Adafruit_GFX.cpp.
References endWrite(), fillCircleHelper(), startWrite(), and writeFastVLine().
Referenced by getTextSize().
fillCircleHelper()
void Adafruit_GFX::fillCircleHelper (int16_t x0, int16_t y0, int16_t r, uint8_t cornername, int16_t delta, uint16_t color)
Definition at line 308 of file Adafruit_GFX.cpp.
References writeFastVLine().
Referenced by fillCircle(), fillRoundRect(), and getTextSize().
fillRect()
void Adafruit_GFX::fillRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
Definition at line 194 of file Adafruit_GFX.cpp.
References endWrite(), startWrite(), and writeFastVLine().
Referenced by fillScreen(), getTextSize(), and writeFillRect().
fillRoundRect()
void Adafruit_GFX::fillRoundRect (int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint16_t color)
Definition at line 367 of file Adafruit_GFX.cpp.
References endWrite(), fillCircleHelper(), startWrite(), and writeFillRect().
Referenced by getTextSize().
fillScreen()
void Adafruit_GFX::fillScreen (uint16_t color)
Definition at line 204 of file Adafruit_GFX.cpp.
References _height, _width, and fillRect().
Referenced by getTextSize().
fillTriangle()
void Adafruit_GFX::fillTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color)
Definition at line 388 of file Adafruit_GFX.cpp.
References _swap_int16_t, endWrite(), startWrite(), and writeFastHLine().
Referenced by getTextSize().
getCursorX()
int16_t Adafruit_GFX::getCursorX (void) const
Definition at line 718 of file Adafruit_GFX.cpp.
References cursor_x.
Referenced by getTextSize().
getCursorY()
int16_t Adafruit_GFX::getCursorY (void) const
Definition at line 722 of file Adafruit_GFX.cpp.
References cursor_y.
Referenced by getTextSize().
getFont()
GFXfont* Adafruit_GFX::getFont () inline
Definition at line 18 of file Adafruit_GFX.h.
References gfxFont.
getRotation()
uint8_t Adafruit_GFX::getRotation (void) const
Definition at line 745 of file Adafruit_GFX.cpp.
References rotation.
Referenced by getTextSize().
getTextBounds() [1/2]
void Adafruit_GFX::getTextBounds (char * string, int16_t x, int16_t y, int16_t * x1, int16_t * y1, uint16_t * w, uint16_t * h)
Definition at line 792 of file Adafruit_GFX.cpp.
References _height, _width, GFXfont::first, gfxFont, GFXfont::glyph, GFXglyph::height, GFXfont::last, pgm_read_byte, pgm_read_pointer, textsize, GFXglyph::width, wrap, GFXglyph::xAdvance, GFXglyph::xOffset, GFXfont::yAdvance, and GFXglyph::yOffset.
Referenced by getTextSize().
getTextBounds() [2/2]
void Adafruit_GFX::getTextBounds (const __FlashStringHelper * s, int16_t x, int16_t y, int16_t * x1, int16_t * y1, uint16_t * w, uint16_t * h)
Definition at line 882 of file Adafruit_GFX.cpp.
References _height, _width, GFXfont::first, gfxFont, GFXfont::glyph, GFXglyph::height, GFXfont::last, pgm_read_byte, pgm_read_pointer, textsize, GFXglyph::width, wrap, GFXglyph::xAdvance, GFXglyph::xOffset, GFXfont::yAdvance, and GFXglyph::yOffset.
getTextSize()
uint16_t Adafruit_GFX::getTextSize () inline
Definition at line 22 of file Adafruit_GFX.h.
References cp437(), drawBitmap(), drawChar(), drawCircle(), drawCircleHelper(), drawFastHLine(), drawFastVLine(), drawLine(), drawPixel(), drawRect(), drawRoundRect(), drawTriangle(), drawXBitmap(), endWrite(), fillCircle(), fillCircleHelper(), fillRect(), fillRoundRect(), fillScreen(), fillTriangle(), getCursorX(), getCursorY(), getRotation(), getTextBounds(), height(), invertDisplay(), setCursor(), setFont(), setRotation(), setTextColor(), setTextSize(), setTextWrap(), startWrite(), textsize, width(), write(), writeFastHLine(), writeFastVLine(), writeFillRect(), writeLine(), and writePixel().
height()
int16_t Adafruit_GFX::height (void) const
Definition at line 976 of file Adafruit_GFX.cpp.
References _height.
Referenced by getTextSize().
invertDisplay()
void Adafruit_GFX::invertDisplay (boolean i) virtual
Definition at line 980 of file Adafruit_GFX.cpp.
Referenced by getTextSize().
setCursor()
void Adafruit_GFX::setCursor (int16_t x, int16_t y)
Definition at line 713 of file Adafruit_GFX.cpp.
References cursor_x, and cursor_y.
Referenced by getTextSize().
setFont()
void Adafruit_GFX::setFont (const GFXfont * f = NULL)
Definition at line 776 of file Adafruit_GFX.cpp.
References cursor_y, and gfxFont.
Referenced by getTextSize().
setRotation()
void Adafruit_GFX::setRotation (uint8_t r) virtual
Definition at line 749 of file Adafruit_GFX.cpp.
References _height, _width, HEIGHT, rotation, and WIDTH.
Referenced by getTextSize().
setTextColor() [1/2]
void Adafruit_GFX::setTextColor (uint16_t c)
Definition at line 730 of file Adafruit_GFX.cpp.
References textbgcolor, and textcolor.
Referenced by getTextSize().
setTextColor() [2/2]
void Adafruit_GFX::setTextColor (uint16_t c, uint16_t bg)
Definition at line 736 of file Adafruit_GFX.cpp.
References textbgcolor, and textcolor.
setTextSize()
void Adafruit_GFX::setTextSize (uint8_t s)
Definition at line 726 of file Adafruit_GFX.cpp.
References textsize.
Referenced by getTextSize().
setTextWrap()
void Adafruit_GFX::setTextWrap (boolean w)
Definition at line 741 of file Adafruit_GFX.cpp.
References wrap.
Referenced by getTextSize().
startWrite()
void Adafruit_GFX::startWrite (void) virtual
Definition at line 135 of file Adafruit_GFX.cpp.
Referenced by drawBitmap(), drawChar(), drawCircle(), drawFastHLine(), drawFastVLine(), drawLine(), drawRect(), drawRoundRect(), drawXBitmap(), fillCircle(), fillRect(), fillRoundRect(), fillTriangle(), and getTextSize().
width()
int16_t Adafruit_GFX::width (void) const
Definition at line 972 of file Adafruit_GFX.cpp.
References _width.
Referenced by getTextSize().
write()
void Adafruit_GFX::write (uint8_t c) virtual
Definition at line 662 of file Adafruit_GFX.cpp.
References _width, cursor_x, cursor_y, drawChar(), GFXfont::first, gfxFont, GFXfont::glyph, GFXglyph::height, GFXfont::last, pgm_read_byte, pgm_read_pointer, textbgcolor, textcolor, textsize, GFXglyph::width, wrap, GFXglyph::xAdvance, GFXglyph::xOffset, and GFXfont::yAdvance.
Referenced by drawChar(), and getTextSize().
writeFastHLine()
void Adafruit_GFX::writeFastHLine (int16_t x, int16_t y, int16_t w, uint16_t color) virtual
Definition at line 156 of file Adafruit_GFX.cpp.
References drawFastHLine().
Referenced by drawRect(), drawRoundRect(), fillTriangle(), and getTextSize().
writeFastVLine()
void Adafruit_GFX::writeFastVLine (int16_t x, int16_t y, int16_t h, uint16_t color) virtual
Definition at line 146 of file Adafruit_GFX.cpp.
References drawFastVLine().
Referenced by drawRect(), drawRoundRect(), fillCircle(), fillCircleHelper(), fillRect(), and getTextSize().
writeFillRect()
void Adafruit_GFX::writeFillRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color) virtual
Definition at line 164 of file Adafruit_GFX.cpp.
References fillRect().
Referenced by drawChar(), fillRoundRect(), and getTextSize().
writeLine()
void Adafruit_GFX::writeLine (int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint16_t color) virtual
Definition at line 95 of file Adafruit_GFX.cpp.
References _swap_int16_t, and writePixel().
Referenced by drawFastHLine(), drawFastVLine(), drawLine(), and getTextSize().
writePixel()
void Adafruit_GFX::writePixel (int16_t x, int16_t y, uint16_t color) virtual
Definition at line 139 of file Adafruit_GFX.cpp.
References drawPixel().
Referenced by drawBitmap(), drawChar(), drawCircle(), drawCircleHelper(), drawXBitmap(), getTextSize(), and writeLine().
Member Data Documentation
_cp437
boolean Adafruit_GFX::_cp437 protected
Definition at line 128 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), cp437(), and drawChar().
_height
int16_t Adafruit_GFX::_height protected
Definition at line 120 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), drawChar(), GFXcanvas1::drawPixel(), GFXcanvas16::drawPixel(), fillScreen(), getTextBounds(), height(), GFXcanvas16::returnPixel(), and setRotation().
_width
int16_t Adafruit_GFX::_width protected
Definition at line 120 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), drawChar(), GFXcanvas1::drawPixel(), GFXcanvas16::drawPixel(), fillScreen(), getTextBounds(), GFXcanvas16::returnPixel(), setRotation(), width(), and write().
cursor_x
int16_t Adafruit_GFX::cursor_x protected
Definition at line 120 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), getCursorX(), setCursor(), and write().
cursor_y
int16_t Adafruit_GFX::cursor_y protected
Definition at line 120 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), getCursorY(), setCursor(), setFont(), and write().
gfxFont
GFXfont* Adafruit_GFX::gfxFont protected
Definition at line 131 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), drawChar(), getFont(), getTextBounds(), setFont(), and write().
HEIGHT
const int16_t Adafruit_GFX::HEIGHT protected
Definition at line 118 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), GFXcanvas1::drawPixel(), GFXcanvas16::drawPixel(), GFXcanvas1::fillScreen(), GFXcanvas16::fillScreen(), and setRotation().
rotation
uint8_t Adafruit_GFX::rotation protected
Definition at line 125 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), GFXcanvas1::drawPixel(), GFXcanvas16::drawPixel(), getRotation(), and setRotation().
textbgcolor
uint16_t Adafruit_GFX::textbgcolor protected
Definition at line 123 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), setTextColor(), and write().
textcolor
uint16_t Adafruit_GFX::textcolor protected
Definition at line 123 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), Adafruit_GFX_Button::initButtonUL(), setTextColor(), and write().
textsize
uint8_t Adafruit_GFX::textsize protected
Definition at line 125 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), getTextBounds(), getTextSize(), Adafruit_GFX_Button::initButtonUL(), setTextSize(), and write().
WIDTH
const int16_t Adafruit_GFX::WIDTH protected
Definition at line 118 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), GFXcanvas1::drawPixel(), GFXcanvas16::drawPixel(), GFXcanvas1::fillScreen(), GFXcanvas16::fillScreen(), GFXcanvas16::returnPixel(), and setRotation().
wrap
boolean Adafruit_GFX::wrap protected
Definition at line 128 of file Adafruit_GFX.h.
Referenced by Adafruit_GFX(), getTextBounds(), setTextWrap(), and write().
The documentation for this class was generated from the following files:
External/Adafruit_GFX_Library/Adafruit_GFX.h
External/Adafruit_GFX_Library/Adafruit_GFX.cpp