uWindows: UIPrimitives Class Reference
UIPrimitives Class Reference
#include <UIPrimitives.h>
Public Types
enum eTextHJustify { Left, Center, Right }
Static Public Member Functions
static Rectangle SunkenPanel (DriverBase &tft, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint8_t cornerRadius, uint32_t color, uint8_t alpha=255)
static Rectangle RaisedPanel (DriverBase &tft, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint8_t cornerRadius, uint32_t color, uint8_t alpha=255)
static Rectangle FlatPanel (DriverBase &tft, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint8_t cornerRadius, uint32_t color, uint8_t alpha=255)
static Rectangle CircleSunken (DriverBase &tft, uint32_t color, uint8_t alpha, uint16_t x, uint16_t y, uint16_t radius)
static Rectangle CircleRaised (DriverBase &tft, uint32_t color, uint8_t alpha, uint16_t x, uint16_t y, uint16_t radius)
static Rectangle CircleFlat (DriverBase &tft, uint32_t color, uint8_t alpha, uint16_t x, uint16_t y, uint16_t radius)
static Rectangle CircleOutline (DriverBase &tft, tColor color, uint16_t lineWidth, uint8_t alpha, uint16_t x, uint16_t y, uint16_t radius)
static Rectangle Text (DriverBase &tft, uint32_t color, uint8_t alpha, uint16_t x, uint16_t y, uint8_t font, bool dropShadow, std::string text, eTextHJustify justify=eTextHJustify::Center)
static Rectangle Polygon (DriverBase &tft, std::vector< Point > points, tColor color, uint8_t alpha)
static Rectangle DrawLine (DriverBase &tft, uint8_t lineWidth, Point pt1, Point pt2, tColor color, uint8_t alpha)
static Rectangle DrawPoint (DriverBase &tft, uint8_t pointSize, Point pt1, tColor color, uint8_t alpha)
Detailed Description
Definition at line 16 of file UIPrimitives.h.
Member Enumeration Documentation
eTextHJustify
enum UIPrimitives::eTextHJustify
Enumerator
Left
Center
Right
Definition at line 19 of file UIPrimitives.h.
Member Function Documentation
CircleFlat()
Rectangle UIPrimitives::CircleFlat (DriverBase & tft, uint32_t color, uint8_t alpha, uint16_t x, uint16_t y, uint16_t radius) static
Definition at line 110 of file UIPrimitives.cpp.
References GDClass::Begin(), GDClass::ColorA(), GDClass::ColorRGB(), GD, POINTS, GDClass::PointSize(), and GDClass::Vertex2f().
Referenced by Compass::Draw(), and RadioButton::Draw().
CircleOutline()
Rectangle UIPrimitives::CircleOutline (DriverBase & tft, tColor color, uint16_t lineWidth, uint8_t alpha, uint16_t x, uint16_t y, uint16_t radius) static
Definition at line 226 of file UIPrimitives.cpp.
References GDClass::Begin(), GDClass::BlendFunc(), circle(), GDClass::Clear(), GDClass::ColorMask(), GDClass::ColorRGB(), DST_ALPHA, GD, DriverBase::height(), ONE_MINUS_DST_ALPHA, RECTS, GDClass::RestoreContext(), GDClass::SaveContext(), GDClass::Vertex2f(), and DriverBase::width().
CircleRaised()
Rectangle UIPrimitives::CircleRaised (DriverBase & tft, uint32_t color, uint8_t alpha, uint16_t x, uint16_t y, uint16_t radius) static
Definition at line 90 of file UIPrimitives.cpp.
References GDClass::Begin(), GDClass::ColorA(), GDClass::ColorRGB(), GD, POINTS, GDClass::PointSize(), GDClass::Vertex2f(), and GDClass::VertexFormat().
Referenced by RadioButton::Draw().
CircleSunken()
Rectangle UIPrimitives::CircleSunken (DriverBase & tft, uint32_t color, uint8_t alpha, uint16_t x, uint16_t y, uint16_t radius) static
Definition at line 70 of file UIPrimitives.cpp.
References GDClass::Begin(), GDClass::ColorA(), GDClass::ColorRGB(), GD, POINTS, GDClass::PointSize(), GDClass::Vertex2f(), and GDClass::VertexFormat().
Referenced by RadioButton::Draw().
DrawLine()
Rectangle UIPrimitives::DrawLine (DriverBase & tft, uint8_t lineWidth, Point pt1, Point pt2, tColor color, uint8_t alpha) static
Definition at line 176 of file UIPrimitives.cpp.
References GDClass::Begin(), GDClass::BitmapHandle(), GDClass::Cell(), GDClass::ColorA(), GDClass::ColorRGB(), GD, LINES, GDClass::LineWidth(), GDClass::Vertex2f(), Point::x, Rectangle::x1, Rectangle::x2, Point::y, Rectangle::y1, and Rectangle::y2.
Referenced by UIElementGraph::Update().
DrawPoint()
Rectangle UIPrimitives::DrawPoint (DriverBase & tft, uint8_t pointSize, Point pt1, tColor color, uint8_t alpha) static
Definition at line 194 of file UIPrimitives.cpp.
References GDClass::Begin(), GDClass::BitmapHandle(), GDClass::Cell(), GDClass::ColorA(), GDClass::ColorRGB(), GD, POINTS, GDClass::PointSize(), GDClass::Vertex2f(), Point::x, Rectangle::x1, Rectangle::x2, Point::y, Rectangle::y1, and Rectangle::y2.
Referenced by UIElementGraph::Update().
FlatPanel()
Rectangle UIPrimitives::FlatPanel (DriverBase & tft, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint8_t cornerRadius, uint32_t color, uint8_t alpha = 255) static
Definition at line 59 of file UIPrimitives.cpp.
References DriverBase::colorA(), DriverBase::fillRect(), and DriverBase::fillRoundRect().
Referenced by CheckBox::Draw(), DropDownList::Draw(), ProgressBar::Draw(), IconButton::Draw(), NumericEntry::Draw(), Slider::Draw(), Button::Draw(), Window::Draw(), DropDownList::DrawExpanded(), NumericEntry::DrawKeys(), and NumericEntry::UpdateInput().
Polygon()
Rectangle UIPrimitives::Polygon (DriverBase & tft, std::vector< Point > points, tColor color, uint8_t alpha) static
Definition at line 153 of file UIPrimitives.cpp.
References Poly::begin(), GDClass::ColorA(), GDClass::ColorRGB(), Poly::draw(), GD, Poly::v(), Rectangle::x1, Rectangle::x2, Rectangle::y1, and Rectangle::y2.
Referenced by Compass::Draw().
RaisedPanel()
Rectangle UIPrimitives::RaisedPanel (DriverBase & tft, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint8_t cornerRadius, uint32_t color, uint8_t alpha = 255) static
Definition at line 34 of file UIPrimitives.cpp.
References GDClass::Begin(), GDClass::ColorA(), GDClass::ColorRGB(), GD, GDClass::LineWidth(), RECTS, GDClass::Vertex2f(), and GDClass::VertexFormat().
Referenced by CheckBox::Draw(), DropDownList::Draw(), IconButton::Draw(), Button::Draw(), Slider::Draw(), Window::Draw(), DropDownList::DrawExpanded(), NumericEntry::DrawKeys(), and UIElementGraph::Update().
SunkenPanel()
Rectangle UIPrimitives::SunkenPanel (DriverBase & tft, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint8_t cornerRadius, uint32_t color, uint8_t alpha = 255) static
Definition at line 4 of file UIPrimitives.cpp.
References GDClass::Begin(), GDClass::ColorA(), GDClass::ColorRGB(), GD, GDClass::LineWidth(), RECTS, GDClass::Vertex2f(), and GDClass::VertexFormat().
Referenced by CheckBox::Draw(), ProgressBar::Draw(), NumericEntry::Draw(), IconButton::Draw(), Button::Draw(), and NumericEntry::UpdateInput().
Text()
Rectangle UIPrimitives::Text (DriverBase & tft, uint32_t color, uint8_t alpha, uint16_t x, uint16_t y, uint8_t font, bool dropShadow, std::string text, eTextHJustify justify = eTextHJustify::Center) static
Definition at line 120 of file UIPrimitives.cpp.
References GDClass::cmd_text(), GDClass::ColorA(), GDClass::ColorRGB(), GD, FontHelper::GetTextRect(), OPT_CENTERX, OPT_RIGHTX, Rectangle::x2, and Rectangle::y2.
Referenced by CheckBox::Draw(), DropDownList::Draw(), RadioButton::Draw(), Compass::Draw(), ProgressBar::Draw(), IconButton::Draw(), Button::Draw(), Slider::Draw(), Window::Draw(), DropDownList::DrawExpanded(), NumericEntry::DrawKeys(), UIElementGraph::Update(), and NumericEntry::UpdateInput().
The documentation for this class was generated from the following files:
UIElements/FT8XX/UIPrimitives.h
UIElements/FT8XX/UIPrimitives.cpp