uWindows: WindowManager Class Reference
WindowManager Class Reference
This is the base class of the UI Library
#include <WindowManager.h>
Public Member Functions
sTouchResponse GetLastTouchEvent ()
void MoveControlToFront (unsigned long controlID)
void DeleteElement (unsigned long elementID)
void ClearElements ()
Deletes all elements from the window manager (Effective clear on next update)
void RegisterElement (UIElement *element)
void Update ()
void SetLowPowerTime (uint16_t secondsToLow)
void SetScreenOffTime (uint16_t secondsToOff)
FT8XXDriver * GetDriver ()
Static Public Member Functions
static WindowManager * instance ()
static WindowManager * instance (const uint8_t cs, const uint8_t rst=9, const uint8_t mosi=11, const uint8_t sclk=13, const uint8_t miso=12, eLCDSizes lcdSize=eLCDSizes::lcd800x480)
Private Member Functions
WindowManager (const uint8_t cs, const uint8_t rst=255, const uint8_t mosi=11, const uint8_t sclk=13, const uint8_t miso=12, eLCDSizes lcdSize=eLCDSizes::lcd800x480)
~WindowManager ()
void processTouch ()
void updatePowerTriggerTime ()
Updates when the power states will be triggered from this instant in time
void updateOccluded (unsigned long id)
Private Attributes
UIWindow * wmCanvas
FT8XXDriver * tft
std::map< unsigned long, UIElement * > elementMap
std::vector< unsigned long > elementOrder
ePowerState powerState = ePowerState::Normal
uint16_t lowPowerTime = 30
uint16_t screenOffTime = 300
uint32_t lowPowerTrigger
uint32_t screenOffTrigger
sTouchResponse lastTouchEvent
Static Private Attributes
static WindowManager * s_instance
Detailed Description
This is the base class of the UI Library
Definition at line 33 of file WindowManager.h.
Constructor & Destructor Documentation
WindowManager()
WindowManager::WindowManager (const uint8_t cs, const uint8_t rst = 255, const uint8_t mosi = 11, const uint8_t sclk = 13, const uint8_t miso = 12, eLCDSizes lcdSize = eLCDSizes::lcd800x480) private
Definition at line 5 of file WindowMananger.cpp.
References FT8XXDriver::backlightOn(), FT8XXDriver::backlightPower(), UIElement::getElementID(), DriverBase::height(), FT8XXDriver::Init(), lcd800x480, None, tft, Logger::Trace(), updatePowerTriggerTime(), DriverBase::width(), and wmCanvas.
Referenced by instance().
~WindowManager()
WindowManager::~WindowManager () private
Definition at line 223 of file WindowMananger.cpp.
References elementMap.
Member Function Documentation
ClearElements()
void WindowManager::ClearElements ()
Deletes all elements from the window manager (Effective clear on next update)
Definition at line 61 of file WindowMananger.cpp.
References DeleteElement(), UIElement::GetChildElements(), and wmCanvas.
Referenced by GetLastTouchEvent().
DeleteElement()
void WindowManager::DeleteElement (unsigned long elementID)
Definition at line 70 of file WindowMananger.cpp.
References Logger::Crit(), elementMap, elementOrder, UIElement::getElementID(), updateOccluded(), and wmCanvas.
Referenced by ClearElements(), and GetLastTouchEvent().
GetDriver()
FT8XXDriver* WindowManager::GetDriver () inline
Definition at line 83 of file WindowManager.h.
References tft.
Referenced by SetScreenOffTime().
GetLastTouchEvent()
sTouchResponse WindowManager::GetLastTouchEvent () inline
Definition at line 55 of file WindowManager.h.
References ClearElements(), DeleteElement(), lastTouchEvent, MoveControlToFront(), RegisterElement(), and Update().
instance() [1/2]
static WindowManager* WindowManager::instance () inline static
Definition at line 36 of file WindowManager.h.
References s_instance, and WindowManager().
instance() [2/2]
static WindowManager* WindowManager::instance (const uint8_t cs, const uint8_t rst = 9, const uint8_t mosi = 11, const uint8_t sclk = 13, const uint8_t miso = 12, eLCDSizes lcdSize = eLCDSizes::lcd800x480) inline static
Definition at line 45 of file WindowManager.h.
References s_instance, and WindowManager().
MoveControlToFront()
void WindowManager::MoveControlToFront (unsigned long controlID)
Definition at line 133 of file WindowMananger.cpp.
References elementOrder, updateOccluded(), and Logger::Warn().
Referenced by GetLastTouchEvent().
processTouch()
void WindowManager::processTouch () private
Definition at line 146 of file WindowMananger.cpp.
References FT8XXDriver::backlightOn(), FT8XXDriver::backlightPower(), ControlTouchedInactive, elementMap, elementOrder, UIElement::getElementID(), lastTouchEvent, LowPower, lowPowerTrigger, NoOp, Normal, powerState, ScreenOff, screenOffTrigger, tft, FT8XXDriver::touched(), FT8XXDriver::touchRead(), sTouchResponse::touchReponse, Logger::Trace(), updatePowerTriggerTime(), and wmCanvas.
Referenced by Update().
RegisterElement()
void WindowManager::RegisterElement (UIElement * element)
Definition at line 49 of file WindowMananger.cpp.
References UIWindow::AddChildElement(), elementMap, elementOrder, UIElement::getElementID(), UIElement::Invalidate(), Logger::Trace(), and wmCanvas.
Referenced by GetLastTouchEvent().
SetLowPowerTime()
void WindowManager::SetLowPowerTime (uint16_t secondsToLow) inline
Definition at line 66 of file WindowManager.h.
References lowPowerTime.
SetScreenOffTime()
void WindowManager::SetScreenOffTime (uint16_t secondsToOff) inline
Definition at line 70 of file WindowManager.h.
References GetDriver(), screenOffTime, and tft.
Update()
void WindowManager::Update ()
Definition at line 37 of file WindowMananger.cpp.
References FT8XXDriver::clearScreen(), elementMap, elementOrder, processTouch(), FT8XXDriver::swapDisplay(), and tft.
Referenced by GetLastTouchEvent(), and updateOccluded().
updateOccluded()
void WindowManager::updateOccluded (unsigned long id) private
Definition at line 107 of file WindowMananger.cpp.
References Logger::Crit(), elementMap, UIElement::GetChildElements(), Update(), and wmCanvas.
Referenced by DeleteElement(), and MoveControlToFront().
updatePowerTriggerTime()
void WindowManager::updatePowerTriggerTime () private
Updates when the power states will be triggered from this instant in time
Definition at line 217 of file WindowMananger.cpp.
References lowPowerTime, lowPowerTrigger, screenOffTime, and screenOffTrigger.
Referenced by processTouch(), and WindowManager().
Member Data Documentation
elementMap
std::map<unsigned long, UIElement *> WindowManager::elementMap private
Definition at line 109 of file WindowManager.h.
Referenced by DeleteElement(), processTouch(), RegisterElement(), Update(), updateOccluded(), and ~WindowManager().
elementOrder
std::vector<unsigned long> WindowManager::elementOrder private
Definition at line 110 of file WindowManager.h.
Referenced by DeleteElement(), MoveControlToFront(), processTouch(), RegisterElement(), and Update().
lastTouchEvent
sTouchResponse WindowManager::lastTouchEvent private
Definition at line 115 of file WindowManager.h.
Referenced by GetLastTouchEvent(), and processTouch().
lowPowerTime
uint16_t WindowManager::lowPowerTime = 30 private
Definition at line 112 of file WindowManager.h.
Referenced by SetLowPowerTime(), and updatePowerTriggerTime().
lowPowerTrigger
uint32_t WindowManager::lowPowerTrigger private
Definition at line 114 of file WindowManager.h.
Referenced by processTouch(), and updatePowerTriggerTime().
powerState
ePowerState WindowManager::powerState = ePowerState::Normal private
Definition at line 111 of file WindowManager.h.
Referenced by processTouch().
s_instance
WindowManager * WindowManager::s_instance static private
Definition at line 92 of file WindowManager.h.
Referenced by instance().
screenOffTime
uint16_t WindowManager::screenOffTime = 300 private
Definition at line 113 of file WindowManager.h.
Referenced by SetScreenOffTime(), and updatePowerTriggerTime().
screenOffTrigger
uint32_t WindowManager::screenOffTrigger private
Definition at line 114 of file WindowManager.h.
Referenced by processTouch(), and updatePowerTriggerTime().
tft
FT8XXDriver* WindowManager::tft private
Definition at line 104 of file WindowManager.h.
Referenced by GetDriver(), processTouch(), SetScreenOffTime(), Update(), and WindowManager().
wmCanvas
UIWindow* WindowManager::wmCanvas private
Definition at line 91 of file WindowManager.h.
Referenced by ClearElements(), DeleteElement(), processTouch(), RegisterElement(), updateOccluded(), and WindowManager().
The documentation for this class was generated from the following files:
WindowManager/WindowManager.h
WindowManager/WindowMananger.cpp