uWindows: ScreenSaver Class Reference
ScreenSaver Class Reference
#include <ScreenSaver.h>
Public Member Functions
ScreenSaver (DriverBase &tft)
void Update () override
sTouchResponse ProcessTouch (Point touchPoint) override
Public Member Functions inherited from UIElement
UIElement (DriverBase &tft, Rectangle location, std::string elementName, eElementType elementType)
UIElement (const UIElement &other)
eElementType GetElementType ()
bool UpdatePending ()
int getElementID ()
bool isEnabled ()
void setEnabled (bool val)
void Invalidate ()
Rectangle GetLocation ()
Rectangle SetLocation (Rectangle newLoc)
std::vector< UIElement * > GetChildElements ()
virtual void AddChildElement (UIElement *element)
If a child UI element overrides this, it must call this as well
void SetParent (UIElement *element)
std::string getElementName ()
void UpdateChildren ()
~UIElement ()
Additional Inherited Members
Protected Attributes inherited from UIElement
std::string elementName
Rectangle location
UIElement * parentElement
bool updatePending
bool enabled
uint32_t elementID
DriverBase & tft
eElementType elementType
std::vector< UIElement * > childElements
Detailed Description
Definition at line 6 of file ScreenSaver.h.
Constructor & Destructor Documentation
ScreenSaver()
ScreenSaver::ScreenSaver (DriverBase & tft)
Definition at line 3 of file ScreenSaver.cpp.
References AntiAliasFont31, Color::Aqua, Color::Beige, Color::Blue, Color::BlueViolet, DriverBase::clearScreen(), GDClass::cmd_text(), GDClass::ColorA(), GDClass::ColorRGB(), Color::Crimson, GD, Color::Green, Color::GreenYellow, DriverBase::swapDisplay(), UIElement::tft, Color::White, and Color::Yellow.
Member Function Documentation
ProcessTouch()
sTouchResponse ScreenSaver::ProcessTouch (Point touchPoint) override virtual
Implements UIElement.
Definition at line 60 of file ScreenSaver.cpp.
References CloseControl, and UIElement::elementID.
Update()
void ScreenSaver::Update () override virtual
Implements UIElement.
Definition at line 54 of file ScreenSaver.cpp.
The documentation for this class was generated from the following files:
UIElements/UIPages/ScreenSaver.h
UIElements/UIPages/ScreenSaver.cpp