uWindows: NumericEntry Class Reference
NumericEntry Class Reference
#include <NumericEntryFT8XX.h>
Static Public Member Functions
static Rectangle Draw (DriverBase &tft, uint16_t x, uint16_t y, uint16_t controlColor, uint16_t controlBGColor, uint16_t textColor, eUITextFont font, std::string initialValue, bool is3D=true, uint8_t cornerRadius=4, uint8_t alpha=255, bool singleDecimal=true)
static void DrawKeys (DriverBase &tft, uint16_t x, uint16_t y, uint16_t controlColor, uint16_t textColor, eUITextFont font, bool is3D=true, bool periodActive=true, bool singleDecimal=true)
static void UpdateInput (DriverBase &tft, uint16_t x, uint16_t y, uint16_t controlBGColor, uint16_t textColor, eUITextFont font, std::string inputValue, bool is3D=true)
static std::string ProcessTouch (DriverBase &tft, std::string value, uint16_t x, uint16_t y, Point pt, bool &complete, bool singleDecimal)
Processes the touch point
Detailed Description
Definition at line 13 of file NumericEntryFT8XX.h.
Member Function Documentation
Draw()
Rectangle NumericEntry::Draw (DriverBase & tft, uint16_t x, uint16_t y, uint16_t controlColor, uint16_t controlBGColor, uint16_t textColor, eUITextFont font, std::string initialValue, bool is3D = true, uint8_t cornerRadius = 4, uint8_t alpha = 255, bool singleDecimal = true) static
Definition at line 7 of file NumericEntryFT8XX.cpp.
References Logger::BoolToStr(), DrawKeys(), UIPrimitives::FlatPanel(), DriverBase::isLandscape(), UIPrimitives::SunkenPanel(), Logger::Trace(), and UpdateInput().
DrawKeys()
void NumericEntry::DrawKeys (DriverBase & tft, uint16_t x, uint16_t y, uint16_t controlColor, uint16_t textColor, eUITextFont font, bool is3D = true, bool periodActive = true, bool singleDecimal = true) static
Definition at line 43 of file NumericEntryFT8XX.cpp.
References Rectangle::center(), UIPrimitives::FlatPanel(), FontHelper::GetTextRect(), Rectangle::height, UIPrimitives::RaisedPanel(), UIPrimitives::Text(), Point::x, and Point::y.
Referenced by Draw().
ProcessTouch()
std::string NumericEntry::ProcessTouch (DriverBase & tft, std::string value, uint16_t x, uint16_t y, Point pt, bool & complete, bool singleDecimal) static
Processes the touch point
Parameters
pt The pt.
Returns
value each time, complete=true if it is complete
Definition at line 215 of file NumericEntryFT8XX.cpp.
References Rectangle::contains(), DriverBase::isLandscape(), Point::x, and Point::y.
UpdateInput()
void NumericEntry::UpdateInput (DriverBase & tft, uint16_t x, uint16_t y, uint16_t controlBGColor, uint16_t textColor, eUITextFont font, std::string inputValue, bool is3D = true) static
Definition at line 162 of file NumericEntryFT8XX.cpp.
References UIPrimitives::FlatPanel(), FontHelper::GetTextRect(), Rectangle::height, DriverBase::isLandscape(), UIPrimitives::SunkenPanel(), UIPrimitives::Text(), and Rectangle::width.
Referenced by Draw().
The documentation for this class was generated from the following files:
UIElements/ControlDisplay/NumericEntryFT8XX.h
UIElements/ControlDisplay/NumericEntryFT8XX.cpp