uWindows: ios Class Reference
ios Class Reference
Error and state information for all streams.
#include <ios.h>
Public Member Functions
ios ()
operator const void * () const
bool operator! () const
iostate rdstate () const
bool good () const
bool eof () const
bool fail () const
bool bad () const
void clear (iostate state=goodbit)
void setstate (iostate state)
Public Member Functions inherited from ios_base
ios_base ()
char fill ()
char fill (char c)
fmtflags flags () const
fmtflags flags (fmtflags fl)
int precision () const
int precision (unsigned int n)
fmtflags setf (fmtflags fl)
fmtflags setf (fmtflags fl, fmtflags mask)
void unsetf (fmtflags fl)
unsigned width ()
unsigned width (unsigned n)
Additional Inherited Members
Public Types inherited from ios_base
enum seekdir { beg, cur, end }
typedef unsigned char iostate
typedef uint32_t streamsize
typedef uint32_t pos_type
typedef int32_t off_type
typedef unsigned int fmtflags
typedef uint8_t openmode
Static Public Attributes inherited from ios_base
static const iostate goodbit = 0x00
static const iostate badbit = 0X01
static const iostate eofbit = 0x02
static const iostate failbit = 0X04
static const fmtflags left = 0x0001
static const fmtflags right = 0x0002
static const fmtflags internal = 0x0004
static const fmtflags dec = 0x0008
static const fmtflags hex = 0x0010
static const fmtflags oct = 0x0020
static const fmtflags boolalpha = 0x0100
static const fmtflags showbase = 0x0200
static const fmtflags showpoint = 0x0400
static const fmtflags showpos = 0x0800
static const fmtflags skipws = 0x1000
static const fmtflags uppercase = 0x4000
static const fmtflags adjustfield = left | right | internal
static const fmtflags basefield = dec | hex | oct
static const openmode app = 0X4
static const openmode ate = 0X8
static const openmode binary = 0X10
static const openmode in = 0X20
static const openmode out = 0X40
static const openmode trunc = 0X80
Protected Member Functions inherited from ios_base
uint8_t flagsToBase ()
Detailed Description
Error and state information for all streams.
Definition at line 361 of file ios.h.
Constructor & Destructor Documentation
ios()
ios::ios () inline
Create ios with no error flags set
Definition at line 364 of file ios.h.
Member Function Documentation
bad()
bool ios::bad () const inline
Returns
true if bad bit is set else false.
Definition at line 397 of file ios.h.
References ios_base::badbit.
Referenced by istream::peek().
clear()
void ios::clear (iostate state = goodbit) inline
Clear iostate bits.
Parameters
[in] state The flags you want to set after clearing all flags.
Definition at line 404 of file ios.h.
Referenced by fstream::clear(), ofstream::clear(), and ibufstream::init().
eof()
bool ios::eof () const inline
Returns
true if end of file has been reached else false.
Warning: An empty file returns false before the first read.
Moral: eof() is only useful in combination with fail(), to find out whether EOF was the cause for failure
Definition at line 389 of file ios.h.
References ios_base::eofbit.
fail()
bool ios::fail () const inline
Returns
true if any iostate bit other than eof are set else false.
Definition at line 393 of file ios.h.
References ios_base::badbit, and ios_base::failbit.
good()
bool ios::good () const inline
Returns
True if no iostate flags are set else false.
Definition at line 379 of file ios.h.
References ios_base::goodbit.
operator const void *()
ios::operator const void * () const inline
Returns
null pointer if fail() is true.
Definition at line 367 of file ios.h.
operator!()
bool ios::operator! () const inline
Returns
true if fail() else false.
Definition at line 371 of file ios.h.
rdstate()
iostate ios::rdstate () const inline
Returns
The iostate flags for this file.
Definition at line 375 of file ios.h.
setstate()
void ios::setstate (iostate state) inline
Set iostate bits.
Parameters
[in] state Bitts to set.
Definition at line 411 of file ios.h.
Referenced by ostream::flush(), istream::get(), istream::getline(), ibufstream::init(), obufstream::length(), istream::peek(), istream::seekg(), and ostream::seekp().
The documentation for this class was generated from the following file:
External/SDFat/FatLib/ios.h