uWindows: FontHelper Class Reference
FontHelper Class Reference
#include <FontHelper.h>
Static Public Member Functions
static Rectangle GetTextRect (DriverBase &lcd, std::string text, eUITextFont font, Point textLoc)
Detailed Description
Definition at line 27 of file FontHelper.h.
Member Function Documentation
GetTextRect()
Rectangle FontHelper::GetTextRect (DriverBase & lcd, std::string text, eUITextFont font, Point textLoc) static
Definition at line 604 of file FontHelper.cpp.
References AileronRegular12, AntiAliasFont26, AntiAliasFont27, AntiAliasFont28, AntiAliasFont29, AntiAliasFont30, AntiAliasFont31, AntiAliasFont32, AntiAliasFont33, AntiAliasFont34, BitmapFont16, BitmapFont17, BitmapFont18, BitmapFont19, BitmapFont20, BitmapFont21, BitmapFont22, BitmapFont23, BitmapFont24, BitmapFont25, Point::x, and Point::y.
Referenced by CheckBox::Draw(), RadioButton::Draw(), Compass::Draw(), IconButton::Draw(), Slider::Draw(), Button::Draw(), Window::Draw(), NumericEntry::DrawKeys(), DropDownList::ProcessTouch(), UIPrimitives::Text(), UIElementGraph::Update(), and NumericEntry::UpdateInput().
The documentation for this class was generated from the following files:
Utility/FontHelper.h
Utility/FontHelper.cpp