uWindows: SdSpiCardEX Class Reference
SdSpiCardEX Class Reference
Extended SD I/O block driver.
#include <SdSpiCard.h>
Public Member Functions
bool begin (SdSpiDriver *spi, uint8_t csPin, SPISettings spiSettings)
bool readBlock (uint32_t block, uint8_t *dst)
bool syncBlocks ()
bool writeBlock (uint32_t block, const uint8_t *src)
bool readBlocks (uint32_t block, uint8_t *dst, size_t nb)
bool writeBlocks (uint32_t block, const uint8_t *src, size_t nb)
Public Member Functions inherited from SdSpiCard
SdSpiCard ()
bool begin (SdSpiDriver *spi, uint8_t csPin, SPISettings spiSettings)
uint32_t cardSize ()
bool erase (uint32_t firstBlock, uint32_t lastBlock)
bool eraseSingleBlockEnable ()
void error (uint8_t code)
int errorCode () const
int errorData () const
bool isBusy ()
bool readCID (cid_t *cid)
bool readCSD (csd_t *csd)
bool readData (uint8_t *dst)
bool readOCR (uint32_t *ocr)
bool readStart (uint32_t blockNumber)
bool readStatus (uint8_t *status)
bool readStop ()
int type () const
bool writeData (const uint8_t *src)
bool writeStart (uint32_t blockNumber)
bool writeStart (uint32_t blockNumber, uint32_t eraseCount)
bool writeStop ()
void spiStart ()
void spiStop ()
Detailed Description
Extended SD I/O block driver.
Definition at line 303 of file SdSpiCard.h.
Member Function Documentation
begin()
bool SdSpiCardEX::begin (SdSpiDriver * spi, uint8_t csPin, SPISettings spiSettings) inline
Initialize the SD card
Parameters
[in] spi SPI driver.
[in] csPin Card chip select pin number.
[in] spiSettings SPI speed, mode, and bit order.
Returns
The value true is returned for success and the value false is returned for failure.
Definition at line 313 of file SdSpiCard.h.
References SdSpiCard::begin(), SdSpiCard::readBlock(), SdSpiCard::readBlocks(), SdSpiCard::syncBlocks(), SdSpiCard::writeBlock(), and SdSpiCard::writeBlocks().
readBlock()
bool SdSpiCardEX::readBlock (uint32_t block, uint8_t * dst) virtual
Read a 512 byte block from an SD card.
Parameters
[in] block Logical block to be read.
[out] dst Pointer to the location that will receive the data.
Returns
The value true is returned for success and the value false is returned for failure.
Reimplemented from SdSpiCard.
Definition at line 21 of file SdSpiCardEX.cpp.
References SdSpiCard::readData(), SdSpiCard::readStart(), and syncBlocks().
Referenced by readBlocks().
readBlocks()
bool SdSpiCardEX::readBlocks (uint32_t block, uint8_t * dst, size_t nb) virtual
Read multiple 512 byte blocks from an SD card.
Parameters
[in] block Logical block to be read.
[in] nb Number of blocks to be read.
[out] dst Pointer to the location that will receive the data.
Returns
The value true is returned for success and the value false is returned for failure.
Reimplemented from SdSpiCard.
Definition at line 39 of file SdSpiCardEX.cpp.
References readBlock().
syncBlocks()
bool SdSpiCardEX::syncBlocks () virtual
End multi-block transfer and go to idle state.
Returns
The value true is returned for success and the value false is returned for failure.
Reimplemented from SdSpiCard.
Definition at line 48 of file SdSpiCardEX.cpp.
References SdSpiCard::readStop(), and SdSpiCard::writeStop().
Referenced by SdFileSystem< SdSpiCardEX >::card(), readBlock(), and writeBlock().
writeBlock()
bool SdSpiCardEX::writeBlock (uint32_t block, const uint8_t * src) virtual
Writes a 512 byte block to an SD card.
Parameters
[in] block Logical block to be written.
[in] src Pointer to the location of the data to be written.
Returns
The value true is returned for success and the value false is returned for failure.
Reimplemented from SdSpiCard.
Definition at line 63 of file SdSpiCardEX.cpp.
References syncBlocks(), SdSpiCard::writeData(), and SdSpiCard::writeStart().
Referenced by writeBlocks().
writeBlocks()
bool SdSpiCardEX::writeBlocks (uint32_t block, const uint8_t * src, size_t nb) virtual
Write multiple 512 byte blocks to an SD card.
Parameters
[in] block Logical block to be written.
[in] nb Number of blocks to be written.
[in] src Pointer to the location of the data to be written.
Returns
The value true is returned for success and the value false is returned for failure.
Reimplemented from SdSpiCard.
Definition at line 81 of file SdSpiCardEX.cpp.
References writeBlock().
The documentation for this class was generated from the following files:
External/SDFat/SdCard/SdSpiCard.h
External/SDFat/SdCard/SdSpiCardEX.cpp