uWindows: DropDownList Class Reference
DropDownList Class Reference
#include <DropDownList.h>
Static Public Member Functions
static Rectangle Draw (DriverBase &tft, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint32_t textColor, uint32_t controlBGColor, uint32_t dropDownControlColor, uint8_t alpha, uint8_t cornerRadius, eUITextFont font, std::vector< std::string > items, uint8_t selectedIndex, bool is3D=true, bool dropDownPressed=false)
static Rectangle DrawExpanded (DriverBase &tft, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint32_t textColor, uint32_t controlBGColor, uint32_t dropDownControlColor, uint8_t alpha, uint8_t cornerRadius, eUITextFont font, std::vector< std::string > items, uint8_t selectedIndex, bool is3D=true)
static int16_t ProcessTouch (bool isExpanded, Point pt, DriverBase &tft, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint32_t textColor, uint32_t controlBGColor, uint32_t dropDownControlColor, uint8_t alpha, uint8_t cornerRadius, eUITextFont font, std::vector< std::string > items, uint8_t selectedIndex, bool is3D=true)
Static Private Member Functions
static Rectangle getMinSize (std::vector< std::string > items, uint16_t width, uint16_t height, DriverBase &tft, eUITextFont font)
static Rectangle getDropDownButton (Rectangle controlLocation)
Detailed Description
Definition at line 11 of file DropDownList.h.
Member Function Documentation
Draw()
Rectangle DropDownList::Draw (DriverBase & tft, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint32_t textColor, uint32_t controlBGColor, uint32_t dropDownControlColor, uint8_t alpha, uint8_t cornerRadius, eUITextFont font, std::vector< std::string > items, uint8_t selectedIndex, bool is3D = true, bool dropDownPressed = false) static
Definition at line 3 of file DropDownList.cpp.
References GDClass::Begin(), Rectangle::center(), GDClass::ColorRGB(), GDClass::End(), UIPrimitives::FlatPanel(), GD, getMinSize(), Rectangle::height, LINE_STRIP, UIPrimitives::RaisedPanel(), RECTS, UIPrimitives::Text(), GDClass::Vertex2ii(), Rectangle::width, Rectangle::x2, Point::y, Rectangle::y1, and Rectangle::y2.
Referenced by DrawExpanded().
DrawExpanded()
Rectangle DropDownList::DrawExpanded (DriverBase & tft, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint32_t textColor, uint32_t controlBGColor, uint32_t dropDownControlColor, uint8_t alpha, uint8_t cornerRadius, eUITextFont font, std::vector< std::string > items, uint8_t selectedIndex, bool is3D = true) static
Definition at line 62 of file DropDownList.cpp.
References Draw(), UIPrimitives::FlatPanel(), Rectangle::height, UIPrimitives::RaisedPanel(), UIPrimitives::Text(), Rectangle::update(), Rectangle::width, Rectangle::x1, Rectangle::y1, and Rectangle::y2.
getDropDownButton()
Rectangle DropDownList::getDropDownButton (Rectangle controlLocation) static private
Definition at line 136 of file DropDownList.cpp.
References Rectangle::height, Rectangle::x2, Rectangle::y1, and Rectangle::y2.
getMinSize()
Rectangle DropDownList::getMinSize (std::vector< std::string > items, uint16_t width, uint16_t height, DriverBase & tft, eUITextFont font) static private
Definition at line 120 of file DropDownList.cpp.
References FontHelper::GetTextRect(), Rectangle::height, and Rectangle::width.
Referenced by Draw().
ProcessTouch()
int16_t DropDownList::ProcessTouch (bool isExpanded, Point pt, DriverBase & tft, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint32_t textColor, uint32_t controlBGColor, uint32_t dropDownControlColor, uint8_t alpha, uint8_t cornerRadius, eUITextFont font, std::vector< std::string > items, uint8_t selectedIndex, bool is3D = true) static
Definition at line 112 of file DropDownList.cpp.
The documentation for this class was generated from the following files:
UIElements/ControlDisplay/DropDownList.h
UIElements/ControlDisplay/DropDownList.cpp