uWindows: ProgressBar Class Reference
ProgressBar Class Reference
#include <ProgressBar.h>
Static Public Member Functions
static Rectangle Draw (DriverBase &tft, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint8_t progress, int32_t textColor, uint32_t barBGColor, uint32_t barProgressColor, eUITextFont font, bool is3D=true, uint8_t cornerRadius=4, uint8_t alpha=255)
static Rectangle Draw (DriverBase &tft, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint8_t progress, uint32_t barBGColor, uint32_t barProgressColor, bool is3D=true, uint8_t cornerRadius=4, uint8_t alpha=255)
Detailed Description
Definition at line 12 of file ProgressBar.h.
Member Function Documentation
Draw() [1/2]
Rectangle ProgressBar::Draw (DriverBase & tft, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint8_t progress, int32_t textColor, uint32_t barBGColor, uint32_t barProgressColor, eUITextFont font, bool is3D = true, uint8_t cornerRadius = 4, uint8_t alpha = 255) static
Definition at line 3 of file ProgressBar.cpp.
References UIPrimitives::FlatPanel(), UIPrimitives::SunkenPanel(), UIPrimitives::Text(), and Logger::Trace().
Draw() [2/2]
Rectangle ProgressBar::Draw (DriverBase & tft, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint8_t progress, uint32_t barBGColor, uint32_t barProgressColor, bool is3D = true, uint8_t cornerRadius = 4, uint8_t alpha = 255) static
Definition at line 47 of file ProgressBar.cpp.
References Logger::BoolToStr(), UIPrimitives::FlatPanel(), UIPrimitives::SunkenPanel(), and Logger::Trace().
The documentation for this class was generated from the following files:
UIElements/ControlDisplay/ProgressBar.h
UIElements/ControlDisplay/ProgressBar.cpp