uWindows: SdioCardEX Class Reference
SdioCardEX Class Reference
Extended SD I/O block driver.
#include <SdioCard.h>
Public Member Functions
bool begin ()
bool erase (uint32_t firstBlock, uint32_t lastBlock)
bool readBlock (uint32_t block, uint8_t *dst)
bool syncBlocks ()
bool writeBlock (uint32_t block, const uint8_t *src)
bool readBlocks (uint32_t block, uint8_t *dst, size_t nb)
bool writeBlocks (uint32_t block, const uint8_t *src, size_t nb)
Public Member Functions inherited from SdioCard
bool begin ()
uint32_t cardSize ()
bool erase (uint32_t firstBlock, uint32_t lastBlock)
uint8_t errorCode ()
uint32_t errorData ()
uint32_t errorLine ()
bool isBusy ()
uint32_t kHzSdClk ()
bool readCID (void *cid)
bool readCSD (void *csd)
bool readData (uint8_t *dst)
bool readOCR (uint32_t *ocr)
bool readStart (uint32_t lba)
bool readStart (uint32_t lba, uint32_t count)
bool readStop ()
uint8_t type ()
bool writeData (const uint8_t *src)
bool writeStart (uint32_t lba)
bool writeStart (uint32_t lba, uint32_t count)
bool writeStop ()
Detailed Description
Extended SD I/O block driver.
Definition at line 217 of file SdioCard.h.
Member Function Documentation
begin()
bool SdioCardEX::begin (void) inline
Initialize the SD card
Returns
The value true is returned for success and the value false is returned for failure.
Definition at line 224 of file SdioCard.h.
References SdioCard::begin().
Referenced by SdFat::fsBegin().
erase()
bool SdioCardEX::erase (uint32_t firstBlock, uint32_t lastBlock) inline
Erase a range of blocks.
Parameters
[in] firstBlock The address of the first block in the range.
[in] lastBlock The address of the last block in the range.
Note
This function requests the SD card to do a flash erase for a range of blocks. The data on the card after an erase operation is either 0 or 1, depends on the card vendor. The card must support single block erase.
Returns
The value true is returned for success and the value false is returned for failure.
Definition at line 241 of file SdioCard.h.
References SdioCard::erase(), SdioCard::readBlock(), SdioCard::readBlocks(), SdioCard::syncBlocks(), SdioCard::writeBlock(), and SdioCard::writeBlocks().
readBlock()
bool SdioCardEX::readBlock (uint32_t block, uint8_t * dst) virtual
Read a 512 byte block from an SD card.
Parameters
[in] block Logical block to be read.
[out] dst Pointer to the location that will receive the data.
Returns
The value true is returned for success and the value false is returned for failure.
Reimplemented from SdioCard.
Definition at line 28 of file SdioCardEX.cpp.
References MAX_SDHC_COUNT, SdioCard::readData(), SdioCard::readStart(), RU_MASK, and syncBlocks().
Referenced by readBlocks().
readBlocks()
bool SdioCardEX::readBlocks (uint32_t block, uint8_t * dst, size_t nb) virtual
Read multiple 512 byte blocks from an SD card.
Parameters
[in] block Logical block to be read.
[in] nb Number of blocks to be read.
[out] dst Pointer to the location that will receive the data.
Returns
The value true is returned for success and the value false is returned for failure.
Reimplemented from SdioCard.
Definition at line 50 of file SdioCardEX.cpp.
References readBlock().
syncBlocks()
bool SdioCardEX::syncBlocks () virtual
End multi-block transfer and go to idle state.
Returns
The value true is returned for success and the value false is returned for failure.
Reimplemented from SdioCard.
Definition at line 59 of file SdioCardEX.cpp.
References SdioCard::readStop(), and SdioCard::writeStop().
Referenced by readBlock(), and writeBlock().
writeBlock()
bool SdioCardEX::writeBlock (uint32_t block, const uint8_t * src) virtual
Writes a 512 byte block to an SD card.
Parameters
[in] block Logical block to be written.
[in] src Pointer to the location of the data to be written.
Returns
The value true is returned for success and the value false is returned for failure.
Reimplemented from SdioCard.
Definition at line 74 of file SdioCardEX.cpp.
References MAX_SDHC_COUNT, RU_MASK, syncBlocks(), SdioCard::writeData(), and SdioCard::writeStart().
Referenced by writeBlocks().
writeBlocks()
bool SdioCardEX::writeBlocks (uint32_t block, const uint8_t * src, size_t nb) virtual
Write multiple 512 byte blocks to an SD card.
Parameters
[in] block Logical block to be written.
[in] nb Number of blocks to be written.
[in] src Pointer to the location of the data to be written.
Returns
The value true is returned for success and the value false is returned for failure.
Reimplemented from SdioCard.
Definition at line 96 of file SdioCardEX.cpp.
References writeBlock().
The documentation for this class was generated from the following files:
External/SDFat/SdCard/SdioCard.h
External/SDFat/SdCard/SdioCardEX.cpp