uWindows: CharWriter Class Reference
CharWriter Class Reference abstract
Character output - often serial port.
#include <FatVolume.h>
Public Member Functions
virtual size_t write (char c)=0
virtual size_t write (const char *s)=0
Detailed Description
Character output - often serial port.
Definition at line 54 of file FatVolume.h.
Member Function Documentation
write() [1/2]
virtual size_t CharWriter::write (char c) pure virtual
Referenced by FatFile::dmpFile(), FatFile::ls(), FatFile::printCreateDateTime(), FatFile::printFileSize(), FatFile::printModifyDateTime(), FatFile::printSFN(), and FatVolume::wipe().
write() [2/2]
virtual size_t CharWriter::write (const char * s) pure virtual
The documentation for this class was generated from the following file:
External/SDFat/FatLib/FatVolume.h