uWindows: Adafruit_RA8875 Class Reference
Adafruit_RA8875 Class Reference
#include <Adafruit_RA8875.h>
Public Member Functions
Adafruit_RA8875 (uint8_t cs, uint8_t rst)
boolean begin (enum RA8875sizes s)
void softReset (void)
void displayOn (boolean on)
void sleep (boolean sleep)
void textMode (void)
void textSetCursor (uint16_t x, uint16_t y)
void textColor (uint16_t foreColor, uint16_t bgColor)
void textTransparent (uint16_t foreColor)
void textEnlarge (uint8_t scale)
void textWrite (const char *buffer, uint16_t len=0)
void graphicsMode (void)
void setXY (uint16_t x, uint16_t y)
void pushPixels (uint32_t num, uint16_t p)
void fillRect (void)
uint16_t getPixel (uint16_t x, uint16_t y)
void drawPixel (int16_t x, int16_t y, uint16_t color)
void drawFastVLine (int16_t x, int16_t y, int16_t h, uint16_t color)
void drawFastHLine (int16_t x, int16_t y, int16_t w, uint16_t color)
void fillScreen (uint16_t color)
void drawLine (int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint16_t color)
void drawRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
void fillRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
void drawCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
void fillCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
void drawTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color)
void fillTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color)
void drawEllipse (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint16_t color)
void fillEllipse (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint16_t color)
void drawCurve (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint8_t curvePart, uint16_t color)
void fillCurve (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint8_t curvePart, uint16_t color)
void GPIOX (boolean on)
void PWM1config (boolean on, uint8_t clock)
void PWM2config (boolean on, uint8_t clock)
void PWM1out (uint8_t p)
void PWM2out (uint8_t p)
void touchEnable (boolean on)
boolean touched (void)
boolean touchRead (uint16_t *x, uint16_t *y)
void writeReg (uint8_t reg, uint8_t val)
uint8_t readReg (uint8_t reg)
void writeData (uint8_t d)
uint8_t readData (void)
void writeCommand (uint8_t d)
uint8_t readStatus (void)
boolean waitPoll (uint8_t r, uint8_t f)
uint16_t width (void)
uint16_t height (void)
Public Member Functions inherited from Adafruit_GFX
Adafruit_GFX (int16_t w, int16_t h)
GFXfont * getFont ()
uint16_t getTextSize ()
virtual void startWrite (void)
virtual void writePixel (int16_t x, int16_t y, uint16_t color)
virtual void writeFillRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
virtual void writeFastVLine (int16_t x, int16_t y, int16_t h, uint16_t color)
virtual void writeFastHLine (int16_t x, int16_t y, int16_t w, uint16_t color)
virtual void writeLine (int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint16_t color)
virtual void endWrite (void)
virtual void setRotation (uint8_t r)
virtual void invertDisplay (boolean i)
virtual void drawFastHLine (int16_t x, int16_t y, int16_t w, uint16_t color)
virtual void fillRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
virtual void fillScreen (uint16_t color)
virtual void drawLine (int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint16_t color)
virtual void drawRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
void drawCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
void drawCircleHelper (int16_t x0, int16_t y0, int16_t r, uint8_t cornername, uint16_t color)
void fillCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
void fillCircleHelper (int16_t x0, int16_t y0, int16_t r, uint8_t cornername, int16_t delta, uint16_t color)
void drawTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color)
void fillTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color)
void drawRoundRect (int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint16_t color)
void fillRoundRect (int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint16_t color)
void drawBitmap (int16_t x, int16_t y, const uint8_t *bitmap, int16_t w, int16_t h, uint16_t color)
void drawBitmap (int16_t x, int16_t y, const uint8_t *bitmap, int16_t w, int16_t h, uint16_t color, uint16_t bg)
void drawBitmap (int16_t x, int16_t y, uint8_t *bitmap, int16_t w, int16_t h, uint16_t color)
void drawBitmap (int16_t x, int16_t y, uint8_t *bitmap, int16_t w, int16_t h, uint16_t color, uint16_t bg)
void drawXBitmap (int16_t x, int16_t y, const uint8_t *bitmap, int16_t w, int16_t h, uint16_t color)
void drawChar (int16_t x, int16_t y, unsigned char c, uint16_t color, uint16_t bg, uint8_t size)
void setCursor (int16_t x, int16_t y)
void setTextColor (uint16_t c)
void setTextColor (uint16_t c, uint16_t bg)
void setTextSize (uint8_t s)
void setTextWrap (boolean w)
void cp437 (boolean x=true)
void setFont (const GFXfont *f=NULL)
void getTextBounds (char *string, int16_t x, int16_t y, int16_t *x1, int16_t *y1, uint16_t *w, uint16_t *h)
void getTextBounds (const __FlashStringHelper *s, int16_t x, int16_t y, int16_t *x1, int16_t *y1, uint16_t *w, uint16_t *h)
virtual void write (uint8_t)
int16_t height (void) const
int16_t width (void) const
uint8_t getRotation (void) const
int16_t getCursorX (void) const
int16_t getCursorY (void) const
Private Member Functions
void PLLinit (void)
void initialize (void)
void circleHelper (int16_t x0, int16_t y0, int16_t r, uint16_t color, bool filled)
void rectHelper (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color, bool filled)
void triangleHelper (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color, bool filled)
void ellipseHelper (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint16_t color, bool filled)
void curveHelper (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint8_t curvePart, uint16_t color, bool filled)
Private Attributes
uint8_t _cs
uint8_t _rst
uint16_t _width
uint16_t _height
uint8_t _textScale
enum RA8875sizes _size
Additional Inherited Members
Protected Attributes inherited from Adafruit_GFX
const int16_t WIDTH
const int16_t HEIGHT
int16_t _width
int16_t _height
int16_t cursor_x
int16_t cursor_y
uint16_t textcolor
uint16_t textbgcolor
uint8_t textsize
uint8_t rotation
boolean wrap
boolean _cp437
GFXfont * gfxFont
Detailed Description
Definition at line 59 of file Adafruit_RA8875.h.
Constructor & Destructor Documentation
Adafruit_RA8875()
Adafruit_RA8875::Adafruit_RA8875 (uint8_t CS, uint8_t RST)
Constructor for a new RA8875 instance
CS[in] Location of the SPI chip select pin RST[in] Location of the reset pin
Definition at line 63 of file Adafruit_RA8875.cpp.
References _cs, _rst, and CS.
Member Function Documentation
begin()
boolean Adafruit_RA8875::begin (enum RA8875sizes s)
Initialises the LCD driver and any HW required by the display
s[in] The display size, which can be either: 'RA8875_480x272' (4.3" displays) r 'RA8875_800x480' (5" and 7" displays)
Definition at line 77 of file Adafruit_RA8875.cpp.
References _cs, _height, _rst, _size, _width, initialize(), RA8875_480x272, RA8875_800x480, readReg(), and spi_speed.
circleHelper()
void Adafruit_RA8875::circleHelper (int16_t x0, int16_t y0, int16_t r, uint16_t color, bool filled) private
Helper function for higher level circle drawing code
Definition at line 793 of file Adafruit_RA8875.cpp.
References RA8875_DCR, RA8875_DCR_CIRCLE_START, RA8875_DCR_CIRCLE_STATUS, RA8875_DCR_FILL, RA8875_DCR_NOFILL, waitPoll(), writeCommand(), and writeData().
Referenced by drawCircle(), and fillCircle().
curveHelper()
void Adafruit_RA8875::curveHelper (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint8_t curvePart, uint16_t color, bool filled) private
Helper function for higher level curve drawing code
Definition at line 1003 of file Adafruit_RA8875.cpp.
References RA8875_ELLIPSE, RA8875_ELLIPSE_STATUS, waitPoll(), writeCommand(), and writeData().
Referenced by drawCurve(), and fillCurve().
displayOn()
void Adafruit_RA8875::displayOn (boolean on)
Turns the display on or off
Definition at line 1193 of file Adafruit_RA8875.cpp.
References RA8875_PWRR, RA8875_PWRR_DISPOFF, RA8875_PWRR_DISPON, RA8875_PWRR_NORMAL, and writeReg().
drawCircle()
void Adafruit_RA8875::drawCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
Draws a HW accelerated circle on the display
x[in] The 0-based x location of the center of the circle y[in] The 0-based y location of the center of the circle w[in] The circle's radius color[in] The RGB565 color to use when drawing the pixel
Definition at line 658 of file Adafruit_RA8875.cpp.
References circleHelper().
drawCurve()
void Adafruit_RA8875::drawCurve (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint8_t curvePart, uint16_t color)
Draws a HW accelerated curve on the display
xCenter[in] The 0-based x location of the ellipse's center yCenter[in] The 0-based y location of the ellipse's center longAxis[in] The size in pixels of the ellipse's long axis shortAxis[in] The size in pixels of the ellipse's short axis curvePart[in] The corner to draw, where in clock-wise motion: 0 = 180-270 1 = 270-0 2 = 0-90 3 = 90-180 color[in] The RGB565 color to use when drawing the pixel
Definition at line 762 of file Adafruit_RA8875.cpp.
References curveHelper().
drawEllipse()
void Adafruit_RA8875::drawEllipse (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint16_t color)
Draws a HW accelerated ellipse on the display
xCenter[in] The 0-based x location of the ellipse's center yCenter[in] The 0-based y location of the ellipse's center longAxis[in] The size in pixels of the ellipse's long axis shortAxis[in] The size in pixels of the ellipse's short axis color[in] The RGB565 color to use when drawing the pixel
Definition at line 725 of file Adafruit_RA8875.cpp.
References ellipseHelper().
drawFastHLine()
void Adafruit_RA8875::drawFastHLine (int16_t x, int16_t y, int16_t w, uint16_t color)
Definition at line 599 of file Adafruit_RA8875.cpp.
References drawLine().
drawFastVLine()
void Adafruit_RA8875::drawFastVLine (int16_t x, int16_t y, int16_t h, uint16_t color) virtual
Reimplemented from Adafruit_GFX.
Definition at line 589 of file Adafruit_RA8875.cpp.
References drawLine().
drawLine()
void Adafruit_RA8875::drawLine (int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint16_t color)
Draws a HW accelerated line on the display
x0[in] The 0-based starting x location y0[in] The 0-base starting y location x1[in] The 0-based ending x location y1[in] The 0-base ending y location color[in] The RGB565 color to use when drawing the pixel
Definition at line 542 of file Adafruit_RA8875.cpp.
References RA8875_DCR, RA8875_DCR_LINESQUTRI_STATUS, waitPoll(), writeCommand(), and writeData().
Referenced by drawFastHLine(), and drawFastVLine().
drawPixel()
void Adafruit_RA8875::drawPixel (int16_t x, int16_t y, uint16_t color) virtual
Draws a single pixel at the specified location
x[in] The 0-based x location y[in] The 0-base y location color[in] The RGB565 color to use when drawing the pixel
Implements Adafruit_GFX.
Definition at line 517 of file Adafruit_RA8875.cpp.
References _cs, RA8875_CURH0, RA8875_CURH1, RA8875_CURV0, RA8875_CURV1, RA8875_DATAWRITE, RA8875_MRWC, writeCommand(), and writeReg().
drawRect()
void Adafruit_RA8875::drawRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
Draws a HW accelerated rectangle on the display
x[in] The 0-based x location of the top-right corner y[in] The 0-based y location of the top-right corner w[in] The rectangle width h[in] The rectangle height color[in] The RGB565 color to use when drawing the pixel
Definition at line 615 of file Adafruit_RA8875.cpp.
References rectHelper().
drawTriangle()
void Adafruit_RA8875::drawTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color)
Draws a HW accelerated triangle on the display
x0[in] The 0-based x location of point 0 on the triangle y0[in] The 0-based y location of point 0 on the triangle x1[in] The 0-based x location of point 1 on the triangle y1[in] The 0-based y location of point 1 on the triangle x2[in] The 0-based x location of point 2 on the triangle y2[in] The 0-based y location of point 2 on the triangle color[in] The RGB565 color to use when drawing the pixel
Definition at line 691 of file Adafruit_RA8875.cpp.
References triangleHelper().
ellipseHelper()
void Adafruit_RA8875::ellipseHelper (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint16_t color, bool filled) private
Helper function for higher level ellipse drawing code
Definition at line 953 of file Adafruit_RA8875.cpp.
References RA8875_ELLIPSE, RA8875_ELLIPSE_STATUS, waitPoll(), writeCommand(), and writeData().
Referenced by drawEllipse(), and fillEllipse().
fillCircle()
void Adafruit_RA8875::fillCircle (int16_t x0, int16_t y0, int16_t r, uint16_t color)
Draws a HW accelerated filled circle on the display
x[in] The 0-based x location of the center of the circle y[in] The 0-based y location of the center of the circle w[in] The circle's radius color[in] The RGB565 color to use when drawing the pixel
Definition at line 673 of file Adafruit_RA8875.cpp.
References circleHelper().
fillCurve()
void Adafruit_RA8875::fillCurve (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint8_t curvePart, uint16_t color)
Draws a HW accelerated filled curve on the display
xCenter[in] The 0-based x location of the ellipse's center yCenter[in] The 0-based y location of the ellipse's center longAxis[in] The size in pixels of the ellipse's long axis shortAxis[in] The size in pixels of the ellipse's short axis curvePart[in] The corner to draw, where in clock-wise motion: 0 = 180-270 1 = 270-0 2 = 0-90 3 = 90-180 color[in] The RGB565 color to use when drawing the pixel
Definition at line 783 of file Adafruit_RA8875.cpp.
References curveHelper().
fillEllipse()
void Adafruit_RA8875::fillEllipse (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint16_t color)
Draws a HW accelerated filled ellipse on the display
xCenter[in] The 0-based x location of the ellipse's center yCenter[in] The 0-based y location of the ellipse's center longAxis[in] The size in pixels of the ellipse's long axis shortAxis[in] The size in pixels of the ellipse's short axis color[in] The RGB565 color to use when drawing the pixel
Definition at line 741 of file Adafruit_RA8875.cpp.
References ellipseHelper().
fillRect() [1/2]
void Adafruit_RA8875::fillRect (void)
Definition at line 502 of file Adafruit_RA8875.cpp.
References RA8875_DCR, RA8875_DCR_DRAWSQUARE, RA8875_DCR_FILL, RA8875_DCR_LINESQUTRI_START, RA8875_DCR_LINESQUTRI_STOP, writeCommand(), and writeData().
fillRect() [2/2]
void Adafruit_RA8875::fillRect (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color)
Draws a HW accelerated filled rectangle on the display
x[in] The 0-based x location of the top-right corner y[in] The 0-based y location of the top-right corner w[in] The rectangle width h[in] The rectangle height color[in] The RGB565 color to use when drawing the pixel
Definition at line 631 of file Adafruit_RA8875.cpp.
References rectHelper().
fillScreen()
void Adafruit_RA8875::fillScreen (uint16_t color)
Fills the screen with the spefied RGB565 color
color[in] The RGB565 color to use when drawing the pixel
Definition at line 643 of file Adafruit_RA8875.cpp.
References _height, _width, and rectHelper().
fillTriangle()
void Adafruit_RA8875::fillTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color)
Draws a HW accelerated filled triangle on the display
x0[in] The 0-based x location of point 0 on the triangle y0[in] The 0-based y location of point 0 on the triangle x1[in] The 0-based x location of point 1 on the triangle y1[in] The 0-based y location of point 1 on the triangle x2[in] The 0-based x location of point 2 on the triangle y2[in] The 0-based y location of point 2 on the triangle color[in] The RGB565 color to use when drawing the pixel
Definition at line 709 of file Adafruit_RA8875.cpp.
References triangleHelper().
getPixel()
uint16_t Adafruit_RA8875::getPixel (uint16_t x, uint16_t y)
Definition at line 254 of file Adafruit_RA8875.cpp.
References RA8875_DATAREAD, RA8875_MRWC, setXY(), and writeCommand().
GPIOX()
void Adafruit_RA8875::GPIOX (boolean on)
Definition at line 1055 of file Adafruit_RA8875.cpp.
References RA8875_GPIOX, and writeReg().
graphicsMode()
void Adafruit_RA8875::graphicsMode (void)
Sets the display in graphics mode (as opposed to text mode)
Definition at line 440 of file Adafruit_RA8875.cpp.
References RA8875_MWCR0, RA8875_MWCR0_TXTMODE, readData(), writeCommand(), and writeData().
height()
uint16_t Adafruit_RA8875::height (void)
Returns the display height in pixels
Returns
The 1-based display height in pixels
Definition at line 279 of file Adafruit_RA8875.cpp.
References _height.
initialize()
void Adafruit_RA8875::initialize (void) private
Initialises the driver IC (clock setup, etc.)
Definition at line 178 of file Adafruit_RA8875.cpp.
References _height, _size, _width, PLLinit(), RA8875_480x272, RA8875_HDWR, RA8875_HEAW0, RA8875_HEAW1, RA8875_HNDFTR, RA8875_HNDFTR_DE_HIGH, RA8875_HNDR, RA8875_HPWR, RA8875_HPWR_LOW, RA8875_HSAW0, RA8875_HSAW1, RA8875_HSTR, RA8875_MCLR, RA8875_MCLR_FULL, RA8875_MCLR_START, RA8875_PCSR, RA8875_PCSR_2CLK, RA8875_PCSR_4CLK, RA8875_PCSR_PDATL, RA8875_SYSR, RA8875_SYSR_16BPP, RA8875_SYSR_MCU8, RA8875_VDHR0, RA8875_VDHR1, RA8875_VEAW0, RA8875_VEAW1, RA8875_VNDR0, RA8875_VNDR1, RA8875_VPWR, RA8875_VPWR_LOW, RA8875_VSAW0, RA8875_VSAW1, RA8875_VSTR0, RA8875_VSTR1, and writeReg().
Referenced by begin().
PLLinit()
void Adafruit_RA8875::PLLinit (void) private
Initialise the PLL
Definition at line 158 of file Adafruit_RA8875.cpp.
References _size, RA8875_480x272, RA8875_PLLC1, RA8875_PLLC1_PLLDIV1, RA8875_PLLC2, RA8875_PLLC2_DIV4, and writeReg().
Referenced by initialize().
pushPixels()
void Adafruit_RA8875::pushPixels (uint32_t num, uint16_t p)
HW accelerated function to push a chunk of raw pixel data
num[in] The number of pixels to push p[in] The pixel color to use
Definition at line 487 of file Adafruit_RA8875.cpp.
References _cs, and RA8875_DATAWRITE.
PWM1config()
void Adafruit_RA8875::PWM1config (boolean on, uint8_t clock)
Definition at line 1085 of file Adafruit_RA8875.cpp.
References RA8875_P1CR, RA8875_P1CR_DISABLE, RA8875_P1CR_ENABLE, and writeReg().
PWM1out()
void Adafruit_RA8875::PWM1out (uint8_t p)
Definition at line 1067 of file Adafruit_RA8875.cpp.
References RA8875_P1DCR, and writeReg().
PWM2config()
void Adafruit_RA8875::PWM2config (boolean on, uint8_t clock)
Definition at line 1098 of file Adafruit_RA8875.cpp.
References RA8875_P2CR, RA8875_P2CR_DISABLE, RA8875_P2CR_ENABLE, and writeReg().
PWM2out()
void Adafruit_RA8875::PWM2out (uint8_t p)
Definition at line 1076 of file Adafruit_RA8875.cpp.
References RA8875_P2DCR, and writeReg().
readData()
uint8_t Adafruit_RA8875::readData (void)
Definition at line 1258 of file Adafruit_RA8875.cpp.
References _cs, RA8875_DATAREAD, spi_begin, and spi_end.
Referenced by graphicsMode(), readReg(), textColor(), textEnlarge(), textMode(), and textTransparent().
readReg()
uint8_t Adafruit_RA8875::readReg (uint8_t reg)
Definition at line 1232 of file Adafruit_RA8875.cpp.
References readData(), and writeCommand().
Referenced by begin(), touched(), touchEnable(), touchRead(), and waitPoll().
readStatus()
uint8_t Adafruit_RA8875::readStatus (void)
Definition at line 1293 of file Adafruit_RA8875.cpp.
References _cs, RA8875_CMDREAD, spi_begin, and spi_end.
rectHelper()
void Adafruit_RA8875::rectHelper (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t color, bool filled) private
Helper function for higher level rectangle drawing code
Definition at line 839 of file Adafruit_RA8875.cpp.
References RA8875_DCR, RA8875_DCR_LINESQUTRI_STATUS, waitPoll(), writeCommand(), and writeData().
Referenced by drawRect(), fillRect(), and fillScreen().
setXY()
void Adafruit_RA8875::setXY (uint16_t x, uint16_t y)
Sets the current X/Y position on the display before drawing
x[in] The 0-based x location y[in] The 0-base y location
Definition at line 472 of file Adafruit_RA8875.cpp.
References RA8875_CURH0, RA8875_CURH1, RA8875_CURV0, RA8875_CURV1, and writeReg().
Referenced by getPixel().
sleep()
void Adafruit_RA8875::sleep (boolean sleep)
Puts the display in sleep mode, or disables sleep mode if enabled
Definition at line 1206 of file Adafruit_RA8875.cpp.
References RA8875_PWRR, RA8875_PWRR_DISPOFF, RA8875_PWRR_SLEEP, and writeReg().
softReset()
void Adafruit_RA8875::softReset (void)
Performs a SW-based reset of the RA8875
Definition at line 146 of file Adafruit_RA8875.cpp.
References RA8875_PWRR, RA8875_PWRR_NORMAL, RA8875_PWRR_SOFTRESET, writeCommand(), and writeData().
textColor()
void Adafruit_RA8875::textColor (uint16_t foreColor, uint16_t bgColor)
Sets the fore and background color when rendering text
foreColor[in] The RGB565 color to use when rendering the text bgColor[in] The RGB565 colot to use for the background
Definition at line 332 of file Adafruit_RA8875.cpp.
References readData(), writeCommand(), and writeData().
textEnlarge()
void Adafruit_RA8875::textEnlarge (uint8_t scale)
Sets the text enlarge settings, using one of the following values:
0 = 1x zoom 1 = 2x zoom 2 = 3x zoom 3 = 4x zoom
scale[in] The zoom factor (0..3 for 1-4x zoom)
Definition at line 393 of file Adafruit_RA8875.cpp.
References _textScale, readData(), writeCommand(), and writeData().
textMode()
void Adafruit_RA8875::textMode (void)
Sets the display in text mode (as opposed to graphics mode)
Definition at line 288 of file Adafruit_RA8875.cpp.
References RA8875_MWCR0, RA8875_MWCR0_TXTMODE, readData(), writeCommand(), and writeData().
textSetCursor()
void Adafruit_RA8875::textSetCursor (uint16_t x, uint16_t y)
Sets the display in text mode (as opposed to graphics mode)
x[in] The x position of the cursor (in pixels, 0..1023) y[in] The y position of the cursor (in pixels, 0..511)
Definition at line 311 of file Adafruit_RA8875.cpp.
References writeCommand(), and writeData().
textTransparent()
void Adafruit_RA8875::textTransparent (uint16_t foreColor)
Sets the fore color when rendering text with a transparent bg
foreColor[in] The RGB565 color to use when rendering the text
Definition at line 364 of file Adafruit_RA8875.cpp.
References readData(), writeCommand(), and writeData().
textWrite()
void Adafruit_RA8875::textWrite (const char * buffer, uint16_t len = 0)
Renders some text on the screen when in text mode
buffer[in] The buffer containing the characters to render len[in] The size of the buffer in bytes
Definition at line 416 of file Adafruit_RA8875.cpp.
References _textScale, RA8875_MRWC, writeCommand(), and writeData().
touched()
boolean Adafruit_RA8875::touched (void)
Checks if a touch event has occured
Returns
True is a touch event has occured (reading it via touchRead() will clear the interrupt in memory)
Definition at line 1149 of file Adafruit_RA8875.cpp.
References RA8875_INTC2, RA8875_INTC2_TP, and readReg().
touchEnable()
void Adafruit_RA8875::touchEnable (boolean on)
Enables or disables the on-chip touch screen controller
Definition at line 1111 of file Adafruit_RA8875.cpp.
References _size, RA8875_800x480, RA8875_INTC1, RA8875_INTC1_TP, RA8875_TPCR0, RA8875_TPCR0_ADCCLK_DIV16, RA8875_TPCR0_ADCCLK_DIV4, RA8875_TPCR0_DISABLE, RA8875_TPCR0_ENABLE, RA8875_TPCR0_WAIT_4096CLK, RA8875_TPCR0_WAKEENABLE, RA8875_TPCR1, RA8875_TPCR1_AUTO, RA8875_TPCR1_DEBOUNCE, readReg(), and writeReg().
touchRead()
boolean Adafruit_RA8875::touchRead (uint16_t * x, uint16_t * y)
Reads the last touch event
x[out] Pointer to the uint16_t field to assign the raw X value y[out] Pointer to the uint16_t field to assign the raw Y value
Note
Calling this function will clear the touch panel interrupt on the RA8875, resetting the flag used by the 'touched' function
Definition at line 1166 of file Adafruit_RA8875.cpp.
References RA8875_INTC2, RA8875_INTC2_TP, RA8875_TPXH, RA8875_TPXYL, RA8875_TPYH, readReg(), and writeReg().
triangleHelper()
void Adafruit_RA8875::triangleHelper (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint16_t color, bool filled) private
Helper function for higher level triangle drawing code
Definition at line 893 of file Adafruit_RA8875.cpp.
References RA8875_DCR, RA8875_DCR_LINESQUTRI_STATUS, waitPoll(), writeCommand(), and writeData().
Referenced by drawTriangle(), and fillTriangle().
waitPoll()
boolean Adafruit_RA8875::waitPoll (uint8_t regname, uint8_t waitflag)
Waits for screen to finish by polling the status!
Definition at line 452 of file Adafruit_RA8875.cpp.
References readReg().
Referenced by circleHelper(), curveHelper(), drawLine(), ellipseHelper(), rectHelper(), and triangleHelper().
width()
uint16_t Adafruit_RA8875::width (void)
Returns the display width in pixels
Returns
The 1-based display width in pixels
Definition at line 270 of file Adafruit_RA8875.cpp.
References _width.
writeCommand()
void Adafruit_RA8875::writeCommand (uint8_t d)
Definition at line 1276 of file Adafruit_RA8875.cpp.
References _cs, RA8875_CMDWRITE, spi_begin, and spi_end.
Referenced by circleHelper(), curveHelper(), drawLine(), drawPixel(), ellipseHelper(), fillRect(), getPixel(), graphicsMode(), readReg(), rectHelper(), softReset(), textColor(), textEnlarge(), textMode(), textSetCursor(), textTransparent(), textWrite(), triangleHelper(), and writeReg().
writeData()
void Adafruit_RA8875::writeData (uint8_t d)
Definition at line 1243 of file Adafruit_RA8875.cpp.
References _cs, RA8875_DATAWRITE, spi_begin, and spi_end.
Referenced by circleHelper(), curveHelper(), drawLine(), ellipseHelper(), fillRect(), graphicsMode(), rectHelper(), softReset(), textColor(), textEnlarge(), textMode(), textSetCursor(), textTransparent(), textWrite(), triangleHelper(), and writeReg().
writeReg()
void Adafruit_RA8875::writeReg (uint8_t reg, uint8_t val)
Definition at line 1221 of file Adafruit_RA8875.cpp.
References writeCommand(), and writeData().
Referenced by displayOn(), drawPixel(), GPIOX(), initialize(), PLLinit(), PWM1config(), PWM1out(), PWM2config(), PWM2out(), setXY(), sleep(), touchEnable(), and touchRead().
Member Data Documentation
_cs
uint8_t Adafruit_RA8875::_cs private
Definition at line 146 of file Adafruit_RA8875.h.
Referenced by Adafruit_RA8875(), begin(), drawPixel(), pushPixels(), readData(), readStatus(), writeCommand(), and writeData().
_height
uint16_t Adafruit_RA8875::_height private
Definition at line 147 of file Adafruit_RA8875.h.
Referenced by begin(), fillScreen(), height(), and initialize().
_rst
uint8_t Adafruit_RA8875::_rst private
Definition at line 146 of file Adafruit_RA8875.h.
Referenced by Adafruit_RA8875(), and begin().
_size
enum RA8875sizes Adafruit_RA8875::_size private
Definition at line 149 of file Adafruit_RA8875.h.
Referenced by begin(), initialize(), PLLinit(), and touchEnable().
_textScale
uint8_t Adafruit_RA8875::_textScale private
Definition at line 148 of file Adafruit_RA8875.h.
Referenced by textEnlarge(), and textWrite().
_width
uint16_t Adafruit_RA8875::_width private
Definition at line 147 of file Adafruit_RA8875.h.
Referenced by begin(), fillScreen(), initialize(), and width().
The documentation for this class was generated from the following files:
External/Adafruit_RA8875/Adafruit_RA8875.h
External/Adafruit_RA8875/Adafruit_RA8875.cpp