uWindows: GDTransport Class Reference
GDTransport Class Reference
#include <dump.h>
Public Member Functions
void begin (void)
void cmdbyte (byte x)
void cmd32 (uint32_t x)
void cmd_n (byte *s, size_t n)
uint8_t rd (uint32_t a)
void wr (uint32_t a, uint8_t v)
uint16_t rd16 (uint32_t a)
void wr16 (uint32_t a, uint16_t v)
uint32_t rd32 (uint32_t a)
void rd_n (byte *dst, uint32_t addr, uint16_t n)
void wr_n (uint32_t addr, byte *src, uint16_t n)
void wr32 (uint32_t a, uint32_t v)
void flush ()
void finish ()
void __end ()
uint32_t getwp (void)
void bulk (uint32_t addr)
void resume (void)
void swap ()
void begin (void)
void cmdbyte (byte x)
void cmd32 (uint32_t x)
void cmd_n (byte *s, size_t n)
uint8_t rd (uint32_t a)
void wr (uint32_t a, uint8_t v)
uint16_t rd16 (uint32_t a)
void wr16 (uint32_t a, uint16_t v)
uint32_t rd32 (uint32_t a)
void rd_n (byte *dst, uint32_t addr, uint16_t n)
void wr32 (uint32_t a, uint32_t v)
void flush ()
void finish ()
void __end ()
uint32_t getwp (void)
void bulk (uint32_t addr)
void resume (void)
void begin ()
void __read (void *dst, uint32_t addr, uint32_t n)
void __write (uint32_t addr, void *src, uint32_t n)
void spisend (uint8_t b)
void cmd32 (uint32_t x)
void cmdbyte (byte x)
void cmd_n (byte *s, uint16_t n)
void flush ()
uint16_t rp ()
void finish ()
byte rd (uint32_t addr)
void wr (uint32_t addr, byte v)
uint16_t rd16 (uint32_t addr)
void wr16 (uint32_t addr, uint32_t v)
uint32_t rd32 (uint32_t addr)
void rd_n (byte *dst, uint32_t addr, uint32_t n)
void wr_n (uint32_t addr, byte *src, uint32_t n)
void wr32 (uint32_t addr, unsigned long v)
uint32_t getwp (void)
void bulk (uint32_t addr)
void resume (void)
void stopstream ()
void stop ()
void __end ()
void stream (void)
uint16_t __rd16 (uint32_t addr)
void __wr16 (uint32_t addr, uint16_t v)
void scu (byte a, byte b, byte c)
void getfree (uint16_t n)
void ios ()
void begin0 ()
void begin1 ()
void cmd32 (uint32_t x)
void cmdbyte (byte x)
void cmd_n (byte *s, uint16_t n)
void flush ()
uint16_t rp ()
void finish ()
byte rd (uint32_t addr)
void wr (uint32_t addr, byte v)
uint16_t rd16 (uint32_t addr)
void wr16 (uint32_t addr, uint32_t v)
uint32_t rd32 (uint32_t addr)
void rd_n (byte *dst, uint32_t addr, uint16_t n)
void wr_n (uint32_t addr, byte *src, uint16_t n)
void wr32 (uint32_t addr, unsigned long v)
uint32_t getwp (void)
void bulk (uint32_t addr)
void resume (void)
void stop ()
void stream (void)
void getfree (uint16_t n)
Static Public Member Functions
static void hostcmd (byte a)
static void default_spi_ioc (struct spi_ioc_transfer *ps)
static void __start (uint32_t addr)
static void __wstart (uint32_t addr)
static void __end ()
static unsigned int __rd16 (uint32_t addr)
static void __wr16 (uint32_t addr, unsigned int v)
static void hostcmd (byte a)
Public Attributes
byte streaming
uint16_t wp
uint16_t freespace
uint32_t wptr0
Private Member Functions
void hose (void)
Private Attributes
FILE * dumpfile
int counter
int fd
uint8_t writebuf [4096]
size_t nwrite
byte model
Detailed Description
Definition at line 1 of file dump.h.
Member Function Documentation
__end() [1/4]
void GDTransport::__end (void) inline
Definition at line 29 of file serial.h.
__end() [2/4]
void GDTransport::__end (void) inline
Definition at line 43 of file dump.h.
Referenced by GDClass::__end(), __rd16(), __wr16(), GDClass::begin(), bulk(), finish(), getfree(), rd(), rd16(), rd32(), rd_n(), ConfigRam::read(), GDClass::reset(), stop(), GDClass::storage(), stream(), wr(), wr16(), wr32(), and wr_n().
__end() [3/4]
void GDTransport::__end (void) inline
Definition at line 229 of file spidev.h.
References stopstream().
__end() [4/4]
static void GDTransport::__end (void) inline static
Definition at line 286 of file wiring.h.
References CS.
__rd16() [1/2]
uint16_t GDTransport::__rd16 (uint32_t addr) inline
Definition at line 239 of file spidev.h.
References __read().
Referenced by begin1(), ConfigRam::get_SDA(), ConfigRam::read(), and rp().
__rd16() [2/2]
static unsigned int GDTransport::__rd16 (uint32_t addr) inline static
Definition at line 304 of file wiring.h.
References __end(), and __start().
__read()
void GDTransport::__read (void * dst, uint32_t addr, uint32_t n) inline
Definition at line 41 of file spidev.h.
References default_spi_ioc().
Referenced by __rd16(), rd(), rd16(), rd32(), and rd_n().
__start()
static void GDTransport::__start (uint32_t addr) inline static
Definition at line 270 of file wiring.h.
References CS.
Referenced by __rd16(), bulk(), rd(), rd16(), rd32(), and rd_n().
__wr16() [1/2]
void GDTransport::__wr16 (uint32_t addr, uint16_t v) inline
Definition at line 246 of file spidev.h.
References __write().
Referenced by finish(), getfree(), ConfigRam::set_SCL(), ConfigRam::set_SDA(), and stop().
__wr16() [2/2]
static void GDTransport::__wr16 (uint32_t addr, unsigned int v) inline static
Definition at line 316 of file wiring.h.
References __end(), and __wstart().
__write()
void GDTransport::__write (uint32_t addr, void * src, uint32_t n) inline
Definition at line 61 of file spidev.h.
References default_spi_ioc().
Referenced by __wr16(), stopstream(), wr(), wr16(), wr32(), and wr_n().
__wstart()
static void GDTransport::__wstart (uint32_t addr) inline static
Definition at line 278 of file wiring.h.
References CS.
Referenced by __wr16(), rd_n(), stream(), wr(), wr16(), wr32(), and wr_n().
begin() [1/3]
void GDTransport::begin (void) inline
Definition at line 3 of file serial.h.
begin() [2/3]
void GDTransport::begin (void) inline
Definition at line 7 of file spidev.h.
References freespace, scu(), stream(), and wp.
begin() [3/3]
void GDTransport::begin (void) inline
Definition at line 14 of file dump.h.
References ft8xx_model, and hose().
begin0()
void GDTransport::begin0 () inline
Definition at line 22 of file wiring.h.
References hostcmd(), and ios().
Referenced by GDClass::begin().
begin1()
void GDTransport::begin1 () inline
Definition at line 41 of file wiring.h.
References __rd16(), CS, freespace, ft8xx_model, hostcmd(), stream(), and wp.
Referenced by GDClass::begin().
bulk() [1/4]
void GDTransport::bulk (uint32_t addr) inline
Definition at line 31 of file serial.h.
bulk() [2/4]
void GDTransport::bulk (uint32_t addr) inline
Definition at line 45 of file dump.h.
Referenced by GDClass::bulkrd().
bulk() [3/4]
void GDTransport::bulk (uint32_t addr) inline
Definition at line 204 of file spidev.h.
bulk() [4/4]
void GDTransport::bulk (uint32_t addr) inline
Definition at line 262 of file wiring.h.
References __end(), and __start().
cmd32() [1/4]
void GDTransport::cmd32 (uint32_t x) inline
Definition at line 10 of file serial.h.
cmd32() [2/4]
void GDTransport::cmd32 (uint32_t x) inline
Definition at line 23 of file dump.h.
Referenced by GDClass::cFFFFFF(), GDClass::cI(), and GDClass::cmd32().
cmd32() [3/4]
void GDTransport::cmd32 (uint32_t x) inline
Definition at line 84 of file spidev.h.
References freespace, getfree(), spisend(), and wp.
cmd32() [4/4]
void GDTransport::cmd32 (uint32_t x) inline
Definition at line 87 of file wiring.h.
References freespace, getfree(), and wp.
cmd_n() [1/4]
void GDTransport::cmd_n (byte * s, size_t n) inline
Definition at line 16 of file serial.h.
cmd_n() [2/4]
void GDTransport::cmd_n (byte * s, size_t n) inline
Definition at line 29 of file dump.h.
Referenced by GDClass::copyram().
cmd_n() [3/4]
void GDTransport::cmd_n (byte * s, uint16_t n) inline
Definition at line 108 of file spidev.h.
References freespace, getfree(), spisend(), and wp.
cmd_n() [4/4]
void GDTransport::cmd_n (byte * s, uint16_t n) inline
Definition at line 111 of file wiring.h.
References freespace, getfree(), and wp.
cmdbyte() [1/4]
void GDTransport::cmdbyte (byte x) inline
Definition at line 7 of file serial.h.
cmdbyte() [2/4]
void GDTransport::cmdbyte (byte x) inline
Definition at line 20 of file dump.h.
Referenced by GDClass::align(), GDClass::cH(), GDClass::cmdbyte(), GDClass::copy(), and GDClass::cs().
cmdbyte() [3/4]
void GDTransport::cmdbyte (byte x) inline
Definition at line 100 of file spidev.h.
References freespace, getfree(), spisend(), and wp.
cmdbyte() [4/4]
void GDTransport::cmdbyte (byte x) inline
Definition at line 103 of file wiring.h.
References freespace, getfree(), and wp.
default_spi_ioc()
static void GDTransport::default_spi_ioc (struct spi_ioc_transfer * ps) inline static
Definition at line 34 of file spidev.h.
Referenced by __read(), and __write().
finish() [1/4]
void GDTransport::finish (void) inline
Definition at line 28 of file serial.h.
finish() [2/4]
void GDTransport::finish (void) inline
Definition at line 42 of file dump.h.
Referenced by GDClass::finish(), and GDClass::get_inputs().
finish() [3/4]
void GDTransport::finish (void) inline
Definition at line 131 of file spidev.h.
References __wr16(), REG_CMD_WRITE, rp(), stopstream(), stream(), and wp.
finish() [4/4]
void GDTransport::finish (void) inline
Definition at line 142 of file wiring.h.
References __end(), __wr16(), REG_CMD_WRITE, rp(), stream(), and wp.
flush() [1/4]
void GDTransport::flush (void) inline
Definition at line 27 of file serial.h.
flush() [2/4]
void GDTransport::flush (void) inline
Definition at line 41 of file dump.h.
Referenced by GDClass::flush(), GDClass::self_calibrate(), and GDClass::swap().
flush() [3/4]
void GDTransport::flush (void) inline
Definition at line 120 of file spidev.h.
References getfree().
flush() [4/4]
void GDTransport::flush (void) inline
Definition at line 132 of file wiring.h.
References getfree().
getfree() [1/2]
void GDTransport::getfree (uint16_t n) inline
Definition at line 258 of file spidev.h.
References __wr16(), freespace, REG_CMD_WRITE, rp(), stopstream(), stream(), and wp.
Referenced by cmd32(), cmd_n(), cmdbyte(), and flush().
getfree() [2/2]
void GDTransport::getfree (uint16_t n) inline
Definition at line 333 of file wiring.h.
References __end(), __wr16(), freespace, REG_CMD_WRITE, rp(), stream(), streaming, and wp.
getwp() [1/4]
uint32_t GDTransport::getwp (void) inline
Definition at line 30 of file serial.h.
getwp() [2/4]
uint32_t GDTransport::getwp (void) inline
Definition at line 44 of file dump.h.
Referenced by GDClass::cmd_getprops(), and GDClass::cmd_memcrc().
getwp() [3/4]
uint32_t GDTransport::getwp (void) inline
Definition at line 200 of file spidev.h.
References RAM_CMD, and wp.
getwp() [4/4]
uint32_t GDTransport::getwp (void) inline
Definition at line 258 of file wiring.h.
References RAM_CMD, and wp.
hose()
void GDTransport::hose (void) inline private
Definition at line 4 of file dump.h.
Referenced by begin(), and swap().
hostcmd() [1/2]
static void GDTransport::hostcmd (byte a) inline static
Definition at line 19 of file dump.h.
Referenced by GDClass::begin(), begin0(), and begin1().
hostcmd() [2/2]
static void GDTransport::hostcmd (byte a) inline static
Definition at line 324 of file wiring.h.
References CS.
ios()
void GDTransport::ios () inline
Definition at line 9 of file wiring.h.
References CS, and MCU_Teensy32.
Referenced by GDClass::begin(), and begin0().
rd() [1/4]
uint8_t GDTransport::rd (uint32_t a) inline
Definition at line 20 of file serial.h.
rd() [2/4]
uint8_t GDTransport::rd (uint32_t a) inline
Definition at line 33 of file dump.h.
Referenced by GDClass::begin(), and GDClass::rd().
rd() [3/4]
byte GDTransport::rd (uint32_t addr) inline
Definition at line 140 of file spidev.h.
References __read(), stopstream(), and stream().
rd() [4/4]
byte GDTransport::rd (uint32_t addr) inline
Definition at line 151 of file wiring.h.
References __end(), __start(), and stream().
rd16() [1/4]
uint16_t GDTransport::rd16 (uint32_t a) inline
Definition at line 22 of file serial.h.
rd16() [2/4]
uint16_t GDTransport::rd16 (uint32_t a) inline
Definition at line 35 of file dump.h.
Referenced by GDClass::rd16().
rd16() [3/4]
uint16_t GDTransport::rd16 (uint32_t addr) inline
Definition at line 156 of file spidev.h.
References __read(), stopstream(), and stream().
rd16() [4/4]
uint16_t GDTransport::rd16 (uint32_t addr) inline
Definition at line 169 of file wiring.h.
References __end(), __start(), and stream().
rd32() [1/4]
uint32_t GDTransport::rd32 (uint32_t a) inline
Definition at line 24 of file serial.h.
rd32() [2/4]
uint32_t GDTransport::rd32 (uint32_t a) inline
Definition at line 37 of file dump.h.
Referenced by GDClass::begin(), GDClass::measure_freq(), and GDClass::rd32().
rd32() [3/4]
uint32_t GDTransport::rd32 (uint32_t addr) inline
Definition at line 172 of file spidev.h.
References __read(), stopstream(), and stream().
rd32() [4/4]
uint32_t GDTransport::rd32 (uint32_t addr) inline
Definition at line 190 of file wiring.h.
References __end(), __start(), and stream().
rd_n() [1/4]
void GDTransport::rd_n (byte * dst, uint32_t addr, uint16_t n) inline
Definition at line 25 of file serial.h.
rd_n() [2/4]
void GDTransport::rd_n (byte * dst, uint32_t addr, uint16_t n) inline
Definition at line 38 of file dump.h.
Referenced by GDClass::get_inputs().
rd_n() [3/4]
void GDTransport::rd_n (byte * dst, uint32_t addr, uint32_t n) inline
Definition at line 180 of file spidev.h.
References __read(), stopstream(), and stream().
rd_n() [4/4]
void GDTransport::rd_n (byte * dst, uint32_t addr, uint16_t n) inline
Definition at line 206 of file wiring.h.
References __end(), __start(), __wstart(), stream(), and wr_n().
resume() [1/4]
void GDTransport::resume (void) inline
Definition at line 32 of file serial.h.
resume() [2/4]
void GDTransport::resume (void) inline
Definition at line 46 of file dump.h.
Referenced by GDClass::begin(), ConfigRam::read(), GDClass::reset(), GDClass::resume(), and GDClass::storage().
resume() [3/4]
void GDTransport::resume (void) inline
Definition at line 210 of file spidev.h.
References stream().
resume() [4/4]
void GDTransport::resume (void) inline
Definition at line 266 of file wiring.h.
References stream().
rp() [1/2]
uint16_t GDTransport::rp () inline
Definition at line 123 of file spidev.h.
References __rd16(), REG_CMD_READ, and REPORT.
Referenced by finish(), and getfree().
rp() [2/2]
uint16_t GDTransport::rp () inline
Definition at line 135 of file wiring.h.
References __rd16(), GDClass::alert(), GD, and REG_CMD_READ.
scu()
void GDTransport::scu (byte a, byte b, byte c) inline
Definition at line 251 of file spidev.h.
Referenced by begin().
spisend()
void GDTransport::spisend (uint8_t b) inline
Definition at line 81 of file spidev.h.
Referenced by cmd32(), cmd_n(), and cmdbyte().
stop() [1/2]
void GDTransport::stop () inline
Definition at line 222 of file spidev.h.
References __wr16(), REG_CMD_WRITE, stopstream(), and wp.
stop() [2/2]
void GDTransport::stop () inline
Definition at line 291 of file wiring.h.
References __end(), __wr16(), REG_CMD_WRITE, and wp.
stopstream()
void GDTransport::stopstream () inline
Definition at line 214 of file spidev.h.
References __write(), and wptr0.
Referenced by __end(), finish(), getfree(), rd(), rd16(), rd32(), rd_n(), stop(), wr(), wr16(), wr32(), and wr_n().
stream() [1/2]
void GDTransport::stream (void) inline
Definition at line 234 of file spidev.h.
References RAM_CMD, wp, and wptr0.
Referenced by begin(), begin1(), finish(), getfree(), rd(), rd16(), rd32(), rd_n(), resume(), wr(), wr16(), wr32(), and wr_n().
stream() [2/2]
void GDTransport::stream (void) inline
Definition at line 299 of file wiring.h.
References __end(), __wstart(), RAM_CMD, and wp.
swap()
void GDTransport::swap (void) inline
Definition at line 47 of file dump.h.
References hose().
Referenced by GDClass::swap().
wr() [1/4]
void GDTransport::wr (uint32_t a, uint8_t v) inline
Definition at line 21 of file serial.h.
wr() [2/4]
void GDTransport::wr (uint32_t a, uint8_t v) inline
Definition at line 34 of file dump.h.
Referenced by GDClass::begin(), GDClass::get_inputs(), GDClass::reset(), GDClass::tune(), and GDClass::wr().
wr() [3/4]
void GDTransport::wr (uint32_t addr, byte v) inline
Definition at line 149 of file spidev.h.
References __write(), stopstream(), and stream().
wr() [4/4]
void GDTransport::wr (uint32_t addr, byte v) inline
Definition at line 161 of file wiring.h.
References __end(), __wstart(), and stream().
wr16() [1/4]
void GDTransport::wr16 (uint32_t a, uint16_t v) inline
Definition at line 23 of file serial.h.
wr16() [2/4]
void GDTransport::wr16 (uint32_t a, uint16_t v) inline
Definition at line 36 of file dump.h.
Referenced by GDClass::begin(), and GDClass::wr16().
wr16() [3/4]
void GDTransport::wr16 (uint32_t addr, uint32_t v) inline
Definition at line 165 of file spidev.h.
References __write(), stopstream(), and stream().
wr16() [4/4]
void GDTransport::wr16 (uint32_t addr, uint32_t v) inline
Definition at line 181 of file wiring.h.
References __end(), __wstart(), and stream().
wr32() [1/4]
void GDTransport::wr32 (uint32_t a, uint32_t v) inline
Definition at line 26 of file serial.h.
wr32() [2/4]
void GDTransport::wr32 (uint32_t a, uint32_t v) inline
Definition at line 40 of file dump.h.
Referenced by GDClass::begin(), GDClass::tune(), and GDClass::wr32().
wr32() [3/4]
void GDTransport::wr32 (uint32_t addr, unsigned long v) inline
Definition at line 193 of file spidev.h.
References __write(), stopstream(), and stream().
wr32() [4/4]
void GDTransport::wr32 (uint32_t addr, unsigned long v) inline
Definition at line 247 of file wiring.h.
References __end(), __wstart(), and stream().
wr_n() [1/3]
void GDTransport::wr_n (uint32_t addr, byte * src, uint16_t n) inline
Definition at line 39 of file dump.h.
Referenced by rd_n(), and GDClass::wr_n().
wr_n() [2/3]
void GDTransport::wr_n (uint32_t addr, byte * src, uint32_t n) inline
Definition at line 186 of file spidev.h.
References __write(), stopstream(), and stream().
wr_n() [3/3]
void GDTransport::wr_n (uint32_t addr, byte * src, uint16_t n) inline
Definition at line 237 of file wiring.h.
References __end(), __wstart(), and stream().
Member Data Documentation
counter
int GDTransport::counter private
Definition at line 3 of file dump.h.
dumpfile
FILE* GDTransport::dumpfile private
Definition at line 2 of file dump.h.
fd
int GDTransport::fd private
Definition at line 2 of file spidev.h.
freespace
uint16_t GDTransport::freespace
Definition at line 272 of file spidev.h.
Referenced by begin(), begin1(), cmd32(), cmd_n(), cmdbyte(), and getfree().
model
byte GDTransport::model private
Definition at line 7 of file wiring.h.
nwrite
size_t GDTransport::nwrite private
Definition at line 4 of file spidev.h.
streaming
byte GDTransport::streaming
Definition at line 270 of file spidev.h.
Referenced by getfree().
wp
uint16_t GDTransport::wp
Definition at line 271 of file spidev.h.
Referenced by begin(), begin1(), cmd32(), cmd_n(), cmdbyte(), finish(), getfree(), getwp(), stop(), and stream().
wptr0
uint32_t GDTransport::wptr0
Definition at line 273 of file spidev.h.
Referenced by stopstream(), and stream().
writebuf
uint8_t GDTransport::writebuf[4096] private
Definition at line 3 of file spidev.h.
The documentation for this class was generated from the following files:
External/GD3/transports/dump.h
External/GD3/transports/spidev.h
External/GD3/transports/wiring.h
External/GD3/transports/serial.h