uWindows: SdSpiLibDriver Class Reference
SdSpiLibDriver Class Reference
SdSpiLibDriver - use standard SPI library.
#include <SdSpiDriver.h>
Public Member Functions
void activate ()
void deactivate ()
void begin (uint8_t csPin)
uint8_t receive ()
uint8_t receive (uint8_t *buf, size_t n)
void send (uint8_t data)
void send (const uint8_t *buf, size_t n)
void select ()
void setSpiSettings (SPISettings spiSettings)
void unselect ()
Detailed Description
SdSpiLibDriver - use standard SPI library.
Definition at line 38 of file SdSpiDriver.h.
Member Function Documentation
activate()
void SdSpiLibDriver::activate () inline
Activate SPI hardware.
Definition at line 42 of file SdSpiDriver.h.
Referenced by SdSpiCard::type(), and SdSpiAltDriver::unselect().
begin()
void SdSpiLibDriver::begin (uint8_t csPin) inline
Initialize the SPI bus.
Parameters
[in] csPin SD card chip select pin.
Definition at line 53 of file SdSpiDriver.h.
Referenced by SdSpiCard::begin(), and SdSpiAltDriver::unselect().
deactivate()
void SdSpiLibDriver::deactivate () inline
Deactivate SPI hardware.
Definition at line 46 of file SdSpiDriver.h.
Referenced by SdSpiCard::type(), and SdSpiAltDriver::unselect().
receive() [1/2]
uint8_t SdSpiLibDriver::receive () inline
Receive a byte.
Returns
The byte.
Definition at line 63 of file SdSpiDriver.h.
Referenced by SdSpiCard::type(), and SdSpiAltDriver::unselect().
receive() [2/2]
uint8_t SdSpiLibDriver::receive (uint8_t * buf, size_t n) inline
Receive multiple bytes.
Parameters
[out] buf Buffer to receive the data.
[in] n Number of bytes to receive.
Returns
Zero for no error or nonzero error code.
Definition at line 73 of file SdSpiDriver.h.
select()
void SdSpiLibDriver::select () inline
Set CS low.
Definition at line 97 of file SdSpiDriver.h.
Referenced by SdSpiCard::type(), and SdSpiAltDriver::unselect().
send() [1/2]
void SdSpiLibDriver::send (uint8_t data) inline
Send a byte.
Parameters
[in] data Byte to send
Definition at line 83 of file SdSpiDriver.h.
Referenced by SdSpiCard::type(), and SdSpiAltDriver::unselect().
send() [2/2]
void SdSpiLibDriver::send (const uint8_t * buf, size_t n) inline
Send multiple bytes.
Parameters
[in] buf Buffer for data to be sent.
[in] n Number of bytes to send.
Definition at line 91 of file SdSpiDriver.h.
setSpiSettings()
void SdSpiLibDriver::setSpiSettings (SPISettings spiSettings) inline
Save SPISettings.
Parameters
[in] spiSettings SPI speed, mode, and byte order.
Definition at line 104 of file SdSpiDriver.h.
Referenced by SdSpiCard::begin(), and SdSpiAltDriver::unselect().
unselect()
void SdSpiLibDriver::unselect () inline
Set CS high.
Definition at line 108 of file SdSpiDriver.h.
Referenced by SdSpiCard::type(), and SdSpiAltDriver::unselect().
The documentation for this class was generated from the following file:
External/SDFat/SpiDriver/SdSpiDriver.h