uWindows: SdFat Class Reference
SdFat Class Reference
Main file system class for SdFat library.
#include <SdFat.h>
Public Member Functions
bool begin (uint8_t csPin=SS, SPISettings spiSettings=SPI_FULL_SPEED)
bool cardBegin (uint8_t csPin=SS, SPISettings settings=SPI_FULL_SPEED)
bool fsBegin ()
Public Member Functions inherited from SdFileSystem< SdSpiCard >
bool begin ()
SdSpiCard * card ()
void errorHalt ()
void errorHalt (Print *pr)
void errorHalt (char const *msg)
void errorHalt (Print *pr, char const *msg)
void errorPrint ()
void errorPrint (Print *pr)
void errorPrint (const char *msg)
void errorPrint (Print *pr, char const *msg)
void initErrorHalt ()
void initErrorHalt (Print *pr)
void initErrorHalt (char const *msg)
void initErrorHalt (Print *pr, char const *msg)
void initErrorPrint ()
void initErrorPrint (Print *pr)
void initErrorPrint (char const *msg)
void initErrorPrint (Print *pr, char const *msg)
uint8_t cardErrorCode ()
uint32_t cardErrorData ()
Public Member Functions inherited from FatFileSystem
bool begin (BlockDriver *blockDev, uint8_t part=0)
bool chdir (bool set_cwd=false)
bool chdir (const char *path, bool set_cwd=false)
void chvol ()
bool exists (const char *path)
void ls (print_t *pr, uint8_t flags=0)
void ls (print_t *pr, const char *path, uint8_t flags)
bool mkdir (const char *path, bool pFlag=true)
bool remove (const char *path)
bool rename (const char *oldPath, const char *newPath)
bool rmdir (const char *path)
bool truncate (const char *path, uint32_t length)
FatVolume * vol ()
FatFile * vwd ()
bool wipe (print_t *pr=0)
Public Member Functions inherited from FatVolume
FatVolume ()
uint8_t blocksPerCluster () const
uint32_t blocksPerFat () const
cache_t * cacheClear ()
uint32_t clusterCount () const
uint8_t clusterSizeShift () const
uint32_t dataStartBlock () const
uint8_t fatCount ()
uint32_t fatStartBlock () const
uint8_t fatType () const
int32_t freeClusterCount ()
bool init ()
bool init (uint8_t part)
uint16_t rootDirEntryCount () const
uint32_t rootDirStart () const
uint32_t volumeBlockCount () const
bool wipe (print_t *pr=0)
int8_t dbgFat (uint32_t n, uint32_t *v)
Additional Inherited Members
Protected Attributes inherited from SdFileSystem< SdSpiCard >
SdSpiCard m_card
Detailed Description
Main file system class for SdFat library.
Definition at line 302 of file SdFat.h.
Member Function Documentation
begin()
bool SdFat::begin (uint8_t csPin = SS, SPISettings spiSettings = SPI_FULL_SPEED) inline
Initialize SD card and file system.
Parameters
[in] csPin SD card chip select pin.
[in] spiSettings SPI speed, mode, and bit order.
Returns
true for success else false.
Definition at line 321 of file SdFat.h.
References SdFileSystem< SdDriverClass >::begin().
cardBegin()
bool SdFat::cardBegin (uint8_t csPin = SS, SPISettings settings = SPI_FULL_SPEED) inline
Initialize SD card for diagnostic use only.
Parameters
[in] csPin SD card chip select pin.
[in] settings SPI speed, mode, and bit order.
Returns
true for success else false.
Definition at line 331 of file SdFat.h.
fsBegin()
bool SdFat::fsBegin () inline
Initialize file system for diagnostic use only.
Returns
true for success else false.
Definition at line 337 of file SdFat.h.
References FatFileSystem::begin(), SdFileSystem< SdDriverClass >::begin(), SdioCardEX::begin(), and SPI_FULL_SPEED.
The documentation for this class was generated from the following file:
External/SDFat/SdFat.h