uWindows: Poly Class Reference
Poly Class Reference
#include <GD3.h>
Public Member Functions
void begin ()
void v (int _x, int _y)
void paint ()
void finish ()
void draw ()
void outline ()
Private Member Functions
void restart ()
void perim ()
Private Attributes
int x0
int y0
int x1
int y1
int x [8]
int y [8]
byte n
Detailed Description
Definition at line 1028 of file GD3.h.
Member Function Documentation
begin()
void Poly::begin () inline
Definition at line 1045 of file GD3.h.
References ALWAYS, GDClass::ColorMask(), INVERT, KEEP, GDClass::StencilFunc(), and GDClass::StencilOp().
Referenced by FT8XXDriver::fillQuad(), FT8XXDriver::fillTriangle(), and UIPrimitives::Polygon().
draw()
void Poly::draw () inline
Definition at line 1079 of file GD3.h.
Referenced by FT8XXDriver::fillQuad(), FT8XXDriver::fillTriangle(), and UIPrimitives::Polygon().
finish()
void Poly::finish (void) inline
Definition at line 1071 of file GD3.h.
References GDClass::Begin(), GDClass::ColorMask(), EDGE_STRIP_B, EQUAL, GDClass::StencilFunc(), and GDClass::Vertex2f().
outline()
void Poly::outline () inline
Definition at line 1083 of file GD3.h.
References GDClass::Begin(), and LINE_STRIP.
paint()
void Poly::paint () inline
Definition at line 1061 of file GD3.h.
References GDClass::Begin(), EDGE_STRIP_B, GDClass::ScissorSize(), and GDClass::ScissorXY().
perim()
void Poly::perim () inline private
Definition at line 1039 of file GD3.h.
References GDClass::Vertex2f().
restart()
void Poly::restart () inline private
Definition at line 1032 of file GD3.h.
v()
void Poly::v (int _x, int _y) inline
Definition at line 1052 of file GD3.h.
Referenced by FT8XXDriver::fillQuad(), FT8XXDriver::fillTriangle(), and UIPrimitives::Polygon().
Member Data Documentation
n
byte Poly::n private
Definition at line 1031 of file GD3.h.
x
int Poly::x[8] private
Definition at line 1030 of file GD3.h.
x0
int Poly::x0 private
Definition at line 1029 of file GD3.h.
x1
int Poly::x1 private
Definition at line 1029 of file GD3.h.
y
int Poly::y[8] private
Definition at line 1030 of file GD3.h.
y0
int Poly::y0 private
Definition at line 1029 of file GD3.h.
y1
int Poly::y1 private
Definition at line 1029 of file GD3.h.
The documentation for this class was generated from the following file:
External/GD3/GD3.h