uWindows: GDClass Class Reference
GDClass Class Reference
#include <GD3.h>
Public Member Functions
void begin (uint8_t options=(GD_CALIBRATE|GD_TRIM|GD_STORAGE))
uint16_t random ()
uint16_t random (uint16_t n)
void seed (uint16_t n)
int16_t rsin (int16_t r, uint16_t th)
int16_t rcos (int16_t r, uint16_t th)
void polar (int &x, int &y, int16_t r, uint16_t th)
uint16_t atan2 (int16_t y, int16_t x)
void copy (const PROGMEM uint8_t *src, int count)
void copyram (byte *src, int count)
void self_calibrate (void)
void swap (void)
void flush (void)
void finish (void)
void play (uint8_t instrument, uint8_t note=0)
void sample (uint32_t start, uint32_t len, uint16_t freq, uint16_t format, int loop=0)
void get_inputs (void)
void get_accel (int &x, int &y, int &z)
void AlphaFunc (byte func, byte ref)
void Begin (byte prim)
void BitmapHandle (byte handle)
void BitmapLayout (byte format, uint16_t linestride, uint16_t height)
void BitmapSize (byte filter, byte wrapx, byte wrapy, uint16_t width, uint16_t height)
void BitmapSource (uint32_t addr)
void BitmapTransformA (int32_t a)
void BitmapTransformB (int32_t b)
void BitmapTransformC (int32_t c)
void BitmapTransformD (int32_t d)
void BitmapTransformE (int32_t e)
void BitmapTransformF (int32_t f)
void BlendFunc (byte src, byte dst)
void Call (uint16_t dest)
void Cell (byte cell)
void ClearColorA (byte alpha)
void ClearColorRGB (byte red, byte green, byte blue)
void ClearColorRGB (uint32_t rgb)
void Clear (byte c, byte s, byte t)
void Clear (void)
void ClearStencil (byte s)
void ClearTag (byte s)
void ColorA (byte alpha)
void ColorMask (byte r, byte g, byte b, byte a)
void ColorRGB (byte red, byte green, byte blue)
void ColorRGB (uint32_t rgb)
void Display (void)
void End (void)
void Jump (uint16_t dest)
void LineWidth (uint16_t width)
void Macro (byte m)
void PointSize (uint16_t size)
void RestoreContext (void)
void Return (void)
void SaveContext (void)
void ScissorSize (uint16_t width, uint16_t height)
void ScissorXY (uint16_t x, uint16_t y)
void StencilFunc (byte func, byte ref, byte mask)
void StencilMask (byte mask)
void StencilOp (byte sfail, byte spass)
void TagMask (byte mask)
void Tag (byte s)
void Vertex2f (int16_t x, int16_t y)
void Vertex2ii (uint16_t x, uint16_t y, byte handle=0, byte cell=0)
void VertexFormat (byte frac)
void BitmapLayoutH (byte linestride, byte height)
void BitmapSizeH (byte width, byte height)
void PaletteSource (uint32_t addr)
void VertexTranslateX (uint32_t x)
void VertexTranslateY (uint32_t y)
void Nop (void)
void cmd_append (uint32_t ptr, uint32_t num)
void cmd_bgcolor (uint32_t c)
void cmd_button (int16_t x, int16_t y, uint16_t w, uint16_t h, byte font, uint16_t options, const char *s)
void cmd_calibrate (void)
void cmd_clock (int16_t x, int16_t y, int16_t r, uint16_t options, uint16_t h, uint16_t m, uint16_t s, uint16_t ms)
void cmd_coldstart (void)
void cmd_dial (int16_t x, int16_t y, int16_t r, uint16_t options, uint16_t val)
void cmd_dlstart (void)
void cmd_fgcolor (uint32_t c)
void cmd_gauge (int16_t x, int16_t y, int16_t r, uint16_t options, uint16_t major, uint16_t minor, uint16_t val, uint16_t range)
void cmd_getmatrix (void)
void cmd_getprops (uint32_t &ptr, uint32_t &w, uint32_t &h)
void cmd_getptr (void)
void cmd_gradcolor (uint32_t c)
void cmd_gradient (int16_t x0, int16_t y0, uint32_t rgb0, int16_t x1, int16_t y1, uint32_t rgb1)
void cmd_inflate (uint32_t ptr)
void cmd_interrupt (uint32_t ms)
void cmd_keys (int16_t x, int16_t y, int16_t w, int16_t h, byte font, uint16_t options, const char *s)
void cmd_loadidentity (void)
void cmd_loadimage (uint32_t ptr, int32_t options)
void cmd_memcpy (uint32_t dest, uint32_t src, uint32_t num)
void cmd_memset (uint32_t ptr, byte value, uint32_t num)
uint32_t cmd_memcrc (uint32_t ptr, uint32_t num)
void cmd_memwrite (uint32_t ptr, uint32_t num)
void cmd_regwrite (uint32_t ptr, uint32_t val)
void cmd_number (int16_t x, int16_t y, byte font, uint16_t options, uint32_t n)
void cmd_progress (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t options, uint16_t val, uint16_t range)
void cmd_regread (uint32_t ptr)
void cmd_rotate (int32_t a)
void cmd_scale (int32_t sx, int32_t sy)
void cmd_screensaver (void)
void cmd_scrollbar (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t options, uint16_t val, uint16_t size, uint16_t range)
void cmd_setfont (byte font, uint32_t ptr)
void cmd_setmatrix (void)
void cmd_sketch (int16_t x, int16_t y, uint16_t w, uint16_t h, uint32_t ptr, uint16_t format)
void cmd_slider (int16_t x, int16_t y, uint16_t w, uint16_t h, uint16_t options, uint16_t val, uint16_t range)
void cmd_snapshot (uint32_t ptr)
void cmd_spinner (int16_t x, int16_t y, byte style, byte scale)
void cmd_stop (void)
void cmd_swap (void)
void cmd_text (int16_t x, int16_t y, byte font, uint16_t options, const char *s)
void cmd_toggle (int16_t x, int16_t y, int16_t w, byte font, uint16_t options, uint16_t state, const char *s)
void cmd_track (int16_t x, int16_t y, uint16_t w, uint16_t h, byte tag)
void cmd_translate (int32_t tx, int32_t ty)
void cmd_playvideo (int32_t options)
void cmd_romfont (uint32_t font, uint32_t romslot)
void cmd_mediafifo (uint32_t ptr, uint32_t size)
void cmd_setbase (uint32_t b)
void cmd_videoframe (uint32_t dst, uint32_t ptr)
void cmd_snapshot2 (uint32_t fmt, uint32_t ptr, int16_t x, int16_t y, int16_t w, int16_t h)
void cmd_setfont2 (uint32_t font, uint32_t ptr, uint32_t firstchar)
void cmd_setrotate (uint32_t r)
void cmd_videostart ()
void cmd_setbitmap (uint32_t source, uint16_t fmt, uint16_t w, uint16_t h)
byte rd (uint32_t addr)
void wr (uint32_t addr, uint8_t v)
uint16_t rd16 (uint32_t addr)
void wr16 (uint32_t addr, uint16_t v)
uint32_t rd32 (uint32_t addr)
void wr32 (uint32_t addr, uint32_t v)
void wr_n (uint32_t addr, byte *src, uint32_t n)
void cmd32 (uint32_t b)
void bulkrd (uint32_t a)
void resume (void)
void __end (void)
void reset (void)
void dumpscreen (void)
byte load (const char *filename, void(*progress)(long, long)=NULL)
void safeload (const char *filename)
void alert (const char *message)
void storage (void)
void tune (void)
Public Attributes
int w
int h
struct {
uint16_t track_tag
uint16_t track_val
uint16_t rz
uint16_t __dummy_1
int16_t y
int16_t x
int16_t tag_y
int16_t tag_x
uint8_t tag
uint8_t ptag
} inputs
sdcard SD
Detailed Description
Definition at line 439 of file GD3.h.
Member Function Documentation
__end()
void GDClass::__end (void)
Definition at line 1304 of file GD3.cpp.
References GDTransport::__end().
Referenced by Streamer::begin(), and Streamer::feed().
alert()
void GDClass::alert (const char * message)
Definition at line 1388 of file GD3.cpp.
References copy.
Referenced by GDTransport::rp().
AlphaFunc()
void GDClass::AlphaFunc (byte func, byte ref)
Definition at line 672 of file GD3.cpp.
atan2()
uint16_t GDClass::atan2 (int16_t y, int16_t x)
Definition at line 568 of file GD3.cpp.
References pgm_read_byte.
begin()
void GDClass::begin (uint8_t options = (GD_CALIBRATE | GD_TRIM | GD_STORAGE))
Definition at line 216 of file GD3.cpp.
References GDTransport::__end(), GDTransport::begin0(), GDTransport::begin1(), BOARD, BOARD_FTDI_81X, CALIBRATION, flush(), FT_810_ENABLE, FT_811_ENABLE, FT_812_ENABLE, FT_813_ENABLE, GD_CALIBRATE, GD_STORAGE, GD_TRIM, GDTransport::hostcmd(), GDTransport::ios(), NULL, GDTransport::rd(), GDTransport::rd32(), ConfigRam::read(), REG_CSPREAD, REG_DITHER, REG_GPIO, REG_GPIO_DIR, REG_HCYCLE, REG_HOFFSET, REG_HSIZE, REG_HSYNC0, REG_HSYNC1, REG_ID, REG_PCLK, REG_PCLK_POL, REG_PWM_DUTY, REG_ROTATE, REG_TOUCH_RZTHRESH, REG_TOUCH_TRANSFORM_A, REG_VCYCLE, REG_VOFFSET, REG_VSIZE, REG_VSYNC0, REG_VSYNC1, GDTransport::resume(), SD_PIN, GDTransport::wr(), GDTransport::wr16(), GDTransport::wr32(), and wr32().
Referenced by FT8XXDriver::FT8XXDriver(), and FT8XXDriver::Init().
Begin()
void GDClass::Begin (byte prim)
Definition at line 675 of file GD3.cpp.
Referenced by circle(), UIPrimitives::CircleFlat(), UIPrimitives::CircleOutline(), UIPrimitives::CircleRaised(), UIPrimitives::CircleSunken(), Compass::Draw(), DropDownList::Draw(), IconButton::Draw(), FT8XXDriver::drawCircle(), FT8XXDriver::drawLine(), UIPrimitives::DrawLine(), FT8XXDriver::drawPixel(), UIPrimitives::DrawPoint(), FT8XXDriver::drawRect(), FT8XXDriver::drawRoundRect(), FT8XXDriver::drawTriangle(), FT8XXDriver::fillCircle(), FT8XXDriver::fillRect(), FT8XXDriver::fillRoundRect(), Poly::finish(), Poly::outline(), Poly::paint(), UIPrimitives::RaisedPanel(), and UIPrimitives::SunkenPanel().
BitmapHandle()
void GDClass::BitmapHandle (byte handle)
Definition at line 678 of file GD3.cpp.
Referenced by UIPrimitives::DrawLine(), and UIPrimitives::DrawPoint().
BitmapLayout()
void GDClass::BitmapLayout (byte format, uint16_t linestride, uint16_t height)
Definition at line 681 of file GD3.cpp.
BitmapLayoutH()
void GDClass::BitmapLayoutH (byte linestride, byte height)
Definition at line 858 of file GD3.cpp.
BitmapSize()
void GDClass::BitmapSize (byte filter, byte wrapx, byte wrapy, uint16_t width, uint16_t height)
Definition at line 693 of file GD3.cpp.
References ft8xx_model.
BitmapSizeH()
void GDClass::BitmapSizeH (byte width, byte height)
Definition at line 861 of file GD3.cpp.
BitmapSource()
void GDClass::BitmapSource (uint32_t addr)
Definition at line 711 of file GD3.cpp.
BitmapTransformA()
void GDClass::BitmapTransformA (int32_t a)
Definition at line 714 of file GD3.cpp.
BitmapTransformB()
void GDClass::BitmapTransformB (int32_t b)
Definition at line 717 of file GD3.cpp.
BitmapTransformC()
void GDClass::BitmapTransformC (int32_t c)
Definition at line 720 of file GD3.cpp.
BitmapTransformD()
void GDClass::BitmapTransformD (int32_t d)
Definition at line 723 of file GD3.cpp.
BitmapTransformE()
void GDClass::BitmapTransformE (int32_t e)
Definition at line 726 of file GD3.cpp.
BitmapTransformF()
void GDClass::BitmapTransformF (int32_t f)
Definition at line 729 of file GD3.cpp.
BlendFunc()
void GDClass::BlendFunc (byte src, byte dst)
Definition at line 732 of file GD3.cpp.
Referenced by UIPrimitives::CircleOutline(), and FT8XXDriver::drawCircle().
bulkrd()
void GDClass::bulkrd (uint32_t a)
Definition at line 1298 of file GD3.cpp.
References GDTransport::bulk().
Call()
void GDClass::Call (uint16_t dest)
Definition at line 735 of file GD3.cpp.
Cell()
void GDClass::Cell (byte cell)
Definition at line 738 of file GD3.cpp.
Referenced by UIPrimitives::DrawLine(), and UIPrimitives::DrawPoint().
Clear() [1/2]
void GDClass::Clear (byte c, byte s, byte t)
Definition at line 750 of file GD3.cpp.
Referenced by UIPrimitives::CircleOutline(), FT8XXDriver::clearScreen(), and FT8XXDriver::fillScreen().
Clear() [2/2]
void GDClass::Clear (void)
Definition at line 754 of file GD3.cpp.
ClearColorA()
void GDClass::ClearColorA (byte alpha)
Definition at line 741 of file GD3.cpp.
ClearColorRGB() [1/2]
void GDClass::ClearColorRGB (byte red, byte green, byte blue)
Definition at line 744 of file GD3.cpp.
Referenced by FT8XXDriver::clearScreen(), and FT8XXDriver::fillScreen().
ClearColorRGB() [2/2]
void GDClass::ClearColorRGB (uint32_t rgb)
Definition at line 747 of file GD3.cpp.
ClearStencil()
void GDClass::ClearStencil (byte s)
Definition at line 757 of file GD3.cpp.
ClearTag()
void GDClass::ClearTag (byte s)
Definition at line 760 of file GD3.cpp.
cmd32()
void GDClass::cmd32 (uint32_t b)
Definition at line 1237 of file GD3.cpp.
References GDTransport::cmd32().
Referenced by FT8XXDriver::writeCommand().
cmd_append()
void GDClass::cmd_append (uint32_t ptr, uint32_t num)
Definition at line 877 of file GD3.cpp.
cmd_bgcolor()
void GDClass::cmd_bgcolor (uint32_t c)
Definition at line 882 of file GD3.cpp.
cmd_button()
void GDClass::cmd_button (int16_t x, int16_t y, uint16_t w, uint16_t h, byte font, uint16_t options, const char * s)
Definition at line 886 of file GD3.cpp.
cmd_calibrate()
void GDClass::cmd_calibrate (void)
Definition at line 896 of file GD3.cpp.
cmd_clock()
void GDClass::cmd_clock (int16_t x, int16_t y, int16_t r, uint16_t options, uint16_t h, uint16_t m, uint16_t s, uint16_t ms)
Definition at line 900 of file GD3.cpp.
cmd_coldstart()
void GDClass::cmd_coldstart (void)
Definition at line 911 of file GD3.cpp.
Referenced by FT8XXDriver::softReset().
cmd_dial()
void GDClass::cmd_dial (int16_t x, int16_t y, int16_t r, uint16_t options, uint16_t val)
Definition at line 914 of file GD3.cpp.
cmd_dlstart()
void GDClass::cmd_dlstart (void)
Definition at line 923 of file GD3.cpp.
cmd_fgcolor()
void GDClass::cmd_fgcolor (uint32_t c)
Definition at line 926 of file GD3.cpp.
cmd_gauge()
void GDClass::cmd_gauge (int16_t x, int16_t y, int16_t r, uint16_t options, uint16_t major, uint16_t minor, uint16_t val, uint16_t range)
Definition at line 930 of file GD3.cpp.
cmd_getmatrix()
void GDClass::cmd_getmatrix (void)
Definition at line 941 of file GD3.cpp.
cmd_getprops()
void GDClass::cmd_getprops (uint32_t & ptr, uint32_t & w, uint32_t & h)
Definition at line 950 of file GD3.cpp.
References GDTransport::getwp().
cmd_getptr()
void GDClass::cmd_getptr (void)
Definition at line 959 of file GD3.cpp.
cmd_gradcolor()
void GDClass::cmd_gradcolor (uint32_t c)
Definition at line 963 of file GD3.cpp.
cmd_gradient()
void GDClass::cmd_gradient (int16_t x0, int16_t y0, uint32_t rgb0, int16_t x1, int16_t y1, uint32_t rgb1)
Definition at line 967 of file GD3.cpp.
cmd_inflate()
void GDClass::cmd_inflate (uint32_t ptr)
Definition at line 976 of file GD3.cpp.
cmd_interrupt()
void GDClass::cmd_interrupt (uint32_t ms)
Definition at line 980 of file GD3.cpp.
cmd_keys()
void GDClass::cmd_keys (int16_t x, int16_t y, int16_t w, int16_t h, byte font, uint16_t options, const char * s)
Definition at line 984 of file GD3.cpp.
cmd_loadidentity()
void GDClass::cmd_loadidentity (void)
Definition at line 994 of file GD3.cpp.
cmd_loadimage()
void GDClass::cmd_loadimage (uint32_t ptr, int32_t options)
Definition at line 997 of file GD3.cpp.
cmd_mediafifo()
void GDClass::cmd_mediafifo (uint32_t ptr, uint32_t size)
Definition at line 1166 of file GD3.cpp.
cmd_memcpy()
void GDClass::cmd_memcpy (uint32_t dest, uint32_t src, uint32_t num)
Definition at line 1002 of file GD3.cpp.
cmd_memcrc()
uint32_t GDClass::cmd_memcrc (uint32_t ptr, uint32_t num)
Definition at line 1014 of file GD3.cpp.
References GDTransport::getwp().
cmd_memset()
void GDClass::cmd_memset (uint32_t ptr, byte value, uint32_t num)
Definition at line 1008 of file GD3.cpp.
cmd_memwrite()
void GDClass::cmd_memwrite (uint32_t ptr, uint32_t num)
Definition at line 1022 of file GD3.cpp.
Referenced by Streamer::feed().
cmd_number()
void GDClass::cmd_number (int16_t x, int16_t y, byte font, uint16_t options, uint32_t n)
Definition at line 1033 of file GD3.cpp.
cmd_playvideo()
void GDClass::cmd_playvideo (int32_t options)
Definition at line 1157 of file GD3.cpp.
cmd_progress()
void GDClass::cmd_progress (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t options, uint16_t val, uint16_t range)
Definition at line 1041 of file GD3.cpp.
cmd_regread()
void GDClass::cmd_regread (uint32_t ptr)
Definition at line 1052 of file GD3.cpp.
cmd_regwrite()
void GDClass::cmd_regwrite (uint32_t ptr, uint32_t val)
Definition at line 1027 of file GD3.cpp.
cmd_romfont()
void GDClass::cmd_romfont (uint32_t font, uint32_t romslot)
Definition at line 1161 of file GD3.cpp.
cmd_rotate()
void GDClass::cmd_rotate (int32_t a)
Definition at line 1057 of file GD3.cpp.
cmd_scale()
void GDClass::cmd_scale (int32_t sx, int32_t sy)
Definition at line 1061 of file GD3.cpp.
cmd_screensaver()
void GDClass::cmd_screensaver (void)
Definition at line 1066 of file GD3.cpp.
cmd_scrollbar()
void GDClass::cmd_scrollbar (int16_t x, int16_t y, int16_t w, int16_t h, uint16_t options, uint16_t val, uint16_t size, uint16_t range)
Definition at line 1069 of file GD3.cpp.
cmd_setbase()
void GDClass::cmd_setbase (uint32_t b)
Definition at line 1171 of file GD3.cpp.
cmd_setbitmap()
void GDClass::cmd_setbitmap (uint32_t source, uint16_t fmt, uint16_t w, uint16_t h)
Definition at line 1195 of file GD3.cpp.
cmd_setfont()
void GDClass::cmd_setfont (byte font, uint32_t ptr)
Definition at line 1080 of file GD3.cpp.
cmd_setfont2()
void GDClass::cmd_setfont2 (uint32_t font, uint32_t ptr, uint32_t firstchar)
Definition at line 1189 of file GD3.cpp.
cmd_setmatrix()
void GDClass::cmd_setmatrix (void)
Definition at line 1085 of file GD3.cpp.
cmd_setrotate()
void GDClass::cmd_setrotate (uint32_t r)
Definition at line 1204 of file GD3.cpp.
Referenced by FT8XXDriver::setRotation().
cmd_sketch()
void GDClass::cmd_sketch (int16_t x, int16_t y, uint16_t w, uint16_t h, uint32_t ptr, uint16_t format)
Definition at line 1088 of file GD3.cpp.
cmd_slider()
void GDClass::cmd_slider (int16_t x, int16_t y, uint16_t w, uint16_t h, uint16_t options, uint16_t val, uint16_t range)
Definition at line 1097 of file GD3.cpp.
cmd_snapshot()
void GDClass::cmd_snapshot (uint32_t ptr)
Definition at line 1108 of file GD3.cpp.
cmd_snapshot2()
void GDClass::cmd_snapshot2 (uint32_t fmt, uint32_t ptr, int16_t x, int16_t y, int16_t w, int16_t h)
Definition at line 1180 of file GD3.cpp.
cmd_spinner()
void GDClass::cmd_spinner (int16_t x, int16_t y, byte style, byte scale)
Definition at line 1112 of file GD3.cpp.
cmd_stop()
void GDClass::cmd_stop (void)
Definition at line 1119 of file GD3.cpp.
cmd_swap()
void GDClass::cmd_swap (void)
Definition at line 1122 of file GD3.cpp.
cmd_text()
void GDClass::cmd_text (int16_t x, int16_t y, byte font, uint16_t options, const char * s)
Definition at line 1125 of file GD3.cpp.
Referenced by FT8XXDriver::drawChar(), ScreenSaver::ScreenSaver(), UIPrimitives::Text(), and FT8XXDriver::textWrite().
cmd_toggle()
void GDClass::cmd_toggle (int16_t x, int16_t y, int16_t w, byte font, uint16_t options, uint16_t state, const char * s)
Definition at line 1133 of file GD3.cpp.
cmd_track()
void GDClass::cmd_track (int16_t x, int16_t y, uint16_t w, uint16_t h, byte tag)
Definition at line 1143 of file GD3.cpp.
cmd_translate()
void GDClass::cmd_translate (int32_t tx, int32_t ty)
Definition at line 1152 of file GD3.cpp.
cmd_videoframe()
void GDClass::cmd_videoframe (uint32_t dst, uint32_t ptr)
Definition at line 1175 of file GD3.cpp.
cmd_videostart()
void GDClass::cmd_videostart ()
Definition at line 1208 of file GD3.cpp.
ColorA()
void GDClass::ColorA (byte alpha)
Definition at line 763 of file GD3.cpp.
Referenced by UIPrimitives::CircleFlat(), UIPrimitives::CircleRaised(), UIPrimitives::CircleSunken(), FT8XXDriver::colorA(), UIPrimitives::DrawLine(), UIPrimitives::DrawPoint(), UIPrimitives::Polygon(), UIPrimitives::RaisedPanel(), ScreenSaver::ScreenSaver(), UIPrimitives::SunkenPanel(), and UIPrimitives::Text().
ColorMask()
void GDClass::ColorMask (byte r, byte g, byte b, byte a)
Definition at line 766 of file GD3.cpp.
Referenced by Poly::begin(), UIPrimitives::CircleOutline(), FT8XXDriver::drawCircle(), and Poly::finish().
ColorRGB() [1/2]
void GDClass::ColorRGB (byte red, byte green, byte blue)
Definition at line 769 of file GD3.cpp.
Referenced by UIPrimitives::CircleFlat(), UIPrimitives::CircleOutline(), UIPrimitives::CircleRaised(), UIPrimitives::CircleSunken(), Compass::Draw(), DropDownList::Draw(), FT8XXDriver::drawChar(), FT8XXDriver::drawCircle(), FT8XXDriver::drawLine(), UIPrimitives::DrawLine(), FT8XXDriver::drawPixel(), UIPrimitives::DrawPoint(), FT8XXDriver::drawRect(), FT8XXDriver::drawRoundRect(), FT8XXDriver::drawTriangle(), FT8XXDriver::fillCircle(), FT8XXDriver::fillQuad(), FT8XXDriver::fillRect(), FT8XXDriver::fillRoundRect(), FT8XXDriver::fillTriangle(), UIPrimitives::Polygon(), UIPrimitives::RaisedPanel(), ScreenSaver::ScreenSaver(), UIPrimitives::SunkenPanel(), UIPrimitives::Text(), and FT8XXDriver::textWrite().
ColorRGB() [2/2]
void GDClass::ColorRGB (uint32_t rgb)
Definition at line 781 of file GD3.cpp.
copy()
void GDClass::copy (const PROGMEM uint8_t * src, int count)
Definition at line 657 of file GD3.cpp.
References GDTransport::cmdbyte().
copyram()
void GDClass::copyram (byte * src, int count)
Definition at line 666 of file GD3.cpp.
References GDTransport::cmd_n().
Referenced by Streamer::feed().
Display()
void GDClass::Display (void)
Definition at line 784 of file GD3.cpp.
dumpscreen()
void GDClass::dumpscreen (void)
End()
void GDClass::End (void)
Definition at line 787 of file GD3.cpp.
Referenced by DropDownList::Draw(), FT8XXDriver::drawLine(), and FT8XXDriver::fillRect().
finish()
void GDClass::finish (void)
Definition at line 1240 of file GD3.cpp.
References GDTransport::finish().
flush()
void GDClass::flush (void)
Definition at line 178 of file GD3.cpp.
References GDTransport::flush().
Referenced by begin().
get_accel()
void GDClass::get_accel (int & x, int & y, int & z)
Definition at line 1243 of file GD3.cpp.
get_inputs()
void GDClass::get_inputs (void)
Definition at line 1255 of file GD3.cpp.
References GDTransport::finish(), GDTransport::rd_n(), REG_TAG, REG_TOUCH_RZ, REG_TRACKER, and GDTransport::wr().
Referenced by FT8XXDriver::touched(), and FT8XXDriver::touchRead().
Jump()
void GDClass::Jump (uint16_t dest)
Definition at line 790 of file GD3.cpp.
LineWidth()
void GDClass::LineWidth (uint16_t width)
Definition at line 793 of file GD3.cpp.
Referenced by Compass::Draw(), FT8XXDriver::drawLine(), UIPrimitives::DrawLine(), FT8XXDriver::drawRect(), FT8XXDriver::drawRoundRect(), FT8XXDriver::drawTriangle(), FT8XXDriver::fillRoundRect(), UIPrimitives::RaisedPanel(), and UIPrimitives::SunkenPanel().
load()
byte GDClass::load (const char * filename, void(*)(long, long) progress = NULL)
Macro()
void GDClass::Macro (byte m)
Definition at line 796 of file GD3.cpp.
Nop()
void GDClass::Nop (void)
Definition at line 873 of file GD3.cpp.
PaletteSource()
void GDClass::PaletteSource (uint32_t addr)
Definition at line 864 of file GD3.cpp.
play()
void GDClass::play (uint8_t instrument, uint8_t note = 0)
Definition at line 1309 of file GD3.cpp.
References REG_PLAY, and REG_SOUND.
PointSize()
void GDClass::PointSize (uint16_t size)
Definition at line 799 of file GD3.cpp.
Referenced by circle(), UIPrimitives::CircleFlat(), UIPrimitives::CircleRaised(), UIPrimitives::CircleSunken(), FT8XXDriver::drawCircle(), UIPrimitives::DrawPoint(), and FT8XXDriver::fillCircle().
polar()
void GDClass::polar (int & x, int & y, int16_t r, uint16_t th)
Definition at line 558 of file GD3.cpp.
References PROGMEM, rcos(), and rsin().
random() [1/2]
uint16_t GDClass::random ()
Definition at line 523 of file GD3.cpp.
random() [2/2]
uint16_t GDClass::random (uint16_t n)
Definition at line 530 of file GD3.cpp.
rcos()
int16_t GDClass::rcos (int16_t r, uint16_t th)
Definition at line 554 of file GD3.cpp.
Referenced by polar().
rd()
byte GDClass::rd (uint32_t addr)
Definition at line 1212 of file GD3.cpp.
References GDTransport::rd().
rd16()
uint16_t GDClass::rd16 (uint32_t addr)
Definition at line 1218 of file GD3.cpp.
References GDTransport::rd16().
Referenced by FT8XXDriver::readReg().
rd32()
uint32_t GDClass::rd32 (uint32_t addr)
Definition at line 1224 of file GD3.cpp.
References GDTransport::rd32().
Referenced by Streamer::feed().
reset()
void GDClass::reset (void)
Definition at line 1321 of file GD3.cpp.
References GDTransport::__end(), PROGMEM, REG_CPURESET, GDTransport::resume(), and GDTransport::wr().
RestoreContext()
void GDClass::RestoreContext (void)
Definition at line 802 of file GD3.cpp.
Referenced by UIPrimitives::CircleOutline().
resume()
void GDClass::resume (void)
Definition at line 1301 of file GD3.cpp.
References GDTransport::resume().
Referenced by Streamer::begin(), and Streamer::feed().
Return()
void GDClass::Return (void)
Definition at line 805 of file GD3.cpp.
rsin()
int16_t GDClass::rsin (int16_t r, uint16_t th)
Definition at line 541 of file GD3.cpp.
Referenced by polar().
safeload()
void GDClass::safeload (const char * filename)
Definition at line 1399 of file GD3.cpp.
References copy.
sample()
void GDClass::sample (uint32_t start, uint32_t len, uint16_t freq, uint16_t format, int loop = 0)
Definition at line 1313 of file GD3.cpp.
References REG_PLAYBACK_FORMAT, REG_PLAYBACK_FREQ, REG_PLAYBACK_LENGTH, REG_PLAYBACK_LOOP, REG_PLAYBACK_PLAY, REG_PLAYBACK_START, wr(), wr16(), and wr32().
Referenced by Streamer::begin().
SaveContext()
void GDClass::SaveContext (void)
Definition at line 808 of file GD3.cpp.
Referenced by UIPrimitives::CircleOutline().
ScissorSize()
void GDClass::ScissorSize (uint16_t width, uint16_t height)
Definition at line 811 of file GD3.cpp.
References ft8xx_model.
Referenced by Poly::paint().
ScissorXY()
void GDClass::ScissorXY (uint16_t x, uint16_t y)
Definition at line 817 of file GD3.cpp.
References ft8xx_model.
Referenced by Poly::paint().
seed()
void GDClass::seed (uint16_t n)
Definition at line 519 of file GD3.cpp.
self_calibrate()
void GDClass::self_calibrate (void)
Definition at line 482 of file GD3.cpp.
References GDTransport::flush(), h, OPT_CENTERX, and w.
StencilFunc()
void GDClass::StencilFunc (byte func, byte ref, byte mask)
Definition at line 823 of file GD3.cpp.
Referenced by Poly::begin(), and Poly::finish().
StencilMask()
void GDClass::StencilMask (byte mask)
Definition at line 826 of file GD3.cpp.
StencilOp()
void GDClass::StencilOp (byte sfail, byte spass)
Definition at line 829 of file GD3.cpp.
Referenced by Poly::begin().
storage()
void GDClass::storage (void)
Definition at line 476 of file GD3.cpp.
References GDTransport::__end(), GDTransport::resume(), and SD_PIN.
swap()
void GDClass::swap (void)
Definition at line 183 of file GD3.cpp.
References GDTransport::flush(), GDTransport::rd32(), REG_CLOCK, and GDTransport::swap().
Referenced by FT8XXDriver::swapDisplay().
Tag()
void GDClass::Tag (byte s)
Definition at line 835 of file GD3.cpp.
TagMask()
void GDClass::TagMask (byte mask)
Definition at line 832 of file GD3.cpp.
tune()
void GDClass::tune (void)
Definition at line 207 of file GD3.cpp.
References LOW_FREQ_BOUND, REG_FREQUENCY, REG_TRIM, GDTransport::wr(), and GDTransport::wr32().
Vertex2f()
void GDClass::Vertex2f (int16_t x, int16_t y)
Definition at line 838 of file GD3.cpp.
Referenced by circle(), UIPrimitives::CircleFlat(), UIPrimitives::CircleOutline(), UIPrimitives::CircleRaised(), UIPrimitives::CircleSunken(), Compass::Draw(), FT8XXDriver::drawLine(), UIPrimitives::DrawLine(), UIPrimitives::DrawPoint(), FT8XXDriver::drawRoundRect(), FT8XXDriver::fillRoundRect(), Poly::finish(), UIPrimitives::RaisedPanel(), and UIPrimitives::SunkenPanel().
Vertex2ii()
void GDClass::Vertex2ii (uint16_t x, uint16_t y, byte handle = 0, byte cell = 0)
Definition at line 843 of file GD3.cpp.
Referenced by DropDownList::Draw(), IconButton::Draw(), FT8XXDriver::drawCircle(), FT8XXDriver::drawPixel(), FT8XXDriver::drawRect(), FT8XXDriver::drawTriangle(), FT8XXDriver::fillCircle(), and FT8XXDriver::fillRect().
VertexFormat()
void GDClass::VertexFormat (byte frac)
Definition at line 855 of file GD3.cpp.
Referenced by UIPrimitives::CircleRaised(), UIPrimitives::CircleSunken(), UIPrimitives::RaisedPanel(), and UIPrimitives::SunkenPanel().
VertexTranslateX()
void GDClass::VertexTranslateX (uint32_t x)
Definition at line 867 of file GD3.cpp.
VertexTranslateY()
void GDClass::VertexTranslateY (uint32_t y)
Definition at line 870 of file GD3.cpp.
wr()
void GDClass::wr (uint32_t addr, uint8_t v)
Definition at line 1215 of file GD3.cpp.
References GDTransport::wr().
Referenced by FT8XXDriver::backlightOn(), FT8XXDriver::backlightPower(), FT8XXDriver::displayPower(), sample(), and FT8XXDriver::touchEnable().
wr16()
void GDClass::wr16 (uint32_t addr, uint16_t v)
Definition at line 1221 of file GD3.cpp.
References GDTransport::wr16().
Referenced by sample(), and FT8XXDriver::writeReg().
wr32()
void GDClass::wr32 (uint32_t addr, uint32_t v)
Definition at line 1227 of file GD3.cpp.
References GDTransport::wr32().
Referenced by begin(), and sample().
wr_n()
void GDClass::wr_n (uint32_t addr, byte * src, uint32_t n)
Definition at line 1230 of file GD3.cpp.
References GDTransport::cmdbyte(), and GDTransport::wr_n().
Member Data Documentation
__dummy_1
uint16_t GDClass::__dummy_1
Definition at line 471 of file GD3.h.
h
int GDClass::h
Definition at line 441 of file GD3.h.
Referenced by self_calibrate().
inputs
struct { ... } GDClass::inputs
Referenced by FT8XXDriver::touched(), and FT8XXDriver::touchRead().
ptag
uint8_t GDClass::ptag
Definition at line 477 of file GD3.h.
rz
uint16_t GDClass::rz
Definition at line 470 of file GD3.h.
SD
sdcard GDClass::SD
Definition at line 611 of file GD3.h.
Referenced by Reader::begin(), Reader::fetch512(), Reader::nextcluster(), Reader::nextcluster2(), Reader::readsector(), Reader::seek(), Reader::skipcluster(), and Reader::skipsector().
tag
uint8_t GDClass::tag
Definition at line 476 of file GD3.h.
tag_x
int16_t GDClass::tag_x
Definition at line 475 of file GD3.h.
tag_y
int16_t GDClass::tag_y
Definition at line 474 of file GD3.h.
track_tag
uint16_t GDClass::track_tag
Definition at line 468 of file GD3.h.
track_val
uint16_t GDClass::track_val
Definition at line 469 of file GD3.h.
w
int GDClass::w
Definition at line 441 of file GD3.h.
Referenced by self_calibrate().
x
int16_t GDClass::x
Definition at line 473 of file GD3.h.
Referenced by FT8XXDriver::touched(), and FT8XXDriver::touchRead().
y
int16_t GDClass::y
Definition at line 472 of file GD3.h.
Referenced by FT8XXDriver::touchRead().
The documentation for this class was generated from the following files:
External/GD3/GD3.h
External/GD3/GD3.cpp