uWindows: UIRadioButton Class Reference
UIRadioButton Class Reference
#include <UIRadioButton.h>
Public Member Functions
UIRadioButton (DriverBase &tft, Rectangle location, std::string text, bool checked, eUITextFont textFont, tColor textColor, uint8_t textScale, tColor controlColor, tColor checkColor, bool is3D=true, bool textToRight=true, std::string elementName="")
void Update () override
void SetText (std::string text)
void SetChecked (bool checked)
bool IsChecked ()
sTouchResponse ProcessTouch (Point touchPoint) override
Public Member Functions inherited from UIElement
UIElement (DriverBase &tft, Rectangle location, std::string elementName, eElementType elementType)
UIElement (const UIElement &other)
eElementType GetElementType ()
bool UpdatePending ()
int getElementID ()
bool isEnabled ()
void setEnabled (bool val)
void Invalidate ()
Rectangle GetLocation ()
Rectangle SetLocation (Rectangle newLoc)
std::vector< UIElement * > GetChildElements ()
virtual void AddChildElement (UIElement *element)
If a child UI element overrides this, it must call this as well
void SetParent (UIElement *element)
std::string getElementName ()
void UpdateChildren ()
~UIElement ()
Private Attributes
std::string buttonText
bool isChecked
bool is3D
bool textRight
eUITextFont textFont
uint32_t textColor
uint32_t controlColor
uint32_t checkColor
Rectangle * checkRect = NULL
Additional Inherited Members
Protected Attributes inherited from UIElement
std::string elementName
Rectangle location
UIElement * parentElement
bool updatePending
bool enabled
uint32_t elementID
DriverBase & tft
eElementType elementType
std::vector< UIElement * > childElements
Detailed Description
Definition at line 13 of file UIRadioButton.h.
Constructor & Destructor Documentation
UIRadioButton()
UIRadioButton::UIRadioButton (DriverBase & tft, Rectangle location, std::string text, bool checked, eUITextFont textFont, tColor textColor, uint8_t textScale, tColor controlColor, tColor checkColor, bool is3D = true, bool textToRight = true, std::string elementName = "")
Definition at line 3 of file UIRadioButton.cpp.
References Logger::BoolToStr(), buttonText, checkColor, controlColor, is3D, isChecked, textColor, textFont, textRight, Logger::Trace(), Rectangle::x1, Rectangle::x2, Rectangle::y1, and Rectangle::y2.
Member Function Documentation
IsChecked()
bool UIRadioButton::IsChecked () inline
Definition at line 22 of file UIRadioButton.h.
References isChecked, and ProcessTouch().
Referenced by UIRadioGroup::AddRadioButton().
ProcessTouch()
sTouchResponse UIRadioButton::ProcessTouch (Point touchPoint) override virtual
Implements UIElement.
Definition at line 72 of file UIRadioButton.cpp.
References Rectangle::contains(), ControlTouched, UIElement::elementID, UIElement::Invalidate(), isChecked, UIElement::location, and NoOp.
Referenced by IsChecked().
SetChecked()
void UIRadioButton::SetChecked (bool checked)
Definition at line 64 of file UIRadioButton.cpp.
References UIElement::Invalidate(), and isChecked.
Referenced by UIRadioGroup::AddRadioButton().
SetText()
void UIRadioButton::SetText (std::string text)
Definition at line 56 of file UIRadioButton.cpp.
References buttonText, and UIElement::Invalidate().
Update()
void UIRadioButton::Update () override virtual
Implements UIElement.
Definition at line 37 of file UIRadioButton.cpp.
References buttonText, checkColor, controlColor, RadioButton::Draw(), is3D, isChecked, UIElement::location, DriverBase::setTextSize(), textColor, textFont, textRight, UIElement::tft, Logger::Trace(), UIElement::updatePending, Rectangle::x1, and Rectangle::y1.
Member Data Documentation
buttonText
std::string UIRadioButton::buttonText private
Definition at line 29 of file UIRadioButton.h.
Referenced by SetText(), UIRadioButton(), and Update().
checkColor
uint32_t UIRadioButton::checkColor private
Definition at line 37 of file UIRadioButton.h.
Referenced by UIRadioButton(), and Update().
checkRect
Rectangle* UIRadioButton::checkRect = NULL private
Definition at line 39 of file UIRadioButton.h.
controlColor
uint32_t UIRadioButton::controlColor private
Definition at line 37 of file UIRadioButton.h.
Referenced by UIRadioButton(), and Update().
is3D
bool UIRadioButton::is3D private
Definition at line 30 of file UIRadioButton.h.
Referenced by UIRadioButton(), and Update().
isChecked
bool UIRadioButton::isChecked private
Definition at line 30 of file UIRadioButton.h.
Referenced by IsChecked(), ProcessTouch(), SetChecked(), UIRadioButton(), and Update().
textColor
uint32_t UIRadioButton::textColor private
Definition at line 37 of file UIRadioButton.h.
Referenced by UIRadioButton(), and Update().
textFont
eUITextFont UIRadioButton::textFont private
Definition at line 31 of file UIRadioButton.h.
Referenced by UIRadioButton(), and Update().
textRight
bool UIRadioButton::textRight private
Definition at line 30 of file UIRadioButton.h.
Referenced by UIRadioButton(), and Update().
The documentation for this class was generated from the following files:
UIElements/UIRadioButton.h
UIElements/UIRadioButton.cpp