uWindows: Compass Class Reference
Compass Class Reference
#include <Compass.h>
Static Public Member Functions
static Rectangle Draw (DriverBase &tft, Rectangle location, float direction, tColor controlColor, tColor pointerColor, eUITextFont controlFont, bool showDegrees, eUITextFont degreeFont, tColor degreeColor, tColor degreeBGColor, bool showNSEW=true, tColor textColor=Color::White)
Private Types
enum eAngle {
N = 0, E = 1, S = 2, W = 3,
NE = 4, SE = 5, SW = 6, NW = 7
}
Static Private Member Functions
static void DrawCompassTriangle (DriverBase &tft, eAngle angle, Point centerPoint, uint16_t length, uint16_t centerRadius, tColor color, tColor color2)
static uint16_t angleMath (uint16_t startAngle, int adjustment)
static double degrees_to_radian (double deg)
Detailed Description
Definition at line 12 of file Compass.h.
Member Enumeration Documentation
eAngle
enum Compass::eAngle private
Enumerator
N
E
S
W
NE
SE
SW
NW
Definition at line 20 of file Compass.h.
Member Function Documentation
angleMath()
uint16_t Compass::angleMath (uint16_t startAngle, int adjustment) static private
Definition at line 151 of file Compass.cpp.
Referenced by Draw(), and DrawCompassTriangle().
degrees_to_radian()
static double Compass::degrees_to_radian (double deg) inline static private
Definition at line 34 of file Compass.h.
Referenced by Draw(), and DrawCompassTriangle().
Draw()
Rectangle Compass::Draw (DriverBase & tft, Rectangle location, float direction, tColor controlColor, tColor pointerColor, eUITextFont controlFont, bool showDegrees, eUITextFont degreeFont, tColor degreeColor, tColor degreeBGColor, bool showNSEW = true, tColor textColor = Color::White) static
Definition at line 5 of file Compass.cpp.
References angleMath(), GDClass::Begin(), Rectangle::center(), UIPrimitives::CircleFlat(), GDClass::ColorRGB(), Color::ContrastingColor(), degrees_to_radian(), DrawCompassTriangle(), GD, FontHelper::GetTextRect(), Rectangle::height, GDClass::LineWidth(), UIPrimitives::Polygon(), RECTS, tColor, UIPrimitives::Text(), Logger::Trace(), GDClass::Vertex2f(), Rectangle::width, Point::x, Rectangle::x1, Rectangle::x2, Point::y, Rectangle::y1, and Rectangle::y2.
DrawCompassTriangle()
void Compass::DrawCompassTriangle (DriverBase & tft, eAngle angle, Point centerPoint, uint16_t length, uint16_t centerRadius, tColor color, tColor color2) static private
Definition at line 83 of file Compass.cpp.
References angleMath(), degrees_to_radian(), UIPrimitives::Polygon(), Point::x, and Point::y.
Referenced by Draw().
The documentation for this class was generated from the following files:
UIElements/ControlDisplay/Compass.h
UIElements/ControlDisplay/Compass.cpp