uWindows: UIButton Class Reference
UIButton Class Reference
#include <UIButton.h>
Public Member Functions
UIButton (DriverBase &tft, Rectangle location, std::string buttonText, eUITextFont font, tColor textColor, uint8_t textScale, tColor buttonBGColor, uint8_t cornerRadius=4, bool is3D=true, bool raised=true, std::string elementName="", uint8_t alpha=255, eVertAlign textVertAlign=eVertAlign::Middle)
sTouchResponse ProcessTouch (Point touchPoint) override
void Update () override
void SetButtonText (std::string txt)
void SetVerticalAlignment (eVertAlign align)
Public Member Functions inherited from UIElement
UIElement (DriverBase &tft, Rectangle location, std::string elementName, eElementType elementType)
UIElement (const UIElement &other)
eElementType GetElementType ()
bool UpdatePending ()
int getElementID ()
bool isEnabled ()
void setEnabled (bool val)
void Invalidate ()
Rectangle GetLocation ()
Rectangle SetLocation (Rectangle newLoc)
std::vector< UIElement * > GetChildElements ()
virtual void AddChildElement (UIElement *element)
If a child UI element overrides this, it must call this as well
void SetParent (UIElement *element)
std::string getElementName ()
void UpdateChildren ()
~UIElement ()
Additional Inherited Members
Protected Attributes inherited from UIElement
std::string elementName
Rectangle location
UIElement * parentElement
bool updatePending
bool enabled
uint32_t elementID
DriverBase & tft
eElementType elementType
std::vector< UIElement * > childElements
Detailed Description
Definition at line 14 of file UIButton.h.
Constructor & Destructor Documentation
UIButton()
UIButton::UIButton (DriverBase & tft, Rectangle location, std::string buttonText, eUITextFont font, tColor textColor, uint8_t textScale, tColor buttonBGColor, uint8_t cornerRadius = 4, bool is3D = true, bool raised = true, std::string elementName = "", uint8_t alpha = 255, eVertAlign textVertAlign = eVertAlign::Middle)
Definition at line 5 of file UIButton.cpp.
References Logger::Trace(), Rectangle::x1, Rectangle::x2, Rectangle::y1, and Rectangle::y2.
Member Function Documentation
ProcessTouch()
sTouchResponse UIButton::ProcessTouch (Point touchPoint) override virtual
Implements UIElement.
Definition at line 33 of file UIButton.cpp.
References ControlTouched, UIElement::elementID, UIElement::enabled, and NoOp.
SetButtonText()
void UIButton::SetButtonText (std::string txt)
Definition at line 40 of file UIButton.cpp.
References UIElement::Invalidate().
SetVerticalAlignment()
void UIButton::SetVerticalAlignment (eVertAlign align) inline
Definition at line 25 of file UIButton.h.
References Middle, and tColor.
Update()
void UIButton::Update () override virtual
Implements UIElement.
Definition at line 49 of file UIButton.cpp.
References Button::Draw(), Rectangle::height, UIElement::location, UIElement::tft, Logger::Trace(), UIElement::UpdateChildren(), UIElement::updatePending, Rectangle::width, Rectangle::x1, and Rectangle::y1.
The documentation for this class was generated from the following files:
UIElements/UIButton.h
UIElements/UIButton.cpp