uWindows: Streamer Class Reference
Streamer Class Reference
#include <GD3.h>
Public Member Functions
void begin (const char *rawsamples, uint16_t freq=44100, byte format=ADPCM_SAMPLES, uint32_t _base=(0x40000UL - 8192), uint16_t size=8192)
int feed ()
void progress (uint16_t &val, uint16_t &range)
Detailed Description
Definition at line 1084 of file GD3.h.
Member Function Documentation
begin()
void Streamer::begin (const char * rawsamples, uint16_t freq = 44100, byte format = ADPCM_SAMPLES, uint32_t _base = (0x40000UL - 8192), uint16_t size = 8192) inline
Definition at line 1086 of file GD3.h.
References GDClass::__end(), GDClass::resume(), and GDClass::sample().
feed()
int Streamer::feed () inline
Definition at line 1103 of file GD3.h.
References GDClass::__end(), GDClass::cmd_memwrite(), GDClass::copyram(), GDClass::rd32(), REG_PLAYBACK_READPTR, and GDClass::resume().
progress()
void Streamer::progress (uint16_t & val, uint16_t & range) inline
Definition at line 1124 of file GD3.h.
The documentation for this class was generated from the following file:
External/GD3/GD3.h