uWindows: FatVolume Class Reference
FatVolume Class Reference
Access FAT16 and FAT32 volumes on raw file devices.
#include <FatVolume.h>
Public Member Functions
FatVolume ()
uint8_t blocksPerCluster () const
uint32_t blocksPerFat () const
cache_t * cacheClear ()
uint32_t clusterCount () const
uint8_t clusterSizeShift () const
uint32_t dataStartBlock () const
uint8_t fatCount ()
uint32_t fatStartBlock () const
uint8_t fatType () const
int32_t freeClusterCount ()
bool init ()
bool init (uint8_t part)
uint16_t rootDirEntryCount () const
uint32_t rootDirStart () const
uint32_t volumeBlockCount () const
bool wipe (print_t *pr=0)
int8_t dbgFat (uint32_t n, uint32_t *v)
Friends
class FatCache
class FatFile
class FatFileSystem
Detailed Description
Access FAT16 and FAT32 volumes on raw file devices.
Definition at line 158 of file FatVolume.h.
Constructor & Destructor Documentation
FatVolume()
FatVolume::FatVolume () inline
Create an instance of FatVolume
Definition at line 162 of file FatVolume.h.
Member Function Documentation
blocksPerCluster()
uint8_t FatVolume::blocksPerCluster () const inline
Returns
The volume's cluster size in blocks.
Definition at line 165 of file FatVolume.h.
Referenced by FatFile::contiguousRange(), FatFile::dirSize(), FatFile::read(), and FatFile::write().
blocksPerFat()
uint32_t FatVolume::blocksPerFat () const inline
Returns
The number of blocks in one FAT.
Definition at line 169 of file FatVolume.h.
Referenced by FatCache::sync().
cacheClear()
cache_t* FatVolume::cacheClear () inline
Clear the cache and returns a pointer to the cache. Not for normal apps.
Returns
A pointer to the cache buffer or zero if an error occurs.
Definition at line 175 of file FatVolume.h.
clusterCount()
uint32_t FatVolume::clusterCount () const inline
Returns
The total number of clusters in the volume.
Definition at line 183 of file FatVolume.h.
clusterSizeShift()
uint8_t FatVolume::clusterSizeShift () const inline
Returns
The shift count required to multiply by blocksPerCluster.
Definition at line 187 of file FatVolume.h.
Referenced by FatFile::createContiguous(), and FatFile::seekSet().
dataStartBlock()
uint32_t FatVolume::dataStartBlock () const inline
Returns
The logical block number for the start of file data.
Definition at line 191 of file FatVolume.h.
dbgFat()
int8_t FatVolume::dbgFat (uint32_t n, uint32_t * v) inline
Debug access to FAT table
Parameters
[in] n cluster number.
[out] v value of entry
Returns
true for success or false for failure
Definition at line 255 of file FatVolume.h.
fatCount()
uint8_t FatVolume::fatCount () inline
Returns
The number of File Allocation Tables.
Definition at line 195 of file FatVolume.h.
fatStartBlock()
uint32_t FatVolume::fatStartBlock () const inline
Returns
The logical block number for the start of the first FAT.
Definition at line 199 of file FatVolume.h.
fatType()
uint8_t FatVolume::fatType () const inline
Returns
The FAT type of the volume. Values are 12, 16 or 32.
Definition at line 203 of file FatVolume.h.
Referenced by FatFile::openRoot().
freeClusterCount()
int32_t FatVolume::freeClusterCount ()
Volume free space in clusters.
Returns
Count of free clusters for success or -1 if an error occurs.
Definition at line 359 of file FatVolume.cpp.
References FatCache::CACHE_FOR_READ, DBG_FAIL_MACRO, FAT12_SUPPORT, cache_t::fat16, and cache_t::fat32.
init() [1/2]
bool FatVolume::init () inline
Initialize a FAT volume. Try partition one first then try super floppy format.
Returns
The value true is returned for success and the value false is returned for failure.
Definition at line 217 of file FatVolume.h.
References part.
Referenced by FatFileSystem::begin().
init() [2/2]
bool FatVolume::init (uint8_t part)
Initialize a FAT volume.
Parameters
[in] part The partition to be used. Legal values for part are 1-4 to use the corresponding partition on a device formatted with a MBR, Master Boot Record, or zero if the device is formatted as a super floppy with the FAT boot sector in block zero.
Returns
The value true is returned for success and the value false is returned for failure.
Definition at line 421 of file FatVolume.cpp.
References FatCache::CACHE_FOR_READ, and DBG_FAIL_MACRO.
rootDirEntryCount()
uint16_t FatVolume::rootDirEntryCount () const inline
Returns
The number of entries in the root directory for FAT16 volumes.
Definition at line 232 of file FatVolume.h.
Referenced by FatFile::dirSize().
rootDirStart()
uint32_t FatVolume::rootDirStart () const inline
Returns
The logical block number for the start of the root directory on FAT16 volumes or the first cluster number on FAT32 volumes.
Definition at line 237 of file FatVolume.h.
Referenced by FatFile::dirSize(), FatFile::read(), and FatFile::seekSet().
volumeBlockCount()
uint32_t FatVolume::volumeBlockCount () const inline
Returns
The number of blocks in the volume
Definition at line 241 of file FatVolume.h.
wipe()
bool FatVolume::wipe (print_t * pr = 0)
Wipe all data from the volume.
Parameters
[in] pr print stream for status dots.
Returns
true for success else false.
Definition at line 521 of file FatVolume.cpp.
References cache_t::data, DBG_FAIL_MACRO, FAT12_SUPPORT, cache_t::fat16, cache_t::fat32, FatCache::lbn(), and CharWriter::write().
Referenced by FatFileSystem::wipe().
Friends And Related Function Documentation
FatCache
friend class FatCache friend
Definition at line 261 of file FatVolume.h.
FatFile
friend class FatFile friend
Definition at line 262 of file FatVolume.h.
FatFileSystem
friend class FatFileSystem friend
Definition at line 263 of file FatVolume.h.
The documentation for this class was generated from the following files:
External/SDFat/FatLib/FatVolume.h
External/SDFat/FatLib/FatVolume.cpp