uWindows: Window Class Reference
Window Class Reference
#include <Window.h>
Static Public Member Functions
static Rectangle Draw (DriverBase &tft, uint16_t x, uint16_t y, uint16_t width, uint16_t height, tColor titleBarBGColor, tColor titleBarTextColor, tColor controlColor, tColor borderColor, tColor windowBGColor, std::string titleText, eUITextFont font, bool hasChrome, bool hasTitleBar, bool hasCloseIcon, bool is3D=true, uint8_t cornerRadius=4, uint8_t alpha=255)
Detailed Description
Definition at line 14 of file Window.h.
Member Function Documentation
Draw()
Rectangle Window::Draw (DriverBase & tft, uint16_t x, uint16_t y, uint16_t width, uint16_t height, tColor titleBarBGColor, tColor titleBarTextColor, tColor controlColor, tColor borderColor, tColor windowBGColor, std::string titleText, eUITextFont font, bool hasChrome, bool hasTitleBar, bool hasCloseIcon, bool is3D = true, uint8_t cornerRadius = 4, uint8_t alpha = 255) static
Definition at line 3 of file Window.cpp.
References Rectangle::center(), DriverBase::drawLine(), DriverBase::drawRect(), UIPrimitives::FlatPanel(), FontHelper::GetTextRect(), Rectangle::height, UIPrimitives::RaisedPanel(), UIPrimitives::Text(), Rectangle::width, Point::x, Rectangle::x2, Point::y, and Rectangle::y1.
The documentation for this class was generated from the following files:
UIElements/ControlDisplay/Window.h
UIElements/ControlDisplay/Window.cpp