uWindows: UIElement Class Reference
UIElement Class Reference abstract
#include <UIElement.h>
Public Member Functions
UIElement (DriverBase &tft, Rectangle location, std::string elementName, eElementType elementType)
UIElement (const UIElement &other)
virtual void Update ()=0
eElementType GetElementType ()
bool UpdatePending ()
int getElementID ()
bool isEnabled ()
void setEnabled (bool val)
void Invalidate ()
Rectangle GetLocation ()
Rectangle SetLocation (Rectangle newLoc)
std::vector< UIElement * > GetChildElements ()
virtual void AddChildElement (UIElement *element)
If a child UI element overrides this, it must call this as well
void SetParent (UIElement *element)
virtual sTouchResponse ProcessTouch (Point touchPoint)=0
std::string getElementName ()
void UpdateChildren ()
~UIElement ()
Protected Attributes
std::string elementName
Rectangle location
UIElement * parentElement
bool updatePending
bool enabled
uint32_t elementID
DriverBase & tft
eElementType elementType
std::vector< UIElement * > childElements
Detailed Description
Definition at line 60 of file UIElement.h.
Constructor & Destructor Documentation
UIElement() [1/2]
UIElement::UIElement (DriverBase & tft, Rectangle location, std::string elementName, eElementType elementType) inline
Definition at line 63 of file UIElement.h.
References Logger::Trace(), Rectangle::x1, Rectangle::x2, Rectangle::y1, and Rectangle::y2.
Referenced by UIWindow::UIWindow().
UIElement() [2/2]
UIElement::UIElement (const UIElement & other) inline
Definition at line 80 of file UIElement.h.
References location, Rectangle::x1, Rectangle::x2, Rectangle::y1, and Rectangle::y2.
~UIElement()
UIElement::~UIElement () inline
Definition at line 175 of file UIElement.h.
Member Function Documentation
AddChildElement()
virtual void UIElement::AddChildElement (UIElement * element) inline virtual
If a child UI element overrides this, it must call this as well
Parameters
element The element.
Reimplemented in UIWindow.
Definition at line 143 of file UIElement.h.
References location, and parentElement.
Referenced by UIRadioGroup::AddRadioButton(), HomeScreen::HomeScreen(), and HomeScreen::~HomeScreen().
GetChildElements()
std::vector<UIElement *> UIElement::GetChildElements () inline
Definition at line 133 of file UIElement.h.
Referenced by WindowManager::DeleteElement().
getElementID()
int UIElement::getElementID () inline
Definition at line 101 of file UIElement.h.
Referenced by WindowManager::DeleteElement(), UIRadioGroup::ProcessTouch(), and WindowManager::RegisterElement().
getElementName()
std::string UIElement::getElementName () inline
Definition at line 160 of file UIElement.h.
GetElementType()
eElementType UIElement::GetElementType () inline
Definition at line 92 of file UIElement.h.
Referenced by UIRadioGroup::AddRadioButton(), UIRadioGroup::GetSelectedButton(), UIRadioGroup::ProcessTouch(), and UIRadioGroup::SetSelectedButton().
GetLocation()
Rectangle UIElement::GetLocation () inline
Definition at line 123 of file UIElement.h.
Referenced by UIWindow::AddChildElement(), UIRadioGroup::AddRadioButton(), and UIRadioGroup::ProcessTouch().
Invalidate()
void UIElement::Invalidate () inline
Definition at line 113 of file UIElement.h.
References Invalidate().
Referenced by UIElementGraph::AddValue(), Invalidate(), UICheckBox::ProcessTouch(), UIRadioButton::ProcessTouch(), WindowManager::RegisterElement(), UIButton::SetButtonText(), UIRadioButton::SetChecked(), UIWindow::SetCloseIcon(), UIWindow::SetHasChrome(), UIWindow::SetModal(), UIRadioButton::SetText(), UIWindow::SetTitleBar(), UIWindow::SetWindowTitle(), and UIElementGraph::UIElementGraph().
isEnabled()
bool UIElement::isEnabled () inline
Definition at line 105 of file UIElement.h.
ProcessTouch()
virtual sTouchResponse UIElement::ProcessTouch (Point touchPoint) pure virtual
Implemented in UIWindow, UIRadioGroup, UIElementGraph, UIRadioButton, UIButton, UICheckBox, HomeScreen, SettingsButton, and ScreenSaver.
setEnabled()
void UIElement::setEnabled (bool val) inline
Definition at line 109 of file UIElement.h.
SetLocation()
Rectangle UIElement::SetLocation (Rectangle newLoc) inline
Definition at line 128 of file UIElement.h.
Referenced by UIWindow::AddChildElement().
SetParent()
void UIElement::SetParent (UIElement * element) inline
Definition at line 153 of file UIElement.h.
Referenced by UIWindow::AddChildElement().
Update()
virtual void UIElement::Update () pure virtual
Implemented in UIElementGraph, UIRadioGroup, UIButton, UICheckBox, UIWindow, UIRadioButton, HomeScreen, SettingsButton, and ScreenSaver.
Referenced by UICheckBox::Update(), UIRadioGroup::Update(), and UpdateChildren().
UpdateChildren()
void UIElement::UpdateChildren () inline
Definition at line 165 of file UIElement.h.
References Update(), and UpdatePending().
Referenced by HomeScreen::Update(), and UIButton::Update().
UpdatePending()
bool UIElement::UpdatePending () inline
Definition at line 97 of file UIElement.h.
Referenced by UpdateChildren().
Member Data Documentation
childElements
std::vector<UIElement *> UIElement::childElements protected
Definition at line 194 of file UIElement.h.
Referenced by UIWindow::AddChildElement(), UIRadioGroup::AddRadioButton(), UIRadioGroup::GetSelectedButton(), UIRadioGroup::ProcessTouch(), UIRadioGroup::SetSelectedButton(), and UIWindow::Update().
elementID
uint32_t UIElement::elementID protected
Definition at line 191 of file UIElement.h.
Referenced by ScreenSaver::ProcessTouch(), SettingsButton::ProcessTouch(), UICheckBox::ProcessTouch(), UIButton::ProcessTouch(), UIRadioButton::ProcessTouch(), UIElementGraph::ProcessTouch(), and UIWindow::ProcessTouch().
elementName
std::string UIElement::elementName protected
Definition at line 186 of file UIElement.h.
elementType
eElementType UIElement::elementType protected
Definition at line 193 of file UIElement.h.
enabled
bool UIElement::enabled protected
Definition at line 190 of file UIElement.h.
Referenced by UICheckBox::ProcessTouch(), and UIButton::ProcessTouch().
location
Rectangle UIElement::location protected
Definition at line 188 of file UIElement.h.
Referenced by AddChildElement(), UIRadioGroup::AddRadioButton(), HomeScreen::HomeScreen(), SettingsButton::ProcessTouch(), UICheckBox::ProcessTouch(), UIRadioButton::ProcessTouch(), UIElement(), UIWindow::UIWindow(), SettingsButton::Update(), UIRadioButton::Update(), UICheckBox::Update(), UIButton::Update(), and UIElementGraph::Update().
parentElement
UIElement* UIElement::parentElement protected
Definition at line 189 of file UIElement.h.
Referenced by AddChildElement().
tft
DriverBase& UIElement::tft protected
Definition at line 192 of file UIElement.h.
Referenced by ScreenSaver::ScreenSaver(), UIWindow::UIWindow(), SettingsButton::Update(), UIRadioButton::Update(), UIButton::Update(), UICheckBox::Update(), UIElementGraph::Update(), and HomeScreen::~HomeScreen().
updatePending
bool UIElement::updatePending protected
Definition at line 190 of file UIElement.h.
Referenced by UIWindow::SetModal(), SettingsButton::Update(), UIRadioButton::Update(), UIWindow::Update(), UICheckBox::Update(), UIButton::Update(), and UIElementGraph::Update().
The documentation for this class was generated from the following file:
UIElements/UIElement.h