uWindows: BatteryIcon Class Reference
BatteryIcon Class Reference
#include <BatteryIcon.h>
Static Public Member Functions
static Rectangle Draw (DriverBase &tft, Rectangle location, uint8_t pctCharged, std::vector< tColor > barColors, bool showPct=true, tColor borderColor=Color::White, tColor bgColor=Color::Black, eUITextFont pctFont=eUITextFont::AntiAliasFont27, tColor pctTextColor=Color::White, bool rightAlignment=true)
Detailed Description
Definition at line 14 of file BatteryIcon.h.
Member Function Documentation
Draw()
Rectangle BatteryIcon::Draw (DriverBase & tft, Rectangle location, uint8_t pctCharged, std::vector< tColor > barColors, bool showPct = true, tColor borderColor = Color::White, tColor bgColor = Color::Black, eUITextFont pctFont = eUITextFont::AntiAliasFont27, tColor pctTextColor = Color::White, bool rightAlignment = true) static
Definition at line 4 of file BatteryIcon.cpp.
References Rectangle::center(), DriverBase::fillRect(), DriverBase::fillRoundRect(), Rectangle::height, UIPrimitives::Text(), Rectangle::update(), Rectangle::width, Point::x, Rectangle::x1, Rectangle::x2, Point::y, Rectangle::y1, and Rectangle::y2.
The documentation for this class was generated from the following files:
UIElements/ControlDisplay/BatteryIcon.h
UIElements/ControlDisplay/BatteryIcon.cpp