uWindows: DriverBase Class Reference
DriverBase Class Reference abstract
#include <DriverBase.h>
Public Member Functions
DriverBase (uint16_t width, uint16_t height, eDriverType driverType)
virtual void Init (uint16_t width, uint16_t height, uint8_t cs=10, uint8_t rst=9)
virtual void drawPixel (int16_t x, int16_t y, uint32_t color)=0
virtual void drawLine (int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint32_t color)=0
virtual void setRotation (eDisplayRotation rotation)=0
eDisplayRotation getRotation ()
bool isLandscape ()
virtual void invertDisplay ()=0
virtual void fillRect (int16_t x, int16_t y, int16_t w, int16_t h, uint32_t color)=0
virtual void fillScreen (uint32_t color)=0
virtual void drawRect (int16_t x, int16_t y, int16_t w, int16_t h, uint32_t color)=0
virtual void drawCircle (int16_t x0, int16_t y0, int16_t r, uint32_t color)=0
virtual void fillCircle (int16_t x0, int16_t y0, int16_t r, uint32_t color)=0
virtual void drawTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint32_t color)=0
virtual void fillTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint32_t color)=0
virtual void drawRoundRect (int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint32_t color)=0
virtual void fillRoundRect (int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint32_t color)=0
virtual void drawChar (int16_t x, int16_t y, unsigned char c, uint32_t color, uint16_t bg, uint8_t size)=0
virtual void setCursor (int16_t x, int16_t y)=0
virtual void setTextColor (uint32_t color)=0
virtual void setTextColor (uint32_t color, uint32_t bgColor)=0
virtual void setTextSize (uint8_t s)=0
virtual void getTextBounds (std::string string, int16_t x, int16_t y, int16_t *x1, int16_t *y1, uint16_t *w, uint16_t *h)=0
virtual void drawEllipse (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint32_t color)=0
virtual void fillEllipse (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint32_t color)=0
virtual void drawCurve (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint8_t curvePart, uint32_t color)=0
virtual void fillCurve (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint8_t curvePart, uint32_t color)=0
virtual void softReset ()=0
virtual void displayPower (bool powerMode)=0
virtual void displaySleep (bool sleepModeOn)=0
virtual void textMode ()=0
virtual void setTextCursor (uint16_t x, uint16_t y)=0
virtual void textTransparent (uint32_t foreColor)=0
virtual void textWrite (std::string text)=0
virtual void textWriteLn (std::string text)=0
virtual void graphicsMode ()=0
virtual void setXY (uint16_t x, uint16_t y)=0
virtual void pushPixels (uint32_t num, uint32_t color)=0
virtual void backlightOn (bool value)=0
virtual void backlightPower (uint8_t value)=0
virtual void touchEnable (bool value)=0
virtual bool touched ()=0
virtual bool touchRead (uint16_t *x, uint16_t *y)=0
virtual void writeReg (uint8_t reg, uint8_t val)=0
virtual uint8_t readReg (uint8_t reg)=0
virtual void writeData (uint8_t d)=0
virtual uint8_t readData ()=0
virtual void writeCommand (uint8_t d)=0
virtual uint8_t readStatus ()=0
virtual bool waitPoll (uint8_t r, uint8_t f)=0
virtual void fillQuad (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, int16_t x3, int16_t y3, tColor color, bool triangled=true)=0
uint16_t width ()
uint16_t height ()
virtual void textWrite (uint16_t x, uint16_t y, eUITextFont font, uint32_t textColor, uint16_t justification, std::string text)=0
uint16_t Color565 (uint8_t r, uint8_t g, uint8_t b)
uint16_t Color24To565 (int32_t color_)
uint16_t htmlTo565 (int32_t color_)
void Color565ToRGB (uint16_t color, uint8_t &r, uint8_t &g, uint8_t &b)
uint16_t colorInterpolation565 (uint16_t color1, uint16_t color2, uint16_t pos, uint16_t div)
uint16_t colorInterpolation565 (uint8_t r1, uint8_t g1, uint8_t b1, uint8_t r2, uint8_t g2, uint8_t b2, uint16_t pos, uint16_t div)
uint32_t getBackgroundColor ()
virtual void swapDisplay ()
virtual void colorA (uint8_t alpha)
virtual void clearScreen (uint32_t clearToColor=Color::Black)
Protected Attributes
eDriverType driverType
uint16_t tftWidth
uint16_t tftHeight
eDisplayRotation rotation = eDisplayRotation::Landscape
uint32_t backgroundColor
Detailed Description
Definition at line 33 of file DriverBase.h.
Constructor & Destructor Documentation
DriverBase()
DriverBase::DriverBase (uint16_t width, uint16_t height, eDriverType driverType) inline
Definition at line 36 of file DriverBase.h.
References drawLine(), drawPixel(), driverType, height(), Init(), rotation, setRotation(), tftHeight, tftWidth, and width().
Member Function Documentation
backlightOn()
virtual void DriverBase::backlightOn (bool value) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
backlightPower()
virtual void DriverBase::backlightPower (uint8_t value) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
clearScreen()
virtual void DriverBase::clearScreen (uint32_t clearToColor = Color::Black) virtual
Reimplemented in FT8XXDriver.
Referenced by getBackgroundColor(), and ScreenSaver::ScreenSaver().
Color24To565()
uint16_t DriverBase::Color24To565 (int32_t color_) inline
Definition at line 145 of file DriverBase.h.
Color565()
uint16_t DriverBase::Color565 (uint8_t r, uint8_t g, uint8_t b) inline
Definition at line 140 of file DriverBase.h.
Referenced by colorInterpolation565().
Color565ToRGB()
void DriverBase::Color565ToRGB (uint16_t color, uint8_t & r, uint8_t & g, uint8_t & b) inline
Definition at line 155 of file DriverBase.h.
Referenced by colorInterpolation565().
colorA()
virtual void DriverBase::colorA (uint8_t alpha) virtual
Reimplemented in FT8XXDriver.
Referenced by UIPrimitives::FlatPanel(), and getBackgroundColor().
colorInterpolation565() [1/2]
uint16_t DriverBase::colorInterpolation565 (uint16_t color1, uint16_t color2, uint16_t pos, uint16_t div) inline
Definition at line 160 of file DriverBase.h.
References Color565ToRGB().
colorInterpolation565() [2/2]
uint16_t DriverBase::colorInterpolation565 (uint8_t r1, uint8_t g1, uint8_t b1, uint8_t r2, uint8_t g2, uint8_t b2, uint16_t pos, uint16_t div) inline
Definition at line 174 of file DriverBase.h.
References backgroundColor, Color565(), and getBackgroundColor().
displayPower()
virtual void DriverBase::displayPower (bool powerMode) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
displaySleep()
virtual void DriverBase::displaySleep (bool sleepModeOn) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
drawChar()
virtual void DriverBase::drawChar (int16_t x, int16_t y, unsigned char c, uint32_t color, uint16_t bg, uint8_t size) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
drawCircle()
virtual void DriverBase::drawCircle (int16_t x0, int16_t y0, int16_t r, uint32_t color) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
drawCurve()
virtual void DriverBase::drawCurve (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint8_t curvePart, uint32_t color) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
drawEllipse()
virtual void DriverBase::drawEllipse (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint32_t color) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
drawLine()
virtual void DriverBase::drawLine (int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint32_t color) pure virtual
Implemented in FT8XXDriver.
Referenced by Window::Draw(), DriverBase(), and UIWindow::SetModal().
drawPixel()
virtual void DriverBase::drawPixel (int16_t x, int16_t y, uint32_t color) pure virtual
Implemented in FT8XXDriver.
Referenced by DriverBase().
drawRect()
virtual void DriverBase::drawRect (int16_t x, int16_t y, int16_t w, int16_t h, uint32_t color) pure virtual
Implemented in FT8XXDriver.
Referenced by Window::Draw(), isLandscape(), and UIWindow::SetModal().
drawRoundRect()
virtual void DriverBase::drawRoundRect (int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint32_t color) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape(), and UIWindow::SetModal().
drawTriangle()
virtual void DriverBase::drawTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint32_t color) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
fillCircle()
virtual void DriverBase::fillCircle (int16_t x0, int16_t y0, int16_t r, uint32_t color) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
fillCurve()
virtual void DriverBase::fillCurve (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint8_t curvePart, uint32_t color) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
fillEllipse()
virtual void DriverBase::fillEllipse (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint32_t color) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
fillQuad()
virtual void DriverBase::fillQuad (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, int16_t x3, int16_t y3, tColor color, bool triangled = true) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
fillRect()
virtual void DriverBase::fillRect (int16_t x, int16_t y, int16_t w, int16_t h, uint32_t color) pure virtual
Implemented in FT8XXDriver.
Referenced by UIPrimitives::FlatPanel(), isLandscape(), and UIWindow::SetModal().
fillRoundRect()
virtual void DriverBase::fillRoundRect (int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint32_t color) pure virtual
Implemented in FT8XXDriver.
Referenced by UIPrimitives::FlatPanel(), isLandscape(), and UIWindow::SetModal().
fillScreen()
virtual void DriverBase::fillScreen (uint32_t color) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
fillTriangle()
virtual void DriverBase::fillTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint32_t color) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
getBackgroundColor()
uint32_t DriverBase::getBackgroundColor () inline
Definition at line 192 of file DriverBase.h.
References backgroundColor, Color::Black, clearScreen(), colorA(), and swapDisplay().
Referenced by colorInterpolation565().
getRotation()
eDisplayRotation DriverBase::getRotation () inline
Definition at line 51 of file DriverBase.h.
References rotation.
getTextBounds()
virtual void DriverBase::getTextBounds (std::string string, int16_t x, int16_t y, int16_t * x1, int16_t * y1, uint16_t * w, uint16_t * h) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
graphicsMode()
virtual void DriverBase::graphicsMode () pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
height()
uint16_t DriverBase::height () inline
Definition at line 132 of file DriverBase.h.
References textWrite(), and tftHeight.
Referenced by UIWindow::AddChildElement(), UIPrimitives::CircleOutline(), DriverBase(), and FT8XXDriver::Init().
htmlTo565()
uint16_t DriverBase::htmlTo565 (int32_t color_) inline
Definition at line 150 of file DriverBase.h.
Init()
virtual void DriverBase::Init (uint16_t width, uint16_t height, uint8_t cs = 10, uint8_t rst = 9) virtual
Reimplemented in FT8XXDriver.
Referenced by DriverBase().
invertDisplay()
virtual void DriverBase::invertDisplay () pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
isLandscape()
bool DriverBase::isLandscape () inline
Definition at line 55 of file DriverBase.h.
References backlightOn(), backlightPower(), displayPower(), displaySleep(), drawChar(), drawCircle(), drawCurve(), drawEllipse(), drawRect(), drawRoundRect(), drawTriangle(), fillCircle(), fillCurve(), fillEllipse(), fillQuad(), fillRect(), fillRoundRect(), fillScreen(), fillTriangle(), getTextBounds(), graphicsMode(), invertDisplay(), pushPixels(), readData(), readReg(), readStatus(), setCursor(), setTextColor(), setTextCursor(), setTextSize(), setXY(), softReset(), tColor, textMode(), textTransparent(), textWrite(), textWriteLn(), touched(), touchEnable(), touchRead(), waitPoll(), writeCommand(), writeData(), and writeReg().
Referenced by NumericEntry::Draw(), NumericEntry::ProcessTouch(), and NumericEntry::UpdateInput().
pushPixels()
virtual void DriverBase::pushPixels (uint32_t num, uint32_t color) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
readData()
virtual uint8_t DriverBase::readData () pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
readReg()
virtual uint8_t DriverBase::readReg (uint8_t reg) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
readStatus()
virtual uint8_t DriverBase::readStatus () pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
setCursor()
virtual void DriverBase::setCursor (int16_t x, int16_t y) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
setRotation()
virtual void DriverBase::setRotation (eDisplayRotation rotation) pure virtual
Implemented in FT8XXDriver.
Referenced by DriverBase().
setTextColor() [1/2]
virtual void DriverBase::setTextColor (uint32_t color) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
setTextColor() [2/2]
virtual void DriverBase::setTextColor (uint32_t color, uint32_t bgColor) pure virtual
Implemented in FT8XXDriver.
setTextCursor()
virtual void DriverBase::setTextCursor (uint16_t x, uint16_t y) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
setTextSize()
virtual void DriverBase::setTextSize (uint8_t s) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape(), UIRadioButton::Update(), and UICheckBox::Update().
setXY()
virtual void DriverBase::setXY (uint16_t x, uint16_t y) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
softReset()
virtual void DriverBase::softReset () pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
swapDisplay()
virtual void DriverBase::swapDisplay () virtual
Reimplemented in FT8XXDriver.
Referenced by getBackgroundColor(), and ScreenSaver::ScreenSaver().
textMode()
virtual void DriverBase::textMode () pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
textTransparent()
virtual void DriverBase::textTransparent (uint32_t foreColor) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
textWrite() [1/2]
virtual void DriverBase::textWrite (std::string text) pure virtual
Implemented in FT8XXDriver.
Referenced by height(), isLandscape(), and UIWindow::SetModal().
textWrite() [2/2]
virtual void DriverBase::textWrite (uint16_t x, uint16_t y, eUITextFont font, uint32_t textColor, uint16_t justification, std::string text) pure virtual
Implemented in FT8XXDriver.
textWriteLn()
virtual void DriverBase::textWriteLn (std::string text) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
touched()
virtual bool DriverBase::touched () pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
touchEnable()
virtual void DriverBase::touchEnable (bool value) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
touchRead()
virtual bool DriverBase::touchRead (uint16_t * x, uint16_t * y) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
waitPoll()
virtual bool DriverBase::waitPoll (uint8_t r, uint8_t f) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
width()
uint16_t DriverBase::width () inline
Definition at line 128 of file DriverBase.h.
References tftWidth.
Referenced by UIWindow::AddChildElement(), UIPrimitives::CircleOutline(), DriverBase(), and FT8XXDriver::Init().
writeCommand()
virtual void DriverBase::writeCommand (uint8_t d) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
writeData()
virtual void DriverBase::writeData (uint8_t d) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
writeReg()
virtual void DriverBase::writeReg (uint8_t reg, uint8_t val) pure virtual
Implemented in FT8XXDriver.
Referenced by isLandscape().
Member Data Documentation
backgroundColor
uint32_t DriverBase::backgroundColor protected
Definition at line 211 of file DriverBase.h.
Referenced by colorInterpolation565(), FT8XXDriver::fillScreen(), and getBackgroundColor().
driverType
eDriverType DriverBase::driverType protected
Definition at line 205 of file DriverBase.h.
Referenced by DriverBase().
rotation
eDisplayRotation DriverBase::rotation = eDisplayRotation::Landscape protected
Definition at line 207 of file DriverBase.h.
Referenced by DriverBase(), getRotation(), FT8XXDriver::invertDisplay(), and FT8XXDriver::setRotation().
tftHeight
uint16_t DriverBase::tftHeight protected
Definition at line 206 of file DriverBase.h.
Referenced by FT8XXDriver::drawCircle(), DriverBase(), FT8XXDriver::FT8XXDriver(), height(), and FT8XXDriver::Init().
tftWidth
uint16_t DriverBase::tftWidth protected
Definition at line 206 of file DriverBase.h.
Referenced by FT8XXDriver::drawCircle(), DriverBase(), FT8XXDriver::FT8XXDriver(), FT8XXDriver::Init(), and width().
The documentation for this class was generated from the following file:
Driver/DriverBase.h