uWindows: CheckBox Class Reference
CheckBox Class Reference
#include <CheckBox.h>
Static Public Member Functions
static Rectangle Draw (DriverBase &tft, bool sunken, bool isChecked, uint16_t x, uint16_t y, uint32_t textColor, uint32_t uncheckedColor, uint32_t checkColor, eUITextFont font, std::string text, bool textRight=true, bool is3D=true, uint8_t cornerRadius=4)
Detailed Description
Definition at line 11 of file CheckBox.h.
Member Function Documentation
Draw()
Rectangle CheckBox::Draw (DriverBase & tft, bool sunken, bool isChecked, uint16_t x, uint16_t y, uint32_t textColor, uint32_t uncheckedColor, uint32_t checkColor, eUITextFont font, std::string text, bool textRight = true, bool is3D = true, uint8_t cornerRadius = 4) static
Definition at line 3 of file CheckBox.cpp.
References UIPrimitives::FlatPanel(), FontHelper::GetTextRect(), Rectangle::height, UIPrimitives::RaisedPanel(), UIPrimitives::SunkenPanel(), UIPrimitives::Text(), Rectangle::update(), Rectangle::width, Rectangle::x1, Rectangle::x2, and Rectangle::y1.
Referenced by UICheckBox::Update().
The documentation for this class was generated from the following files:
UIElements/ControlDisplay/CheckBox.h
UIElements/ControlDisplay/CheckBox.cpp