uWindows: IconButton Class Reference
IconButton Class Reference
#include <IconButton.h>
Static Public Member Functions
static Rectangle Draw (DriverBase &tft, bool sunken, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint8_t iconHandle, Rectangle iconSize, int32_t textColor, uint32_t buttonColor, eUITextFont font, std::string text, bool is3D=true, uint8_t cornerRadius=4, uint8_t alpha=255, eVertAlign vertAlign=eVertAlign::Top)
Detailed Description
Definition at line 13 of file IconButton.h.
Member Function Documentation
Draw()
Rectangle IconButton::Draw (DriverBase & tft, bool sunken, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint8_t iconHandle, Rectangle iconSize, int32_t textColor, uint32_t buttonColor, eUITextFont font, std::string text, bool is3D = true, uint8_t cornerRadius = 4, uint8_t alpha = 255, eVertAlign vertAlign = eVertAlign::Top) static
Definition at line 4 of file IconButton.cpp.
References GDClass::Begin(), BITMAPS, Bottom, UIPrimitives::Center, Rectangle::center(), UIPrimitives::FlatPanel(), GD, FontHelper::GetTextRect(), Rectangle::height, UIPrimitives::RaisedPanel(), UIPrimitives::SunkenPanel(), UIPrimitives::Text(), Top, Logger::Trace(), Rectangle::update(), GDClass::Vertex2ii(), Rectangle::width, Point::x, Rectangle::x1, Rectangle::x2, Point::y, Rectangle::y1, and Rectangle::y2.
Referenced by SettingsButton::Update().
The documentation for this class was generated from the following files:
UIElements/ControlDisplay/IconButton.h
UIElements/ControlDisplay/IconButton.cpp