uWindows: UIElementGraph Class Reference
UIElementGraph Class Reference
#include <UIElementGraph.h>
Public Types
enum eGraphType { BarGraph, LineGraph }
Public Member Functions
UIElementGraph (DriverBase &tft, Rectangle location, CircularMinMaxBuffer &inValues, std::string itemLabel, eUITextFont font, tColor textColor, uint8_t textScale, tColor graphColor, tColor bgColor, eGraphType graphType=eGraphType::BarGraph, uint8_t cornerRadius=4, std::string elementName="", uint8_t alpha=255)
sTouchResponse ProcessTouch (Point touchPoint) override
virtual void Update () override
CircularMinMaxBuffer GetValues ()
void AddValue (float value)
Public Member Functions inherited from UIElement
UIElement (DriverBase &tft, Rectangle location, std::string elementName, eElementType elementType)
UIElement (const UIElement &other)
eElementType GetElementType ()
bool UpdatePending ()
int getElementID ()
bool isEnabled ()
void setEnabled (bool val)
void Invalidate ()
Rectangle GetLocation ()
Rectangle SetLocation (Rectangle newLoc)
std::vector< UIElement * > GetChildElements ()
virtual void AddChildElement (UIElement *element)
If a child UI element overrides this, it must call this as well
void SetParent (UIElement *element)
std::string getElementName ()
void UpdateChildren ()
~UIElement ()
Private Attributes
eUITextFont font
uint8_t cornerRadius
CircularMinMaxBuffer values
uint16_t prevValuesChecksum = 0
uint8_t alpha
std::string itemLabel
eGraphType graphType
tColor textColor
tColor graphColor
tColor bgColor
Additional Inherited Members
Protected Attributes inherited from UIElement
std::string elementName
Rectangle location
UIElement * parentElement
bool updatePending
bool enabled
uint32_t elementID
DriverBase & tft
eElementType elementType
std::vector< UIElement * > childElements
Detailed Description
Definition at line 12 of file UIElementGraph.h.
Member Enumeration Documentation
eGraphType
enum UIElementGraph::eGraphType
Enumerator
BarGraph
LineGraph
Definition at line 15 of file UIElementGraph.h.
Constructor & Destructor Documentation
UIElementGraph()
UIElementGraph::UIElementGraph (DriverBase & tft, Rectangle location, CircularMinMaxBuffer & inValues, std::string itemLabel, eUITextFont font, tColor textColor, uint8_t textScale, tColor graphColor, tColor bgColor, eGraphType graphType = eGraphType::BarGraph, uint8_t cornerRadius = 4, std::string elementName = "", uint8_t alpha = 255)
Definition at line 4 of file UIElementGraph.cpp.
References bgColor, cornerRadius, font, graphColor, graphType, UIElement::Invalidate(), itemLabel, and textColor.
Member Function Documentation
AddValue()
void UIElementGraph::AddValue (float value) inline
Definition at line 38 of file UIElementGraph.h.
References UIElement::Invalidate(), CircularMinMaxBuffer::PushItem(), and values.
GetValues()
CircularMinMaxBuffer UIElementGraph::GetValues () inline
Definition at line 33 of file UIElementGraph.h.
References values.
ProcessTouch()
sTouchResponse UIElementGraph::ProcessTouch (Point touchPoint) inline override virtual
Implements UIElement.
Definition at line 27 of file UIElementGraph.h.
References UIElement::elementID, NoOp, and Update().
Update()
void UIElementGraph::Update () override virtual
Implements UIElement.
Definition at line 21 of file UIElementGraph.cpp.
References alpha, AntiAliasFont26, bgColor, UIPrimitives::Center, Rectangle::center(), cornerRadius, UIPrimitives::DrawLine(), UIPrimitives::DrawPoint(), font, CircularMinMaxBuffer::GetChecksum(), CircularMinMaxBuffer::GetMax(), CircularMinMaxBuffer::GetMin(), CircularMinMaxBuffer::GetSize(), FontHelper::GetTextRect(), CircularMinMaxBuffer::GetValues(), graphColor, graphType, Rectangle::height, itemLabel, UIElement::location, prevValuesChecksum, UIPrimitives::RaisedPanel(), UIPrimitives::Text(), textColor, UIElement::tft, Logger::Trace(), UIElement::updatePending, values, Rectangle::width, Point::x, Rectangle::x1, Rectangle::x2, Rectangle::y1, and Rectangle::y2.
Referenced by ProcessTouch().
Member Data Documentation
alpha
uint8_t UIElementGraph::alpha private
Definition at line 49 of file UIElementGraph.h.
Referenced by Update().
bgColor
tColor UIElementGraph::bgColor private
Definition at line 52 of file UIElementGraph.h.
Referenced by UIElementGraph(), and Update().
cornerRadius
uint8_t UIElementGraph::cornerRadius private
Definition at line 46 of file UIElementGraph.h.
Referenced by UIElementGraph(), and Update().
font
eUITextFont UIElementGraph::font private
Definition at line 45 of file UIElementGraph.h.
Referenced by UIElementGraph(), and Update().
graphColor
tColor UIElementGraph::graphColor private
Definition at line 52 of file UIElementGraph.h.
Referenced by UIElementGraph(), and Update().
graphType
eGraphType UIElementGraph::graphType private
Definition at line 51 of file UIElementGraph.h.
Referenced by UIElementGraph(), and Update().
itemLabel
std::string UIElementGraph::itemLabel private
Definition at line 50 of file UIElementGraph.h.
Referenced by UIElementGraph(), and Update().
prevValuesChecksum
uint16_t UIElementGraph::prevValuesChecksum = 0 private
Definition at line 48 of file UIElementGraph.h.
Referenced by Update().
textColor
tColor UIElementGraph::textColor private
Definition at line 52 of file UIElementGraph.h.
Referenced by UIElementGraph(), and Update().
values
CircularMinMaxBuffer UIElementGraph::values private
Definition at line 47 of file UIElementGraph.h.
Referenced by AddValue(), GetValues(), and Update().
The documentation for this class was generated from the following files:
UIElements/UIElementGraph.h
UIElements/UIElementGraph.cpp