uWindows: Slider Class Reference
Slider Class Reference
#include <Slider.h>
Static Public Member Functions
static Rectangle Draw (DriverBase &tft, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint32_t textColor, uint32_t sliderBarColor, uint32_t sliderControlColor, eUITextFont font, int16_t value, int16_t minValue, int16_t maxValue, bool is3D=true, uint8_t alpha=255)
static uint16_t GetValue (Rectangle controlLocation, int16_t minValue, int16_t maxValue, Point pt)
Detailed Description
Definition at line 14 of file Slider.h.
Member Function Documentation
Draw()
Rectangle Slider::Draw (DriverBase & tft, uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint32_t textColor, uint32_t sliderBarColor, uint32_t sliderControlColor, eUITextFont font, int16_t value, int16_t minValue, int16_t maxValue, bool is3D = true, uint8_t alpha = 255) static
Definition at line 3 of file Slider.cpp.
References UIPrimitives::FlatPanel(), FontHelper::GetTextRect(), UIPrimitives::RaisedPanel(), UIPrimitives::Text(), and Logger::Trace().
GetValue()
uint16_t Slider::GetValue (Rectangle controlLocation, int16_t minValue, int16_t maxValue, Point pt) static
Definition at line 71 of file Slider.cpp.
References Rectangle::height, Rectangle::width, Point::x, Rectangle::x1, Rectangle::x2, Point::y, Rectangle::y1, and Rectangle::y2.
The documentation for this class was generated from the following files:
UIElements/ControlDisplay/Slider.h
UIElements/ControlDisplay/Slider.cpp