uWindows: FT8XXDriver Class Reference
FT8XXDriver Class Reference
#include <FT8XXDriver.h>
Public Member Functions
FT8XXDriver ()
FT8XXDriver (uint16_t width, uint16_t height, uint8_t cs=10, uint8_t rst=9)
void Init (uint16_t width, uint16_t height, uint8_t cs=10, uint8_t rst=9) override
void drawPixel (int16_t x, int16_t y, uint32_t color) override
void drawLine (int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint32_t color) override
void setRotation (eDisplayRotation rotation) override
void invertDisplay () override
void fillRect (int16_t x, int16_t y, int16_t w, int16_t h, uint32_t color) override
void fillScreen (uint32_t color) override
void drawRect (int16_t x, int16_t y, int16_t w, int16_t h, uint32_t color) override
void drawRect (int16_t x, int16_t y, int16_t w, int16_t h, uint32_t color, uint8_t lineWidth)
void drawCircle (int16_t x0, int16_t y0, int16_t r, uint32_t color) override
void drawCircle (int16_t x0, int16_t y0, int16_t r, uint32_t color, uint8_t lineWidth)
void fillCircle (int16_t x0, int16_t y0, int16_t r, uint32_t color) override
void drawTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint32_t color) override
void drawTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint32_t color, uint8_t lineWidth)
void fillTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint32_t color) override
void drawRoundRect (int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint32_t color) override
void drawRoundRect (int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint32_t color, uint8_t lineWidth)
void fillRoundRect (int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint32_t color) override
void drawChar (int16_t x, int16_t y, unsigned char c, uint32_t color, uint16_t bg, uint8_t size) override
void setCursor (int16_t x, int16_t y) override
void setTextColor (uint32_t c) override
void setTextColor (uint32_t c, uint32_t bg) override
void setTextSize (uint8_t s) override
void getTextBounds (std::string str, int16_t x, int16_t y, int16_t *x1, int16_t *y1, uint16_t *w, uint16_t *h) override
void drawEllipse (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint32_t color) override
void fillEllipse (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint32_t color) override
void drawCurve (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint8_t curvePart, uint32_t color) override
void fillCurve (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint8_t curvePart, uint32_t color) override
void softReset () override
void displayPower (bool powerMode) override
void displaySleep (bool sleepModeOn) override
void backlightOn (bool value) override
void backlightPower (uint8_t value) override
void touchEnable (bool value) override
bool touched () override
bool touchRead (uint16_t *x, uint16_t *y) override
void writeReg (uint8_t reg, uint8_t val) override
uint8_t readReg (uint8_t reg) override
void writeData (uint8_t d) override
uint8_t readData () override
void writeCommand (uint8_t d) override
uint8_t readStatus () override
bool waitPoll (uint8_t r, uint8_t f) override
void textWrite (uint16_t x, uint16_t y, eUITextFont font, uint32_t textColor, uint16_t justification, std::string text) override
void textMode () override
void setTextCursor (uint16_t x, uint16_t y) override
void textTransparent (uint32_t foreColor) override
void textWrite (std::string text) override
void textWriteLn (std::string text) override
void graphicsMode () override
void setXY (uint16_t x, uint16_t y) override
void pushPixels (uint32_t num, uint32_t color) override
void fillQuad (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, int16_t x3, int16_t y3, tColor color, bool triangled=true) override
void drawLine (int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint32_t color, uint8_t lineWidth)
void swapDisplay () override
void colorA (uint8_t alpha) override
void clearScreen (uint32_t clearToColor=Color::Black) override
~FT8XXDriver ()
Public Member Functions inherited from DriverBase
DriverBase (uint16_t width, uint16_t height, eDriverType driverType)
eDisplayRotation getRotation ()
bool isLandscape ()
uint16_t width ()
uint16_t height ()
uint16_t Color565 (uint8_t r, uint8_t g, uint8_t b)
uint16_t Color24To565 (int32_t color_)
uint16_t htmlTo565 (int32_t color_)
void Color565ToRGB (uint16_t color, uint8_t &r, uint8_t &g, uint8_t &b)
uint16_t colorInterpolation565 (uint16_t color1, uint16_t color2, uint16_t pos, uint16_t div)
uint16_t colorInterpolation565 (uint8_t r1, uint8_t g1, uint8_t b1, uint8_t r2, uint8_t g2, uint8_t b2, uint16_t pos, uint16_t div)
uint32_t getBackgroundColor ()
Private Attributes
uint8_t currentFont = 31
Additional Inherited Members
Protected Attributes inherited from DriverBase
eDriverType driverType
uint16_t tftWidth
uint16_t tftHeight
eDisplayRotation rotation = eDisplayRotation::Landscape
uint32_t backgroundColor
Detailed Description
Definition at line 10 of file FT8XXDriver.h.
Constructor & Destructor Documentation
FT8XXDriver() [1/2]
FT8XXDriver::FT8XXDriver ()
Definition at line 13 of file FT8XXDriver.cpp.
References GDClass::begin(), GD, DriverBase::tftHeight, DriverBase::tftWidth, and Logger::Trace().
FT8XXDriver() [2/2]
FT8XXDriver::FT8XXDriver (uint16_t width, uint16_t height, uint8_t cs = 10, uint8_t rst = 9)
Definition at line 4 of file FT8XXDriver.cpp.
References GDClass::begin(), GD, and Logger::Trace().
~FT8XXDriver()
FT8XXDriver::~FT8XXDriver ()
Definition at line 28 of file FT8XXDriver.cpp.
Referenced by pushPixels().
Member Function Documentation
backlightOn()
void FT8XXDriver::backlightOn (bool value) override virtual
Implements DriverBase.
Definition at line 328 of file FT8XXDriver.cpp.
References GD, REG_PWM_DUTY, and GDClass::wr().
Referenced by WindowManager::processTouch(), and WindowManager::WindowManager().
backlightPower()
void FT8XXDriver::backlightPower (uint8_t value) override virtual
Implements DriverBase.
Definition at line 340 of file FT8XXDriver.cpp.
References GD, REG_PWM_DUTY, and GDClass::wr().
Referenced by WindowManager::processTouch(), and WindowManager::WindowManager().
clearScreen()
void FT8XXDriver::clearScreen (uint32_t clearToColor = Color::Black) override virtual
Reimplemented from DriverBase.
Definition at line 437 of file FT8XXDriver.cpp.
References GDClass::Clear(), GDClass::ClearColorRGB(), and GD.
Referenced by Init(), pushPixels(), and WindowManager::Update().
colorA()
void FT8XXDriver::colorA (uint8_t alpha) override virtual
Reimplemented from DriverBase.
Definition at line 443 of file FT8XXDriver.cpp.
References GDClass::ColorA(), and GD.
Referenced by pushPixels().
displayPower()
void FT8XXDriver::displayPower (bool powerMode) override virtual
Implements DriverBase.
Definition at line 307 of file FT8XXDriver.cpp.
References GD, REG_GPIO, REG_PCLK, REG_PWM_DUTY, and GDClass::wr().
Referenced by displaySleep().
displaySleep()
void FT8XXDriver::displaySleep (bool sleepModeOn) override virtual
Implements DriverBase.
Definition at line 323 of file FT8XXDriver.cpp.
References displayPower().
drawChar()
void FT8XXDriver::drawChar (int16_t x, int16_t y, unsigned char c, uint32_t color, uint16_t bg, uint8_t size) override virtual
Implements DriverBase.
Definition at line 249 of file FT8XXDriver.cpp.
References GDClass::cmd_text(), GDClass::ColorRGB(), currentFont, GD, and OPT_CENTER.
drawCircle() [1/2]
void FT8XXDriver::drawCircle (int16_t x0, int16_t y0, int16_t r, uint32_t color) override virtual
Implements DriverBase.
Definition at line 170 of file FT8XXDriver.cpp.
drawCircle() [2/2]
void FT8XXDriver::drawCircle (int16_t x0, int16_t y0, int16_t r, uint32_t color, uint8_t lineWidth)
Definition at line 175 of file FT8XXDriver.cpp.
References GDClass::Begin(), GDClass::BlendFunc(), GDClass::ColorMask(), GDClass::ColorRGB(), DST_ALPHA, GD, ONE, ONE_MINUS_SRC_ALPHA, POINTS, GDClass::PointSize(), RECTS, DriverBase::tftHeight, DriverBase::tftWidth, GDClass::Vertex2f(), and ZERO.
drawCurve()
void FT8XXDriver::drawCurve (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint8_t curvePart, uint32_t color) override virtual
Implements DriverBase.
Definition at line 291 of file FT8XXDriver.cpp.
drawEllipse()
void FT8XXDriver::drawEllipse (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint32_t color) override virtual
Implements DriverBase.
Definition at line 281 of file FT8XXDriver.cpp.
drawLine() [1/2]
void FT8XXDriver::drawLine (int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint32_t color) override virtual
Implements DriverBase.
Definition at line 39 of file FT8XXDriver.cpp.
References GDClass::Begin(), GDClass::ColorRGB(), GDClass::End(), GD, LINES, GDClass::LineWidth(), and GDClass::Vertex2f().
Referenced by pushPixels().
drawLine() [2/2]
void FT8XXDriver::drawLine (int16_t x0, int16_t y0, int16_t x1, int16_t y1, uint32_t color, uint8_t lineWidth)
Definition at line 49 of file FT8XXDriver.cpp.
References GDClass::Begin(), GDClass::ColorRGB(), GD, LINES, GDClass::LineWidth(), and GDClass::Vertex2f().
drawPixel()
void FT8XXDriver::drawPixel (int16_t x, int16_t y, uint32_t color) override virtual
Implements DriverBase.
Definition at line 32 of file FT8XXDriver.cpp.
References GDClass::Begin(), GDClass::ColorRGB(), GD, POINTS, and GDClass::Vertex2f().
drawRect() [1/2]
void FT8XXDriver::drawRect (int16_t x, int16_t y, int16_t w, int16_t h, uint32_t color) override virtual
Implements DriverBase.
Definition at line 138 of file FT8XXDriver.cpp.
References GDClass::Begin(), GDClass::ColorRGB(), GD, LINE_STRIP, GDClass::LineWidth(), and GDClass::Vertex2f().
drawRect() [2/2]
void FT8XXDriver::drawRect (int16_t x, int16_t y, int16_t w, int16_t h, uint32_t color, uint8_t lineWidth)
Definition at line 150 of file FT8XXDriver.cpp.
References GDClass::Begin(), GDClass::ColorRGB(), GD, LINE_STRIP, GDClass::LineWidth(), and GDClass::Vertex2f().
drawRoundRect() [1/2]
void FT8XXDriver::drawRoundRect (int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint32_t color) override virtual
Implements DriverBase.
Definition at line 223 of file FT8XXDriver.cpp.
drawRoundRect() [2/2]
void FT8XXDriver::drawRoundRect (int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint32_t color, uint8_t lineWidth)
Definition at line 229 of file FT8XXDriver.cpp.
References GDClass::Begin(), GDClass::ColorRGB(), GD, GDClass::LineWidth(), RECTS, and GDClass::Vertex2f().
drawTriangle() [1/2]
void FT8XXDriver::drawTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint32_t color) override virtual
Implements DriverBase.
Definition at line 194 of file FT8XXDriver.cpp.
drawTriangle() [2/2]
void FT8XXDriver::drawTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint32_t color, uint8_t lineWidth)
Definition at line 200 of file FT8XXDriver.cpp.
References GDClass::Begin(), GDClass::ColorRGB(), GD, LINE_STRIP, GDClass::LineWidth(), and GDClass::Vertex2f().
fillCircle()
void FT8XXDriver::fillCircle (int16_t x0, int16_t y0, int16_t r, uint32_t color) override virtual
Implements DriverBase.
Definition at line 162 of file FT8XXDriver.cpp.
References GDClass::Begin(), GDClass::ColorRGB(), GD, POINTS, GDClass::PointSize(), and GDClass::Vertex2f().
fillCurve()
void FT8XXDriver::fillCurve (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint8_t curvePart, uint32_t color) override virtual
Implements DriverBase.
Definition at line 296 of file FT8XXDriver.cpp.
fillEllipse()
void FT8XXDriver::fillEllipse (int16_t xCenter, int16_t yCenter, int16_t longAxis, int16_t shortAxis, uint32_t color) override virtual
Implements DriverBase.
Definition at line 286 of file FT8XXDriver.cpp.
fillQuad()
void FT8XXDriver::fillQuad (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, int16_t x3, int16_t y3, tColor color, bool triangled = true) override virtual
Implements DriverBase.
Definition at line 419 of file FT8XXDriver.cpp.
References Poly::begin(), GDClass::ColorRGB(), Poly::draw(), GD, and Poly::v().
Referenced by pushPixels().
fillRect()
void FT8XXDriver::fillRect (int16_t x, int16_t y, int16_t w, int16_t h, uint32_t color) override virtual
Implements DriverBase.
Definition at line 122 of file FT8XXDriver.cpp.
References GDClass::Begin(), GDClass::ColorRGB(), GDClass::End(), GD, RECTS, and GDClass::Vertex2f().
fillRoundRect()
void FT8XXDriver::fillRoundRect (int16_t x0, int16_t y0, int16_t w, int16_t h, int16_t radius, uint32_t color) override virtual
Implements DriverBase.
Definition at line 239 of file FT8XXDriver.cpp.
References GDClass::Begin(), GDClass::ColorRGB(), GD, GDClass::LineWidth(), RECTS, and GDClass::Vertex2f().
fillScreen()
void FT8XXDriver::fillScreen (uint32_t color) override virtual
Implements DriverBase.
Definition at line 131 of file FT8XXDriver.cpp.
References DriverBase::backgroundColor, GDClass::Clear(), GDClass::ClearColorRGB(), and GD.
fillTriangle()
void FT8XXDriver::fillTriangle (int16_t x0, int16_t y0, int16_t x1, int16_t y1, int16_t x2, int16_t y2, uint32_t color) override virtual
Implements DriverBase.
Definition at line 211 of file FT8XXDriver.cpp.
References Poly::begin(), GDClass::ColorRGB(), Poly::draw(), GD, and Poly::v().
getTextBounds()
void FT8XXDriver::getTextBounds (std::string str, int16_t x, int16_t y, int16_t * x1, int16_t * y1, uint16_t * w, uint16_t * h) override virtual
Implements DriverBase.
Definition at line 275 of file FT8XXDriver.cpp.
graphicsMode()
void FT8XXDriver::graphicsMode () inline override virtual
Implements DriverBase.
Definition at line 91 of file FT8XXDriver.h.
Init()
void FT8XXDriver::Init (uint16_t width, uint16_t height, uint8_t cs = 10, uint8_t rst = 9) override virtual
Reimplemented from DriverBase.
Definition at line 20 of file FT8XXDriver.cpp.
References GDClass::begin(), clearScreen(), GD, DriverBase::height(), DriverBase::tftHeight, DriverBase::tftWidth, and DriverBase::width().
Referenced by WindowManager::WindowManager().
invertDisplay()
void FT8XXDriver::invertDisplay () override virtual
Implements DriverBase.
Definition at line 91 of file FT8XXDriver.cpp.
References Landscape, LandscapeInverted, LandscapeMirrored, LandscapeMirrorInverted, Portrait, PortraitInverted, PortraitMirrored, PortraitMirroredInveted, DriverBase::rotation, and setRotation().
pushPixels()
void FT8XXDriver::pushPixels (uint32_t num, uint32_t color) inline override virtual
Implements DriverBase.
Definition at line 93 of file FT8XXDriver.h.
References Color::Black, clearScreen(), colorA(), drawLine(), fillQuad(), swapDisplay(), tColor, and ~FT8XXDriver().
readData()
uint8_t FT8XXDriver::readData () override virtual
Implements DriverBase.
Definition at line 390 of file FT8XXDriver.cpp.
readReg()
uint8_t FT8XXDriver::readReg (uint8_t reg) override virtual
Implements DriverBase.
Definition at line 380 of file FT8XXDriver.cpp.
References GD, and GDClass::rd16().
readStatus()
uint8_t FT8XXDriver::readStatus () override virtual
Implements DriverBase.
Definition at line 400 of file FT8XXDriver.cpp.
setCursor()
void FT8XXDriver::setCursor (int16_t x, int16_t y) override virtual
Implements DriverBase.
Definition at line 256 of file FT8XXDriver.cpp.
setRotation()
void FT8XXDriver::setRotation (eDisplayRotation rotation) override virtual
Implements DriverBase.
Definition at line 59 of file FT8XXDriver.cpp.
References GDClass::cmd_setrotate(), GD, Landscape, LandscapeInverted, LandscapeMirrored, LandscapeMirrorInverted, Portrait, PortraitInverted, PortraitMirrored, PortraitMirroredInveted, and DriverBase::rotation.
Referenced by invertDisplay().
setTextColor() [1/2]
void FT8XXDriver::setTextColor (uint32_t c) override virtual
Implements DriverBase.
Definition at line 261 of file FT8XXDriver.cpp.
setTextColor() [2/2]
void FT8XXDriver::setTextColor (uint32_t c, uint32_t bg) override virtual
Implements DriverBase.
Definition at line 266 of file FT8XXDriver.cpp.
setTextCursor()
void FT8XXDriver::setTextCursor (uint16_t x, uint16_t y) inline override virtual
Implements DriverBase.
Definition at line 87 of file FT8XXDriver.h.
setTextSize()
void FT8XXDriver::setTextSize (uint8_t s) override virtual
Implements DriverBase.
Definition at line 271 of file FT8XXDriver.cpp.
setXY()
void FT8XXDriver::setXY (uint16_t x, uint16_t y) inline override virtual
Implements DriverBase.
Definition at line 92 of file FT8XXDriver.h.
softReset()
void FT8XXDriver::softReset () override virtual
Implements DriverBase.
Definition at line 302 of file FT8XXDriver.cpp.
References GDClass::cmd_coldstart(), and GD.
swapDisplay()
void FT8XXDriver::swapDisplay () override virtual
Reimplemented from DriverBase.
Definition at line 432 of file FT8XXDriver.cpp.
References GD, and GDClass::swap().
Referenced by pushPixels(), and WindowManager::Update().
textMode()
void FT8XXDriver::textMode () inline override virtual
Implements DriverBase.
Definition at line 83 of file FT8XXDriver.h.
textTransparent()
void FT8XXDriver::textTransparent (uint32_t foreColor) inline override virtual
Implements DriverBase.
Definition at line 88 of file FT8XXDriver.h.
textWrite() [1/2]
void FT8XXDriver::textWrite (uint16_t x, uint16_t y, eUITextFont font, uint32_t textColor, uint16_t justification, std::string text) override virtual
Implements DriverBase.
Definition at line 412 of file FT8XXDriver.cpp.
References GDClass::cmd_text(), GDClass::ColorRGB(), and GD.
textWrite() [2/2]
void FT8XXDriver::textWrite (std::string text) inline override virtual
Implements DriverBase.
Definition at line 89 of file FT8XXDriver.h.
textWriteLn()
void FT8XXDriver::textWriteLn (std::string text) inline override virtual
Implements DriverBase.
Definition at line 90 of file FT8XXDriver.h.
touched()
bool FT8XXDriver::touched () override virtual
Implements DriverBase.
Definition at line 361 of file FT8XXDriver.cpp.
References GD, GDClass::get_inputs(), GDClass::inputs, and GDClass::x.
Referenced by WindowManager::processTouch().
touchEnable()
void FT8XXDriver::touchEnable (bool value) override virtual
Implements DriverBase.
Definition at line 347 of file FT8XXDriver.cpp.
References GD, REG_TOUCH_ADC_MODE, REG_TOUCH_MODE, and GDClass::wr().
touchRead()
bool FT8XXDriver::touchRead (uint16_t * x, uint16_t * y) override virtual
Implements DriverBase.
Definition at line 369 of file FT8XXDriver.cpp.
References GD, GDClass::get_inputs(), GDClass::inputs, GDClass::x, and GDClass::y.
Referenced by WindowManager::processTouch().
waitPoll()
bool FT8XXDriver::waitPoll (uint8_t r, uint8_t f) override virtual
Implements DriverBase.
Definition at line 406 of file FT8XXDriver.cpp.
writeCommand()
void FT8XXDriver::writeCommand (uint8_t d) override virtual
Implements DriverBase.
Definition at line 395 of file FT8XXDriver.cpp.
References GDClass::cmd32(), and GD.
writeData()
void FT8XXDriver::writeData (uint8_t d) override virtual
Implements DriverBase.
Definition at line 385 of file FT8XXDriver.cpp.
writeReg()
void FT8XXDriver::writeReg (uint8_t reg, uint8_t val) override virtual
Implements DriverBase.
Definition at line 376 of file FT8XXDriver.cpp.
References GD, and GDClass::wr16().
Member Data Documentation
currentFont
uint8_t FT8XXDriver::currentFont = 31 private
Definition at line 106 of file FT8XXDriver.h.
Referenced by drawChar().
The documentation for this class was generated from the following files:
Driver/FT8XXDriver.h
Driver/FT8XXDriver.cpp